### PR TITLE
Add Twig loader

### PR DESCRIPTION
**Pull request by webberig**
Add Twig loader to the list of templating loaders

### CODE REVIEW

**Comment by webberig** [comment]
Added my secondary e-mail address that I used for the commit... should the clabot update its check automatically, or do I need to do something else ?

**Comment by montogeek** [comment]
@webberig You would need to change commit author. Or create a new PR with the correct commit author.

**Comment by webberig** [comment]
ok, think I succeeded :-)

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
