### PR TITLE
feature: pre-commit hooks

### PR DESCRIPTION
**Pull request by byzyk**
As per discussion in #2226

### CODE REVIEW

**Comment by byzyk** [comment]
This one is ready to go.

**Comment by montogeek** [comment]
What is the difference between this husky release candidate and the last stable one?

**Comment by byzyk** [comment]
In the RC version, you define hooks in the separate `husky` object. In previous stable version hooks were part of `scripts`. Not sure if there are any other improvements like performance etc but this is what they recommend to install now.

[Here](https://github.com/typicode/husky/blob/dev/CHANGELOG.md) is the full changelog.

**Comment by montogeek** [comment]
Thanks!

**Comment by montogeek** [comment]
@byzyk If you have time, please add lint-staged too. We are losing time checking for files that shouldn't be linted, for example, bash scripts.

**Comment by byzyk** [comment]
@montogeek sure man! will pick it up at the earliest, shouldn't take much time

**Pull request merged**
