### PR TITLE
Replace broken images in sponsor list

### LINKED ISSUE #1845: Broken images in backer list
I found broken images in the sponsor list so i think it should replaced these images.
because broken images is not good for a website and sponsors.

The path to the avatar image was passed through the API, but the resource was rejected to load.
I think that It looks like the 'opencollective' API did not send the sponsor data list correctly.

### PR DESCRIPTION
**Pull request by Lutece**
#1845 please look this issue

example

Resolves #1845

### CODE REVIEW

**Comment by montogeek** [comment]
Could you please share how it would look with the default webpack image?

**Comment by Lutece** [comment]
@montogeek 
I didn't understand the default webpack image.
Is it logo which have text?

**Comment by montogeek** [comment]
Sorry, I mean the image you added in your changes.
This one https://github.com/webpack/webpack.js.org/blob/master/src/assets/icon-square-small-slack.png.

That screenshot is before of after your changes?

**Comment by Lutece** [comment]
Before:
not_changed

After:
changed

**Comment by montogeek** [comment]
That's great! It would look nicer showing the logo when the backer doesn't have an avatar:
https://github.com/webpack/webpack.js.org/blob/0f3d8e6bb74a93988773241019118c960fc01f09/src/components/Support/Support.jsx#L103

**Comment by Lutece** [comment]
@montogeek 
Thanks :)

How long does it take to be reflected on website? :)

**Comment by montogeek** [comment]
This has to be reviewed, approved and merged. No idea if merging to master automatically deploys a new version.

**Comment by Lutece** [comment]
@montogeek 
Is it better that change it to look like a logo even when there is no avatar too?

**Comment by montogeek** [comment]
That would be cool, so it would look like a wall of avatars instead of images and texts. Can you try it to see how it looks?

**Comment by Lutece** [comment]
Give me a minute :)

**Comment by Lutece** [comment]
@montogeek
 
All_Changed:
all_changed

**Comment by montogeek** [comment]
It looks really nice! Thanks!

**Comment by Lutece** [comment]
@montogeek 

I pushed again :)
have a nice day 👍

**Comment by skipjack** [comment]
@Lutece I like the idea here, nice work. Doing a thorough review now and hopefully merging.

> No idea if merging to master automatically deploys a new version.

@montogeek it does automatically deploy although sometimes it takes a little while.

**Comment by skipjack** [comment]
Just tested, works fine. As soon as the build passes I'll get this merged.

**Comment by Lutece** [comment]
@skipjack Thanks! 👍

**Pull request merged**
