### PR TITLE
Add temporary warning

### PR DESCRIPTION
**Pull request by buoyantair**
I guess the "Prevent Duplication" section has to be re-written due to the changes :3 But for now maybe a flag that points to the updated plugin should be okay :D 

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by jeremenichelli** [comment]
I think that here, instead of just putting a warning here we should re-write the section to not include the old `CommonChunksPlugin`, it makes no sense to have a whole section based on it if it's not complaint with our latest release.

What do you think @montogeek

**Comment by buoyantair** [comment]
@jeremenichelli Yeah that's definitely what we need to do 👍

**Comment by montogeek** [comment]
We can't remove, there is a lot of people using v3, we know v4 docs are not ready to be finished, so there is hundred of developers waiting for full docs to start migrating.

Also, we haven't solved the docs versioning, if we had versioned docs we could do it, but we don't, so we still need to show both pages.

**Comment by jeremenichelli** [comment]
But if we solve that, then this content will lie in the 3.0 tag, right?

**Comment by montogeek** [comment]
@jeremenichelli Yes

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
