### PR TITLE
Update parser.md

### PR DESCRIPTION
**Pull request by prateekbh**
Fixed some typo

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hi @prateekbh can you please link to the source code or pull request after which this change became valid? So we could confirm it

**Comment by prateekbh** [comment]
isnt this just a simple typo?

**Comment by montogeek** [comment]
I can't find that method/property in webpack source code: https://github.com/webpack/webpack/search?q=expressionAnyMember&unscoped_q=expressionAnyMember

**Comment by prateekbh** [comment]
well the documentattion is here already: https://webpack.js.org/api/parser/#expressionanymember

its just that I guess the example got copied over from the `new ` section above this

**Comment by chenxsan** [comment]
`expressionAnyMember` got removed in this https://github.com/webpack/webpack/pull/9203/files#diff-313038f65941a3a6c139ebe61a484045ace246a429e31975f3606afdd95d977fL97, I'll file another PR to remove it once this one get merged.

**Pull request merged**
