### PR TITLE
Feature/mobile sidebar

### PR DESCRIPTION
**Pull request by skipjack**
WIP

Breaking out the mobile version of the Sidebar into a separate component.

cc @bebraw @SpaceK33z

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Tested this on a mobile device. It's looking good so far! When everything works I'll test again.

**Comment by skipjack** [comment]
@SpaceK33z ready for review again. As far as I can tell it's good on the dev-server as well as the in  the production build (using `npm run build-test` after).

**Comment by SpaceK33z** [comment]
@skipjack, I'll test this in a few hours :).

**Comment by SpaceK33z** [comment]
Tested this on an Android phone (latest Chrome) and iOS 10 with @indri-indri again.

- Did you try scrolling in the sidebar with a touch device? It seems a bit off (especially with iOS). Can't pinpoint a specific problem here, but may be worth trying it out.
- On iOS, the hamburger menu is not exactly centered. See screenshot:
img_7828

Other then that, looks good :).

**Comment by skipjack** [comment]
@SpaceK33z

- Didn't try on an actual touch device. CSS for it is pretty straightforward though, not sure what could be going on there. 

- Do have a method that closes it on click of content but I probably need to add touch handling.

- I noticed this as well. 

I'll see if I can knock some of these things out, if you guys have any advice on the scrolling issue I'm all ears.

**Comment by skipjack** [comment]
Ok fixed the icon and added touch handling for content. 

I think I see what you mean, scrolling seems to work fine but the usual continuation or "flick" scroll isn't behaving properly. Not really sure how to approach this, I did a bit of research but came up dry, mostly coming across older, more severe scrolling issues with`position: fixed`. I'd say we shouldn't let this hold us up from merging though.

Tested it on an iOS 10 device, @SpaceK33z feel free to give it another go.

**Comment by skipjack** [comment]
Nvm, `-webkit-overflow-scrolling: touch` to the rescue!

**Comment by SpaceK33z** [comment]
Hm, on my Android (with Chrome) I now get this when selecting something:



I can live it with though, so if it's not easy to fix, we can merge this PR already ;).

**Comment by skipjack** [comment]
@SpaceK33z hmm not able to replicate that one but I'll look into it more. I'm merging though, as even with that issue this is way better than what's currently in develop.

@NejcZdovc now that these changes are in develop you'd be more than welcome to update the normal Sidebar component as we were discussing.

**Comment by skipjack** [comment]
@SpaceK33z was able to replicate: `-webkit-tap-highlight-color: rgba(0,0,0,0);` to the rescue this time, pushing the fix to develop.

**Comment by SpaceK33z** [comment]
Awesome work @skipjack :).

**Pull request merged**
