### PR TITLE
fix custom blockquote

### PR DESCRIPTION
**Pull request by chenxsan**
Seems like 1.0.1 has bug causing issues like below:

image

By the way, we should consider eliminating those exotic packages as the code are not in control of this repository.

### CODE REVIEW

**Comment by montogeek** [comment]
> By the way, we should consider eliminating those exotic packages as the code are not in control of this repository.

This is be design. They should live outside of this repo, I can also add you as contributor to those plugins. What do you think?

**Comment by chenxsan** [comment]
I'm afraid I have no interest maintaining other plugins at the moment.

**Comment by montogeek** [comment]
How is that different from maintaining it here?

**Comment by montogeek** [comment]
In that case I can update the plugins and release new versions with the fixes.

**Pull request merged**
