### PR TITLE
Adds the missing 'run' command to server script.

### PR DESCRIPTION
**Pull request by Cambuchi**
Adds the "run" text to the CLI command. Without this you get an output of "unknown command: start"

### CODE REVIEW

**Comment by chenxsan** [comment]
Could you set up a reproducible repo, maybe on https://stackblitz.com/? As far as I know, `npm start` should just work as you can see from https://github.com/webpack/webpack.js.org/blob/master/package.json#L31.

**Comment by Cambuchi** [comment]
Using the config from the tutorial, with my script named "server". On a blank node.js stackblitz.
You can see `npm server` does not work but `npm run server` does.

image

**Comment by chenxsan** [comment]
> 

You are right, `npm server` won't work. But `start` is an exception, you can just run `npm start` or `yarn start` without that `run`. See https://stackoverflow.com/questions/51358235/difference-between-npm-start-and-npm-run-start/51358329 for some answers.

**Comment by Cambuchi** [comment]
Ah, I didn't realize that there were special script keywords, I thought the behavior was supposed to be like "build" in the earlier script example. Thanks for the information. Consider this closed.

**Pull request closed without merging**
