### PR TITLE
docs(sideEffects): documented rule and updated tree-shaking terms

### PR DESCRIPTION
**Pull request by pnevares**
Hello! 👋

- Removed a duplicated tip in tree-shaking.md
- Normalized references to the `sideEffects` property in package.json
- Documented `sideEffects` rule in module.md (though I'm not familiar with its use)

Would appreciate any feedback! Thank you!

### CODE REVIEW

**Comment by pnevares** [comment]
Looks like the latest Travis build failed because it triggered the Github API rate limit, not sure if I can start it off again.

**Comment by byzyk** [comment]
@montogeek ^ is that CI build fail issue resolved in `rebuild` or at least on the roadmap? If not I could have a look at it since it happens too often

**Comment by montogeek** [comment]
@byzyk I already tried to solve it: #1963

**Comment by byzyk** [comment]
@montogeek seems it didn't work, right?

**Comment by montogeek** [comment]
@byzyk No, it doesn't, It seems I am not reading TravisCI env variable correctly. Will debug

**Comment by pnevares** [comment]
Looking like the latest build was able to complete successfully 🤞

**Comment by montogeek** [comment]
Thank you

**Comment by pnevares** [comment]
Thank you for the merge!

**Pull request merged**
