### PR TITLE
docs(devServer): add sockPath docs

### PR DESCRIPTION
**Pull request by trescenzi**
[Related PR](https://github.com/webpack/webpack-dev-server/pull/1553)

This adds documentation for the `sockPath` option added by the related PR above.

### CODE REVIEW

**Comment by montogeek** [comment]
This change is already released?

**Comment by evilebottnawi** [comment]
@trescenzi in near future

**Comment by arusahni** [comment]
Hi, this appears to be in 3.2.1.

**Comment by EugeneHlushko** [comment]
@trescenzi are you still around to apply suggestion?

**Comment by trescenzi** [comment]
@EugeneHlushko let me know if there's anything else I should change.

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
