### PR TITLE
docs(getting-started): use var instead to match the rest of the guides

### PR DESCRIPTION
**Pull request by kelvinau**
I understand that there's a PR for this similar issue already https://github.com/webpack/webpack.js.org/pull/2614, but it's been 3 months and we haven't had any updates from the last PR regarding to the `const` reassignment fix.

A simpler fix will be only changing **docs(getting-started)** to replace it `let` with `var`, as that's the only part inconsistent with the others.

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hello @kelvinau 
I understand how critical it is to update this example with the modern `let` syntax, but i would suggest we don't rush and wait two more weeks here and give original author a warning or something.

What do you think @montogeek ?

**Comment by kelvinau** [comment]
Understood. I can make the changes for `let` and `const` instead too, if @anayadesign hasn't responded after.

**Comment by montogeek** [comment]
@kelvinau Friendly ping

**Comment by kelvinau** [comment]
This was fixed by #2962 which extended #2614 already.

**Pull request closed without merging**
