### PR TITLE
Fix Build Issues

### PR DESCRIPTION
**Pull request by skipjack**
fix(dropdown): convert all tabs to spaces

### CODE REVIEW

**Comment by skipjack** [comment]
@Munter this is a bit bizarre -- I'm getting all 200s when I go to the actual site or `curl` it but for some reason on Travis it gets all 502s... I've rerun the build a few times already all with the same result.

**Comment by Munter** [comment]
```
$ curl https://jspm.io -I
HTTP/1.1 502 Bad Gateway
Date: Wed, 12 Jul 2017 07:46:38 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d65c6b17eead63406cc24a080503b3b8d1499845598; expires=Thu, 12-Jul-18 07:46:38 GMT; path=/; domain=.jspm.io; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Server: cloudflare-nginx
CF-RAY: 37d263cbf89e3cef-CPH
```

This seems to happen on `HTTP HEAD` only. I have special casing for retrying with the slower and more resource intensive `HTTP GET` here: https://github.com/Munter/hyperlink/blob/master/lib/index.js#L172-L175

It seems another case needs to be added here

**Comment by skipjack** [comment]
@Munter ah man that's a pain... what would you even flag on from that response? I may just rethink this link for now as it's not really crucial to our docs -- keep us posted though if you find a good solution and re-release `hyperlink`.

**Comment by Munter** [comment]
It's an easy fix. I already have a retry mechanism for when a server hasn't implemented `HTTP HEAD`. It just doesn't activate on `5xx` responses. I'll get this out pretty soon.

**Comment by Munter** [comment]
I released a new major version that includes this fix and also comes with a new `canonicalroot` option that should be helpful if you ever need canonical urls in your build output and want to test things locally

**Pull request merged**
