### PR TITLE
Update entry-points.md

### PR DESCRIPTION
**Pull request by glennreyes**
Just a little tweak of the entry point intro.

### CODE REVIEW

**Comment by bebraw** [comment]
Can you PR against `develop`? Thanks!

**Comment by glennreyes** [comment]
@bebraw Sure done! Will do it with the other PR too.

**Comment by bebraw** [comment]
@glennreyes The other one was merged already. I synced `master` with `develop` so we are good again. 👍

**Comment by SpaceK33z** [comment]
@bebraw, oh you already fixed my mistake? Noticed it a few seconds after hitting the merge button, sorry.

**Comment by SpaceK33z** [comment]
Haha okay saw your other comment, so it's fixed :).

**Comment by SpaceK33z** [comment]
Thanks!

**Pull request merged**
