### PR TITLE
misc(updates) Upgrade react to 16.6, stop loading gitter for all user…

### PR DESCRIPTION
**Pull request by EugeneHlushko**
- update react, dom, prop types
- only load gitter after clicking icon. Only a small % of users does click that gitter icon. Now its loaded on-demand

According to speed audit, this is 1100ms faster to interactive than before.

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
According to speed audit, this is **1100MS** faster to interactive than before.

**Comment by anshumanv** [comment]
I think you can set netlify to update preview link in a single comment rather than a new comment for all commits pushed. 🤔

**Comment by EugeneHlushko** [comment]
It is because i've pushed another commit later :)

**Comment by montogeek** [comment]
Very good! (Hattori Hanzō voice)

**Comment by anshumanv** [comment]
> It is because i've pushed another commit later :)

Yes @EugeneHlushko it basically updates the original comment with the new link and commit, I think it's default behavior though, not entirely sure why it didn't happen here 🤔

**Pull request merged**
