### PR TITLE
remove deprecated loaders

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- [raw-loader](https://github.com/webpack-contrib/raw-loader)
- [url-loader](https://github.com/webpack-contrib/url-loader)
- [file-loader](https://github.com/webpack-contrib/file-loader)

### CODE REVIEW

**Review by chenxsan — COMMENTED** [review]
I would rather keeping those pages although they're deprecated. Those are used a lot and there would be many pages on the internet linking to them. Removing them would break users' expectation.

Or we can remove them and redirect the removed url to the v4 version.

cc @alexander-akait what do you think here.

**Comment by alexander-akait** [comment]
@chenxsan it makes sense to redirect :+1: it will be better since most of developers will move to assets modules instead using `file-loader`/`url-loader`/`raw-loader`

**Comment by jamesgeorge007** [comment]
> Or we can remove them and redirect the removed url to the v4 version.

How to go about implementing the redirects? I can see a few listed here:-
https://github.com/webpack/webpack.js.org/blob/747cb66122a5c5812ba7daa8fafde3b827dfad4e/webpack.ssg.js#L58

**Comment by chenxsan** [comment]
> > Or we can remove them and redirect the removed url to the v4 version.
> 
> How to go about implementing the redirects? I can see a few listed here:-
> https://github.com/webpack/webpack.js.org/blob/747cb66122a5c5812ba7daa8fafde3b827dfad4e/webpack.ssg.js#L58

Spot on.

**Review by chenxsan — APPROVED** [review]

**Pull request merged**
