### PR TITLE
docs(all): add doctype for valid HTML in all documentation

### PR DESCRIPTION
**Pull request by TheDutchCoder**
As pointed out in Issue #1866, this should be added for valid HTML.

### CODE REVIEW

**Comment by montogeek** [comment]
There are other placer where this happen, It is ok if I add them into this branch?

**Comment by TheDutchCoder** [comment]
@montogeek good point, I can skim through them as well, but feel free to do so of course.

**Comment by jeremenichelli** [comment]
Can we organize this a little better? Because if not someone will look at this PR and the issues and think this wasn't done. It's important to make easy to track what has been changed for long tasks like this.

That said, are there more places where this is happening? Or we are sure these are all the doctypes that were missing?

**Comment by TheDutchCoder** [comment]
@jeremenichelli I've scanned all Guides and updated where required. Do you want to expand this to all sections of the website instead? I'm okay with that, it'll just widen the scope a bit more.

**Comment by jeremenichelli** [comment]
I would love to have each section as separate PRs, if that's already not possible, then list in the title of this PR all the sections you covered.

**Comment by montogeek** [comment]
I only found another place missing, it seems there is not more places.

**Pull request merged**
