### PR TITLE
docs for dynamically entry

### PR DESCRIPTION
**Pull request by jerexyz**
https://github.com/webpack/webpack/issues/4456

### CODE REVIEW

**Comment by bebraw** [comment]
Can you sign the CLA? Thanks.

**Comment by jerexyz** [comment]
the second commit was signed,my local git config was wrong.

**Comment by bebraw** [comment]
Feel free to re-open. The fix is valid. I was just waiting for the checks to complete. 👍

**Comment by bebraw** [comment]
Nm. Just saw https://github.com/webpack/webpack.js.org/pull/1028 .

**Pull request closed without merging**
