### PR TITLE
remove unnecessary comma

### PR DESCRIPTION
**Pull request by monkindey**

### CODE REVIEW

**Comment by simon04** [comment]
Trailing commas are often used with intent: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

Therefore I'm reluctant removing it.

**Comment by bebraw** [comment]
I think the underlying problem is that we don't lint the examples. Either is fine by me. It's easier to manage diffs with trailing commas, though.

**Comment by monkindey** [comment]
Thanks for your reply, I learn a lot from this conversation. There are the good point using the trailing commas. I just be used to clear the trailing commas to be consistent with the JSON syntax.

**Comment by bebraw** [comment]
Yeah, no way to avoid them in vanilla JSON. 😞

**Comment by simon04** [comment]
Let's keep it as it is.

**Pull request closed without merging**
