### PR TITLE
Use Network-first strategy for service worker

### PR DESCRIPTION
**Pull request by chenxsan**
closes https://github.com/webpack/webpack.js.org/issues/4340
closes https://github.com/webpack/webpack.js.org/issues/4458

We will do this in multiple steps:

1. Implement `NetworkFirst` strategy for those webpack generated assets so service worker will always fetch them from network first and only fallback to cache when offline
2. Since `NetworkFirst` strategy is used, we don't really need to activate the new service worker as soon as possible, i.e., the `UPDATE` button at the right bottom can be removed. But we'll do it after maybe two months to make sure most users have updated to the latest service worker.

cc @alexander-akait

### CODE REVIEW

**Comment by montogeek** [comment]
Current Cache first strategy is good for which kind of sites?

**Review by montogeek — DISMISSED** [review]

**Comment by montogeek** [comment]
Would be also worth to run a poll to see how many actually use the site offline.

**Comment by chenxsan** [comment]
> Current Cache first strategy is good for which kind of sites?

Actually I have no idea why workbox precaching would default to Cache first without alternative strategies. It's a nightmare for a documentation site as users have to click the UPDATE button in the page all the time when we update the site frequently.

> Would be also worth to run a poll to see how many actually use the site offline.

Yeah, once I wanted to remove the offline function but since it's been introduced a long time ago, I have no idea whether we should do it.

Network first strategy would be the most safe option for a documentation site as users can still check it even when they're offline.

**Comment by alexander-akait** [comment]
> Network first strategy would be the most safe option for a documentation site as users can still check it even when they're offline.

:+1:

**Comment by chenxsan** [comment]
Let's ship it now, we'll see how it works before removing that UPDATE button.

**Pull request merged**
