### PR TITLE
Docs(config) :remove test/include/exclude from rule set conditions

### LINKED ISSUE #3625: Document webpack change: fix(#10552) remove test/include/exclude from rule set conditions
*A pull request by @vankop was merged and maintainers requested a documentation change.*

See pull request: https://github.com/webpack/webpack/pull/10557

---

**What kind of change does this PR introduce?**

bugfix #10552 

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

Yes

**What needs to be documented once your changes are merged?**

Remove test/include/exclude from condition in docs
https://webpack.js.org/configuration/module/#condition

NOTE: This is not related to `Rule.test`, `Rule.include` and `Rule.exclude`. It only applies to `Rule.resource.test`, `Rule.resource.include`, `Rule.resource.exclude`, and the same on `Rule.resourceQuery`, `Rule.issuer`, `Rule.compiler`, etc.

### PR DESCRIPTION
**Pull request by jeffin143**
fix #3625 

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].

### CODE REVIEW

**Comment by anshumanv** [comment]
Not a good practice, I literally said it's wip - https://github.com/webpack/webpack.js.org/issues/3625#issuecomment-600494356

Now I'll have to stash my changes, please don't repeat this. 😕

**Comment by jeffin143** [comment]
I am really sorry, I just saw the issue , and raised it once . Didn't look at your comments 

I closed it , and won't repeat it

**Comment by EugeneHlushko** [comment]
Hi @anshumanv 
We dont currently have SLAs so i guess this is right to be closed despite you not submitting the PR first.

@jeffin143 we might consider adding SLAs similar to how opencollective does it, e.g. if there is not a PR for minor sized work for 7 days we un assign the initial requester.

Right now i feel like we are moving fast enough with the outstanding documentation requests.

The comma corrections and small grammar fixes PRs obviously are overwhelming due to them still being paid for, they are not a priority unless we are out of documentation errors and requests so i keep encouraging everyone to first correct documentation gaps and errors before resorting to grammar and commas work whatsoever.

Very nice to have such great contributors around, keep up the good job and focus on the important

**Comment by jeffin143** [comment]
I am totally ok with anybody attacking the issue , we have 150 of them :) 

It has happened with me in past too , where somebody have commented and I have overlooked it , an example - https://github.com/webpack/webpack.js.org/issues/3447#issuecomment-570469449

But I ll make sure it doesn't happen :) again.

@EugeneHlushko , I don't think sla are important as of now since there aren't many contributors currently and hence evey one are mutually ok with the things , until and unless there isn't a big argument :)

**Comment by EugeneHlushko** [comment]
Hi @anshumanv 
You said it was WIP, any ETA?

**Pull request closed without merging**
