### PR TITLE
Fix Testing/Linting Issues

### LINKED ISSUE #1041: npm run test  => error
after `npm install`, `npm run build`, `npm run test`, I  got some eslint errors:
image

Did I forget something?

### PR DESCRIPTION
**Pull request by skipjack**
Fixes #1041

This is an attempt to resolve all of our linting and testing issues. It contains:

- Removal of eslint script for markdown code blocks
- Fixes for a whole slew of markdownlint errors
- Minor updates to `.markdownlintrc` to loosen rules

Take aways...

- We could add eslint-ing for markdown code blocks if someone takes the time to write a separate eslintrc for that. I'm not sure how much value it really adds though.
- Certain patches I made on the plugin markdown files should be carried over to their respective readmes in per-repo PRs. Or we should figure out how to exclude the auto-fetched files from the linting process.

In general, I think we should try to be a little more careful about adding scripts or processes before they're fully ready. Also, for the ones that we do want to keep, these should actually fail hard in the travis build so we pick up on things like markdown or prose issues instead of letting them build up.

The last one that needs fixing is `lint:social`. It only emits warnings right now but for some reason it's still failing hard. @bebraw @TheLarkInn any ideas? (I forget who implemented that one)

Once we get `lint:social` either removed or resolved, I'll rebase to resolve the conflicts and this should be good to go.

### CODE REVIEW

**Comment by simon04** [comment]
Great work. Once all issues are resolved, those tests also should be added to CI.

Running `alex *.md content/` brings up the following 50 warnings: https://gist.github.com/simon04/b823cd424f1f3645faa7592e5f52f91c

```
$ node_modules/.bin/alex --version    
3.1.0
```

**Comment by bebraw** [comment]
> The last one that needs fixing is lint:social. It only emits warnings right now but for some reason it's still failing hard. @bebraw @TheLarkInn any ideas? (I forget who implemented that one)

@wooorm Any idea on this alex warning issue?

**Comment by wooorm** [comment]
> @wooorm Any idea on this alex warning issue?

A “warning” in alex’s sense is enough to fail the tests I think. You could go with `alex --diff` to only check the changed lines in Travis though?

**Comment by skipjack** [comment]
@webpack/documentation-team idk after taking a look at the warnings I saw locally and the ones @simon04 shared, I'd say the way it's configured now is way too tight for our use case. The fact that it's flagging things like `disabled`, `executed` and `bigger` makes it seem like it's going to get in our way more than help us. 

Has anyone found it useful so far? Or is anyone familiar enough with it to re-configure it in a looser way? Either way, imho I think we should remove it for now and re-integrate more thoroughly later on if anything. I'd like to get this merged and back into the CI process sooner rather than later so I don't have to go through fixing a bunch more errors after the next round of PRs (would be nice if markdownlint had a `fix` option like eslint 😁).

**Comment by wooorm** [comment]
Note that you could also add an [`.alexrc`](https://github.com/wooorm/alex#alexrc) file, which turns off these warnings, like so:

```json
{
  "allow": [
    "bigger",
    "color",
    "lies",
    "execute",
    "executed",
    "execution",
    "host-hostess",
    "disabled",
    "crash",
    "failure",
    "period",
    "hook",
    "dirty",
    "host-hostess",
    "fire",
    "remains",
    "jade",
    "failed"
  ]
}
```

Or, alternatively, run alex as previously mentioned as `alex --diff`.
Or finally, I personally use alex on my computer only, once in a while, to check markdown files — not in a CI.

**Comment by skipjack** [comment]
@wooorm ah ok... I'll try that and then we can continue to fiddle around this more down the road (or just keep adding words to the `allow`ed list.

**Comment by skipjack** [comment]
@wooorm that solution works.

@webpack/documentation-team just need to test `proselint` and we should be good to go.

**Comment by skipjack** [comment]
Ok rebased and resolved conflicts... 

> Once all issues are resolved, those tests also should be added to CI.

Definitely agree... is this as simple as adding a line to the `travis.yml`? If someone points me in the right direction we can knock this out of the way now as well.

**Comment by bebraw** [comment]
Yeah, tweak `travis.yml` so it picks up the tests you want.

**Comment by skipjack** [comment]
@bebraw ok how do I do that? I'm not too familiar with travis...

**Comment by skipjack** [comment]
Ah I see looks like I have to change `deploy.sh`?

**Comment by skipjack** [comment]
This should be good to go 👍 , all tests ran and the CI build passed.

**Pull request merged**
