### PR TITLE
infra(lint) make links check manual

### PR DESCRIPTION
**Pull request by EugeneHlushko**
as per title, to cut build times

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Thanks!

**Comment by montogeek** [comment]
lol

**Comment by EugeneHlushko** [comment]
Made a screen shot as a good memory of such occasion :D

**Comment by Munter** [comment]
This one was a bit too aggressive. I've opened a PR to bring back the part of the link checking that ensures we don't have any internal broken links

**Pull request merged**
