### PR TITLE
Modify a small missing part of translation

### PR DESCRIPTION
**Pull request by escawn**
Modify a small missing part of translation

### CODE REVIEW

**Comment by skipjack** [comment]
I think you want to target this branch to the `translation` branch or one of the other repositories (e.g. webpack-china or webpack-korea). 

cc @bebraw @lcxfs1991 @Lutece

**Comment by dear-lizhihua** [comment]
你应该向 https://github.com/webpack-china/webpack.js.org 提交 pull-request。
You should submit a request to https://github.com/webpack-china/webpack.js.org.

**Comment by skipjack** [comment]
Ok @escawn I'm going to close, please see @dear-lizhihua's comment above.

**Comment by escawn** [comment]
I'm sorry to make such a mistake，sorry to add your work.Thank you for your
reply!

2017-07-29 23:53 GMT+08:00 Greg Venech <notifications@github.com>:

**Comment by skipjack** [comment]
@escawn no problem, happy to see all this work happening on the internationalized docs!

**Pull request closed without merging**
