### PR TITLE
Add/extend plugin documentation

### PR DESCRIPTION
**Pull request by simon04**
- Add introduction page on plugins from webpack/webpack readme
- Add html-webpack-plugin documentation
- Add environment-plugin documentation

### CODE REVIEW

**Comment by bebraw** [comment]
Can you fix that proselint error? Good to merge after that.

**Comment by simon04** [comment]
I fixed the proselint error (actually originating from https://github.com/webpack/webpack/commit/b04f6d7491c5e9154d67ddefe1b466e140766863). I don't know what problem Travis is seeing now.

**Comment by bebraw** [comment]
Basically Travis tells that it's failing to find some links it expects. I guess building the project locally and inspecting the result might give more insight to that.

**Comment by simon04** [comment]
Ahh, the Travis previously did not `npm run fetch`. Fixed that in 2bc4e06.

**Comment by bebraw** [comment]
Thanks. Good fix. Let's roll with this.

**Pull request merged**
