### PR TITLE
Revert "cacheGroups"

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Reverts webpack/webpack.js.org#2227

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
I dont know why this got merged, result is on screenshot:

screen shot 2018-12-17 at 11 17 54 am


Basically before `reuseexistingChunk` example there is duplicated heading of the next section, also it is misformatted, we use curly for cacheGroup abstraction as its not real cacheGroup name: `splitChunks.cacheGroups.{cacheGroup}.test` vs `splitChunks.cacheGroups.cacheGroup.test`

**Comment by EugeneHlushko** [comment]
We would need to revert exactly that one commit and not all these, can you handle that @montogeek ?

**Comment by montogeek** [comment]
Yep, I will revert it.

**Comment by montogeek** [comment]
It got merged because I didn't pay enough attention.

**Comment by montogeek** [comment]
Thank you

**Pull request merged**
