### PR TITLE
fix(guides): update production guide, fix #2387

### LINKED ISSUE #2387: Documentation confusion: manually configure DefinePlugin with `mode` present or not?
As the [docs on Mode concept](https://webpack.js.org/concepts/mode/#usage) goes, when `mode` is set, webpack automatically configures some plugins like `DefinePlugin`.
image

But as the [production guide](https://webpack.js.org/guides/production/#specify-the-environment) goes, even with `mode` set to `'production'`, I should manually set `process.env.NODE_ENV` in `DefinePlugin`.
image

This really confused me. Which one should I follow?

---

This issue was moved from webpack/webpack#7779 by @montogeek. Original issue was by @SevenOutman.

### PR DESCRIPTION
**Pull request by SevenOutman**
Add explanation to [Specify the Environment](https://webpack.js.org/guides/production/#specify-the-environment) section in production guide, which is no longer effective with webpack v4. See advice here https://github.com/webpack/webpack.js.org/issues/2387.

P.S. I think it's better adding an instruction than removing the whole section, for there're users of previous major versions. If there's a separate branch and url for v3 docs, I'll add changes and remove the whole section in master.

### CODE REVIEW

**Comment by montogeek** [comment]
It seems that we could drop the entire section.

**Comment by SevenOutman** [comment]
@montogeek What about v3 users? Do we have v3 docs available for them?

**Comment by EugeneHlushko** [comment]
I dont think we should remove it. It does need a big change, the title can be `Specify the mode`, and info about NODE_ENV relation to libraries is useful, just make it v4 compliant

**Comment by EugeneHlushko** [comment]
Right now the v3 docs are only available locally, there is an outsdanding issue which (not without luck) can get resolved hopefully this year... Its not progressing quickly

**Comment by SevenOutman** [comment]
@EugeneHlushko Agreed. An ideal solution could be removing the entire section from v4 docs with there being standalone v3 docs. Adding this instruction is just a temporary approach while v3 docs is still wip.

**Comment by SevenOutman** [comment]
@montogeek Changes have been made according to https://github.com/webpack/webpack.js.org/pull/2388#pullrequestreview-139868481 and https://github.com/webpack/webpack.js.org/pull/2388#issuecomment-407393800

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
