### PR TITLE
doc: HashedModuleIdsPlugin Namespace

### PR DESCRIPTION
**Pull request by icirellik**
This add the `.ids` namespace to the `HashedModuleIdsPlugin`
documentation.

### CODE REVIEW

**Review by chenxsan — APPROVED** [review]
Can you sign CLA?

**Comment by icirellik** [comment]
@chenxsan I have signed it...is there any way to rerun the check?

**Comment by snitin315** [comment]
Close and open your PR.

**Comment by evilebottnawi** [comment]
Bug with CLA, ignore this

**Comment by chenxsan** [comment]
@icirellik Thank you for your contribution to webpack.

**Pull request merged**
