### PR TITLE
Update migration guide title to reflect that it applies to both v2 and v3

### PR DESCRIPTION
**Pull request by eteeselink**

### CODE REVIEW

**Comment by skipjack** [comment]
I'm actually not sure it does apply to v3 -- I was about to submit a PR that makes this clear with an intro paragraph. I may change the title as well.

**Comment by skipjack** [comment]
@eteeselink thanks for your contribution, I'm going to close in favor of #1426 which should be merged soon. Feel free to continue the discussion here, or on that PR though.

**Comment by eteeselink** [comment]
@skipjack hmm are you sure? I just upgraded from v1 straight to v3 by doing the steps in this guide. Shouldn't v2 to v3 be a noop for virtually all cases? Anyway great work and feel free to ignore this PR indeed! :-)

**Comment by skipjack** [comment]
Yeah, the migration from v2 to v3 is pretty painless which is why you probably didn't notice any issues after following the steps for v2. I did a quick scan and definitely didn't see any mention of v3 in the guide (aside from some "this may be deprecated in v3" statements). 

If someone wanted to update the guide to include v2 to v3 and then rename it _Migrating Versions_ or something like that I wouldn't be opposed to it. Not sure that's necessary though.

**Pull request closed without merging**
