### PR TITLE
docs(plugins) SplitChunks defaults update

### LINKED ISSUE #2323: [webpack 5] SplitChunksPlugin defaults - documentation update
see webpack/webpack#7599

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Update defaults for SplitChunks on:
https://webpack.js.org/plugins/split-chunks-plugin/#defaults
https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks

Fixes #2323

### CODE REVIEW

**Comment by byzyk** [comment]
Looks good 👍🏽But this doc update is for webpack 5. Should we merge to `master` after webpack release or do we have separate v5 docs branch?

**Comment by EugeneHlushko** [comment]
Ah in that case we stall it, will change to next or leave on master once we prepare for v5 and decide on the strategy

**Comment by montogeek** [comment]
@EugeneHlushko Please change base branch to `next`

**Comment by montogeek** [comment]
I can do it too :D

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
