### PR TITLE
Mode/to configuration

### PR DESCRIPTION
**Pull request by EugeneHlushko**
After getting feedback on twitter, i am moving mode configuration docs to configuration section.

- moved page
- updated links
- created redirect

### CODE REVIEW

**Comment by montogeek** [comment]
We need more eyes on this. cc @TheLarkInn

**Comment by EugeneHlushko** [comment]
Amazing, @montogeek what you think?

**Comment by EugeneHlushko** [comment]
Merging it, will observe live website for any anomalities ;]

**Comment by EugeneHlushko** [comment]
It works, thanks everyone

**Pull request merged**
