### PR TITLE
Fix typo in code splitting documentation

### PR DESCRIPTION
**Pull request by foolip**
_describe your changes..._

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/

### CODE REVIEW

**Comment by anshumanv** [comment]
Please sign the CLA :)

**Comment by foolip** [comment]
I'm looking into how to sign it, I suspect I can't sign as an individual as I work for Google.

**Comment by foolip** [comment]
Alright, CLA signed, it was allowed.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
