### PR TITLE
fix: popover functionality

### PR DESCRIPTION
**Pull request by snitin315**
Fix https://github.com/webpack/webpack.js.org/issues/3990

Fix https://github.com/webpack/webpack.js.org/pull/3991

### CODE REVIEW

**Comment by rahul3v** [comment]
#3991 was the commit I requested  for #3990, there is nothing to fix in #3991,

How come #3991 not merged, just surprised :(

**Comment by snitin315** [comment]
@rahul3v CLA was not accepted.

**Comment by rahul3v** [comment]
@snitin315 well it never asked for, I already merged few commits at webpack before, so....! ,
I guess I have to ignore this one, as it's done now  :)

**Comment by snitin315** [comment]
Actually, we changed our CLA recently, that's why - https://cla.openjsf.org/

**Comment by rahul3v** [comment]
@snitin315 you should have informed before requesting the similar merge, so that I could accept the CLA and able to merge the same, Nothing to say now, So, It's fine :)

**Comment by snitin315** [comment]
Sorry about that, I should have asked. But, the PR was very old and usually folks abandon PRs after this long. I time to time recreate old and stale PRs and merge them.

**Comment by rahul3v** [comment]
that might needed, only if anything need to change, what just happened was really a bad practice for open-source :)
you should inform if you do anything similar in future, I mean to anyone :)

**Pull request merged**
