### PR TITLE
Fix https settings for own certs

### PR DESCRIPTION
**Pull request by vladimirmartsul**
Hi! If you want to use own https certificate for hmr with devServer you should pass cert & key in the devServer.https object not just root devServer object.

### CODE REVIEW

**Comment by chenxsan** [comment]
I believe it's [a change](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0) in `webpack-dev-server` v4 which is still in beta. The current documentation targets the latest released version, i.e., v3.

**Comment by vladimirmartsul** [comment]
> I believe it's [a change](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0) in `webpack-dev-server` v4 which is still in beta. The current documentation targets the latest released version, i.e., v3.

I see the same https object config one paragraph above at the https://webpack.js.org/configuration/dev-server/#devserverhttp2 so let the bring docs consistent?

**Comment by snitin315** [comment]
Lets allow and add a badge for beta version.

**Comment by chenxsan** [comment]
@vladimirmartsul That would make sense. I've tested against `webpack-dev-server` v3, the object version works as well:

image

**Review by chenxsan — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
