### PR TITLE
Documentation amended to be available in printable format

### PR DESCRIPTION
**Pull request by SetTrend**
#### Currently, it's not possible to create a decent printed (or PDF) version of the documentation:

1. Printed pages show all the navigation and interactive chrome, thereby unnecessarily wasting space.
1. Printing all of a chapter's pages to get a comprehensive lecture wastes a lot of space when each of a chapter's pages gets printed separately.

#### This commit fixes both issues:

1. New CSS rules have been added to remove navigation and interactive chrome when printing a documentation page.
1. A Node script has been added to concatenate a chapter's Markdown documents into a single page.

#### To do:

The webpack documentation team is suggested to add my new Node script to their build script and to
publish the generated concatenated content, converted to HTML, as additional Hyperlinks in the doc on their website (e.g. "→ Printable version").

### CODE REVIEW

**Comment by montogeek** [comment]
@SetTrend What problem did you have when building it?

**Comment by SetTrend** [comment]
@montogeek: Sorry, my mistake. I confused this project with another one I'm contributing to. The other project uses bash commands I cannot run. So, after running `npm run serve` I edited my pull request comment accordingly now.

**Comment by SetTrend** [comment]
I successfully ran `npm run chapterize` and `npm run build`.

The document pages look excellent when printed.

Still, I can't find the help files generated by `npm run chapterize` anywhere in the result. I was able, though, to convert the generated "_all.md" files manually to HTML and print them. So, the `chapterize` task runs flawlessly.

**Comment by SetTrend** [comment]
Hi @EugeneHlushko: What is the state of this pull request?

**Comment by EugeneHlushko** [comment]
Hi @SetTrend ,
I've updated your branch to be up-to-date with latest `master` and will try it locally, make sure to pull the changes. Thanks for reminding

**Comment by EugeneHlushko** [comment]
Meanwhile, can you give me permissions on your fork so i can contribute to the branch too?

**Comment by montogeek** [comment]
You should have, I can commit into forks

**Comment by EugeneHlushko** [comment]
oh, okay let me try

**Comment by EugeneHlushko** [comment]
I am struggling to build local/prod version on this branch, cannot see obvious reasons tho.

**Comment by SetTrend** [comment]
Unfortunately I cannot be of any help here. The build process now requires Python, which I don't have on my Windows machine.

I'm working on a new client project now, so, I don't think I'm able to go through the pain of installing and learning Python before being able to commit anything.

Would it help to cherry-pick my changes?

**Comment by EugeneHlushko** [comment]
Yeah its an option, not sure i can cherry pick cross fork

**Comment by montogeek** [comment]
This is now possible, thanks!

**Pull request closed without merging**
