### PR TITLE
Fixes #355, page titles

### LINKED ISSUE #355: Page title doesn't reflect page
The title is always "webpack", but should be the title of the page.

### PR DESCRIPTION
**Pull request by montogeek**
This PR fixes issue number #355
It is blocked by https://github.com/antwarjs/antwar/pull/116

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Cool! Could you lowercase webpack? It should always be written in lower case

**Comment by montogeek** [comment]
https://github.com/antwarjs/antwar/pull/116 was merged, thanks again @bebraw !

**Comment by montogeek** [comment]
Forgot to clarif: this fixes pages titles only when building the site, not in dev mode

**Comment by SpaceK33z** [comment]
Thanks!

**Pull request merged**
