### PR TITLE
Updating table spacing

### PR DESCRIPTION
**Pull request by rishantagarwal**
Currently, table spacing is not proper and needs to be scrolled to view whole content. I removed some extra space to make it completely visible.

### CODE REVIEW

**Comment by pierreneter** [comment]
No relation. Tabs will be removed during HTML rendering.

capture

**Comment by skipjack** [comment]
@rishantagarwal actually I think @pierreneter makes a good point. I'm not 100% sure your change actually makes a difference in the table... could you share some screenshots?

@pierreneter did you test this, are you sure it the spacing change doesn't make a difference? I approved as it doesn't seem like it'd hurt anything but I was wondering the same thing. I feel like whitespace is typically trimmed and the column's width is just determined by the longest trimmed cell.

**Comment by skipjack** [comment]
@rishantagarwal closing, but please feel free to re-open and share some screenshots if @pierreneter and I are mistaken.

**Comment by rishantagarwal** [comment]
@pierreneter @skipjack makes sense, my bad ! I am so sorry .

**Pull request closed without merging**
