### PR TITLE
doc/addSockPath cli

### PR DESCRIPTION
**Pull request by zhangyuang**
_describe your changes..._

add webpack-dev-server sockPath description, now it can be used by cli

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hi @zhangyuang 

When did this got available via the CLI?

**Comment by EugeneHlushko** [comment]
Looks like it is not yet released:
https://github.com/webpack/webpack-dev-server/pull/1804
https://github.com/webpack/webpack-dev-server/releases

**Comment by EugeneHlushko** [comment]
Can you ping us when its released @zhangyuang @evilebottnawi

**Comment by evilebottnawi** [comment]
Yes

**Comment by zhangyuang** [comment]
ok,it seems not yet released

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
