### PR TITLE
Added GitHub token for authenticated GitHub API calls

### PR DESCRIPTION
**Pull request by montogeek**
We are hitting GH Rate limit (60 request/hr) very quickly, this will increase it to 5000.

### CODE REVIEW

**Comment by jeremenichelli** [comment]
So the problem was that we were fetching even when no token was present? We'll still gonna fetch on Travis I guess, I don't know if this will actually solve our quota issue.

**Comment by montogeek** [comment]
No, we weren't using auth at all, this add authentication if the token exists (on Travis CI), a contributor won't have it locally, so I added a check before using it

**Comment by jeremenichelli** [comment]
Go for it!

**Comment by EugeneHlushko** [comment]
great addition!

**Pull request merged**
