### PR TITLE
chore: remove test, include, exclude from rule set conditions

### PR DESCRIPTION
**Pull request by anshumanv**
Remove additional rule set conditions.

Fixes https://github.com/webpack/webpack.js.org/issues/3625

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

Need confirmation - I should also remove all the instances where any of these are used in `modules: {rules: [{test: "...", ...}] }`. Found a bunch of instances across the project

### CODE REVIEW

**Comment by anshumanv** [comment]
@montogeek is this change alright? What do we do about several instances in the docs? 

> Need confirmation - I should also remove all the instances where any of these are used in modules: {rules: [{test: "...", ...}] }. Found a bunch of instances across the project

**Comment by montogeek** [comment]
Yes, please

**Comment by anshumanv** [comment]
Okay, will remove all the references in the next commit.

**Comment by EugeneHlushko** [comment]
@montogeek i am not clear on this, it says: "This is not related to Rule.test, Rule.include and Rule.exclude"

And we are removing it from the condition list on Rule which is shown in example below the list:

```
module.exports = {
  //...
  module: {
    rules: [
      {
        test: /\.css$/,
        include: [
          path.resolve(__dirname, 'app/styles'),
          path.resolve(__dirname, 'vendor/styles')
        ]
      }
    ]
  }
};
```

**Comment by anshumanv** [comment]
Seems unclear to me too, did you get any clarity on this @EugeneHlushko ?

**Comment by EugeneHlushko** [comment]
No not sure yet, @vankop can you help us document this change properly

**Comment by vankop** [comment]
This changes are correct, but I think we need to reword 
`Rule.resource`
`Rule.include`
`Rule.exclude`
`Rule.test`

Now `Rule.include`, `Rule.exclude, `Rule.test` are not a shortcuts since there is no `Rule.resource.<include|exclude|test>`, but they do the same =)

**Comment by EugeneHlushko** [comment]
@anshumanv willing to update this one according to https://github.com/webpack/webpack.js.org/pull/3641#issuecomment-623175731 ?

**Comment by anshumanv** [comment]
Yes I'll update @EugeneHlushko 👍

**Comment by anshumanv** [comment]
@vankop thanks for the help, does the previous restriction still stay which is mentioned on the docs?

>  If you supply a \`Rule.include\` option, you cannot also supply a \`Rule.resource\`.

**Comment by vankop** [comment]
> @vankop thanks for the help, does the previous restriction still stay which is mentioned on the docs?
> 
> > If you supply a `Rule.include` option, you cannot also supply a `Rule.resource`.

@anshumanv yes

**Comment by anshumanv** [comment]
Cool then, I think I'm done with the changes here. 

/cc @EugeneHlushko

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
