### PR TITLE
add support for browsers without native fetch

### LINKED ISSUE #410: [Vote] Poly/Ponyfill Fetch for Cross-Browser Supportability
Safari doesn't support `fetch`. We should probably poly/ponyfill it.

### PR DESCRIPTION
**Pull request by otbe**
Fixes #410

### CODE REVIEW

**Comment by TheLarkInn** [comment]
This looks good to me.

**Comment by SpaceK33z** [comment]
let me test it realll quick

**Comment by TheLarkInn** [comment]
No problem. Will wait before merge.

**Comment by SpaceK33z** [comment]
Thanks! Tested it & worked.

**Comment by TheLarkInn** [comment]
@otbe thank you!!!! Will probably deploy after a few more changes are made.

**Comment by otbe** [comment]
@TheLarkInn @SpaceK33z no problem. Glad to have helped :)

**Pull request merged**
