### PR TITLE
By default it uses 'main.js' instead bundle.js

### PR DESCRIPTION
**Pull request by MehdiRaash**
_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by Legends** [comment]
Can you elaborate on this PR a bit more? Why rename `bundle.js` to `main.js`?

**Comment by MehdiRaash** [comment]
Yeah sure, I just followed the instruction of that page(introduction), by default Webpack built main.js file however the doc is talking about build.js which is actually the main.js.

**Comment by Legends** [comment]
There is no `main.js` file...

**Comment by MehdiRaash** [comment]
I first did step by step through the docs in windows
image

after PR I also checked it out on Linux as well
image

Results were the same. there's no bundle.js via commands `npx webpack`

**Comment by montogeek** [comment]
Thanks!

**Comment by MehdiRaash** [comment]
Your welcome, but the thing is at that point after, docs is explaining about the `bundle.js` which all should changed to `main.js`.
 I was about to make a PR for it, but this wouldn't work because of the title and of although the rest of the page is talking about `bundle.js ` throughout introducing the config file.

**Comment by montogeek** [comment]
I will do it

**Pull request merged**
