### PR TITLE
update link: https://doc.webpack-china.org => https://webpack.docschina.org

### PR DESCRIPTION
**Pull request by dear-lizhihua**

### CODE REVIEW

**Comment by dear-lizhihua** [comment]
@skipjack 
Hi, there are many chinese documents in `docschina.org` now, like `Vue`, `React`, `Node.js`, `Babel`. Too many domain names are inconvenient to remember, so we use new domain `webpack.docschina.org`. @lcxfs1991

**Comment by dear-lizhihua** [comment]
@skipjack Is it possible to merge now?

**Comment by montogeek** [comment]
Thanks!

**Comment by dear-lizhihua** [comment]
@montogeek nice, thank you!

**Pull request merged**
