### PR TITLE
aliasFields is a string, not array

### PR DESCRIPTION
**Pull request by liamzebedee**
Fixed error in docs.

### CODE REVIEW

**Comment by montogeek** [comment]
It is an array: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L329
Why do you think it is a string?

**Comment by liamzebedee** [comment]
Hmm, I was erroring out on the latest version of webpack-cli (3.1.0) with this. Sorry if I'm incorrect. In either case, the docs still confuse the reader - it says type "string" above an example which is an array.

**Comment by montogeek** [comment]
Current webpack docs are for v4.x, please update the description to `array`.

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
