### PR TITLE
docs(contrib) remove simply, format note block

### PR DESCRIPTION
**Pull request by EugeneHlushko**
- remove "simply"
- format note block while at it

### CODE REVIEW

**Comment by montogeek** [comment]
What happened to the previews?

**Comment by EugeneHlushko** [comment]
@montogeek unfortunately they became billable, trying to get webpack to pay for them. There was a converstation in our slack

**Comment by montogeek** [comment]
@EugeneHlushko Yeah, I saw it but nothing happened...
Why billable? Netlify changed their plans?

**Comment by EugeneHlushko** [comment]
Yes, they decided that we should pay for preview builds if we build for more than 100 minutes. One build is approx 5 mins so its only 20 previews per month free for webpack.js.org

**Comment by montogeek** [comment]
:/

**Pull request merged**
