### PR TITLE
Update caching.md

### PR DESCRIPTION
**Pull request by aholzner**
destructures `CleanWebpackPlugin` from module import.

### CODE REVIEW

**Comment by montogeek** [comment]
Please change it everywhere, not only in this page.

**Comment by EugeneHlushko** [comment]
This is a breaking change on their side... Wonder whey they did plan to tell us about it. It went in 24 days ago...

**Comment by aholzner** [comment]
@montogeek I have replaced it in all affected pages. Please take another look.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
