### PR TITLE
Add CLI reference

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simon04** [comment]
Ahh, there's already an (possibly outdated) CLI doc: https://webpack.js.org/api/cli/ – *sigh*. However the search does not find this one, see #822. :confused:

**Comment by bebraw** [comment]
Yeah, better merge with the api doc (really hidden). Also moving the resulting doc below root level (needs a rewrite) would be a good move. Then we get "api, cli, configuration, ..." at navigation with a tiny amount of tweaking.

**Comment by bebraw** [comment]
What do you want to do with this? I would do `/cli` and make it visible in the navigation (easier to find). Push all CLI bits there and call it a day.

**Comment by simon04** [comment]
I'll open a separate PR to merge the new bits from this PR with the existing docs.

**Pull request closed without merging**
