### PR TITLE
fix(homepage): Fix a homepage animation bug.

### PR DESCRIPTION
**Pull request by zjffun**
Add a condition to the homepage animation.

Reproduction:
When you come back after leave the homepage for a long time , the cube will spin quickly and then become normal.

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
requestAnimationFrame is paused when tab is inactive, are you on older FireFox? @zjffun

**Comment by zjffun** [comment]
@EugeneHlushko 

This is indeed the case in the documentation. [window.requestAnimationFrame() - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

But it doesn't work fine in FireFox 66.0.3 (64 bit). Puzzled @_@

**Comment by EugeneHlushko** [comment]
Maybe worth checking firefox bug backlog, if not found open an issue. But i'd expect this to be known

**Comment by zjffun** [comment]
I print some log just now and find it really a bug of Firefox...

**Comment by zjffun** [comment]
Bug reported. [1548561 - requestAnimationFrame() can't paused when running in background tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1548561)

Close this

**Comment by zjffun** [comment]
@EugeneHlushko 

Err.. Should we using `document.hidden` condition temporary? Even though this animation doesn't make a big difference.

**Comment by EugeneHlushko** [comment]
its fine, edge case not directly related to reading docs. lets just let ff fix their bug instead. Thanks for looking into this anyway

**Comment by zjffun** [comment]
All right

**Pull request closed without merging**
