### PR TITLE
changed dist/index.htlm JavaScript ref

### PR DESCRIPTION
**Pull request by bjarki**
The rest of the tutorial expects the mail file to reference `bundle.js` not `main.js`

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
@bjarki pls update your branch for build to pass on Travis

**Comment by bjarki** [comment]
The build error:
> The job exceeded the maximum time limit for jobs, and has been terminated.

I only added a small amount of markdown to the documentation. Not sure of what I need to do to "fix" this. @EugeneHlushko can you point me in the right direction.

**Comment by EugeneHlushko** [comment]
All passes now, i see conflicting PR: #2050
CC @montogeek

**Comment by montogeek** [comment]
PR is not longer valid, all references use `main.js`.

**Pull request closed without merging**
