### PR TITLE
Documentation update for output path in Stats object

### PR DESCRIPTION
**Pull request by franjohn21**
Doc updates for https://github.com/webpack/webpack/pull/6405

### CODE REVIEW

**Comment by skipjack** [comment]
@franjohn21 thanks for the follow through, please ping us once the main pr is merged.

**Comment by franjohn21** [comment]
The pr is merged however the output path does not show up in the stats output to text string, only in JSON, so Im not sure it needs to be documented here

**Comment by skipjack** [comment]
Hmmmm, so maybe add it to the relevant location [here](https://webpack.js.org/api/stats/)?

**Comment by dhruvdutt** [comment]
The PR is merged. @franjohn21 please rebase.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
