### PR TITLE
Limit number of displayed sponsors and backers

### PR DESCRIPTION
**Pull request by sokra**
Donating seem to be abused for advertising. This PR limits the number of "latest" sponsors and limits the number of backers to 100 randomly chosen ones.

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Tested locally, all works as expected

**Comment by EugeneHlushko** [comment]
Thank you @sokra 👍

**Comment by sokra** [comment]
Thanks. It's much better now...

**Comment by EugeneHlushko** [comment]
Yeah, also page loads much faster :)

**Pull request merged**
