### PR TITLE
[FIX]Correct path value for webpack-dev-middleware

### PR DESCRIPTION
**Pull request by rahulbhooteshwar**
Current document is using path value configured for dist, but for webpack-dev-middleware it should be same as publicPath.

### CODE REVIEW

**Comment by rahulbhooteshwar** [comment]
Hi Maintainers,
I am unable to understand the reason of travis-ci build failure for this PR. It reports lint:social failed but while executing it on my local machine lint:social is having no issues.

**Comment by montogeek** [comment]
@andrewonaboat

**Comment by shellscape** [comment]
@montogeek I've never seen a need for that before. (not to mention that's not the right place in the code for that change, stylistically)

**Comment by montogeek** [comment]
@rahulbhooteshwar Please provide a repository to show why your code doesn't work without your change.

**Comment by rahulbhooteshwar** [comment]
@montogeek [Here](https://github.com/rahulbhooteshwar/learn-webpack) is the repository to show the problem I am facing without the change:
[learn-webpack](https://github.com/rahulbhooteshwar/learn-webpack)

**Comment by elliottsj** [comment]
@rahulbhooteshwar I tried `npm run server` in your repo, and localhost:3000 loads fine for me.

**Comment by montogeek** [comment]
@rahulbhooteshwar Friendly ping

**Pull request closed without merging**
