### PR TITLE
Add Glossary Page

### PR DESCRIPTION
**Pull request by rouzbeh84**
Still a WIP...

Building out base for glossary per #970. Definitely needs more items so help would be much appreciated in checking/adding glossary items 👍

### CODE REVIEW

**Comment by rouzbeh84** [comment]
@bebraw would it make sense to port over most of the SurviveJS book glossary terms in here as the 'starting point'?

**Comment by skipjack** [comment]
@rouzbeh84 just did one pass to clean up grammar and make the formatting more consistent. Please review, and let me know if you think any of the changes I made don't make sense. I think __Bundle Splitting__ can probably be dropped or just point from there to the __Code Splitting__ definition to prevent any confusion (plus I haven't seen the term _bundle splitting_ used much).

@webpack/core-team @webpack/documentation-team any other thoughts for common terms and definitions that should be added here? I think this is a pretty good start but we could probably sneak a few more in before merging.

**Comment by bebraw** [comment]
> @bebraw would it make sense to port over most of the SurviveJS book glossary terms in here as the 'starting point'?

@rouzbeh84 You can expand/rewrite as needed. I wouldn't copy them verbatim (different writing style etc.).

**Comment by bebraw** [comment]
Can you rebase against master? There's something funky going on with the commits.

**Comment by rouzbeh84** [comment]
@bebraw i dropped the duplicate commit that somehow got wrangled in...

**Comment by skipjack** [comment]
@rouzbeh84 have you come up with any others yet or are there ones from SurviveJS you plan to port? I'm thinking we leave this open for the rest of this week then try to ship it this weekend. I'll give some thought as to where to add the link to it and add that in soon.

**Comment by rouzbeh84** [comment]
I figure I'll start by going through the [intro](https://webpack.js.org/concepts/) section and adding words that further warrant explanation or will be referenced frequently throughout the docs as I can. I think the high level items are on there for the most part but will dig in each section and see what I can pull out for the glossary.

Also, I would love any help I can get! My explanations are sometimes good and sometimes not so great but I have a busy week this week with a few out of work events as well as work.

**Comment by skipjack** [comment]
Closing in favor of #1242...

**Pull request closed without merging**
