### PR TITLE
docs(concepts): Update plugins.md

### PR DESCRIPTION
**Pull request by arjendeblok**
Made sample code for plugin working for webpack 4.
Also changed to ES2015.

### CODE REVIEW

**Comment by montogeek** [comment]
Could you please add a note regarding that the plugin name should be a camelized version of the name

**Comment by arjendeblok** [comment]
@montogeek Do you mean the name of the class or the string constant. Both are camilized in the example.

**Comment by montogeek** [comment]
Plugin name, something like:
'First parameter of the tap method (or hook?) should be a camelized version of the plugin name'

**Comment by TheDutchCoder** [comment]
Before I merge this in @jeremenichelli should this be PR'ed against the `next` branch instead?

**Comment by jeremenichelli** [comment]
Yes @TheDutchCoder

**Pull request merged**
