### PR TITLE
Notice about stats config

### PR DESCRIPTION
**Pull request by danez**
The stats config does not have any effect in the Node.JS API

I added a warning on configuration/stats
And also mentioned it on the Node.JS API page

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Hmm, it's not entirely correct that the `stats` options don't have any effect. It is correct that using e.g. `stats: { chunks: false }` in your **webpack config** has no effect, but the `stats` options are still relevant if you want to display stats, e.g. like this:

```js
compiler.watch({...}, function(err, stats) {
    console.log(stats.toString({ chunks: false }));
});
```

**Comment by danez** [comment]
Yeah true. What I actually meant is that if this options is supplied to the webpack constructor, it won't print anything and calling `stats.to{String/Json}` won't respect these.

**Comment by bebraw** [comment]
Can you rebase against `master`? The development happens against it now (faster deployments).

**Comment by bebraw** [comment]
Thanks.

**Pull request merged**
