### PR TITLE
fix(safari) polyfill IntersectionObserver for safari

### LINKED ISSUE #2977: Website doesn't work at all - Just shows blank white page
FYI I see a completely blank white page when visiting https://webpack.js.org

The console shows the following output:
```
[Info] Content blocker prevented frame displaying https://webpack.js.org/ from loading a resource from https://www.google-analytics.com/analytics.js (index.bundle.js, line 37)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver — index.bundle.js:6:7503
	pr (index.bundle.js:22:75233)
	callback (index.bundle.js:22:80280)
	or (index.bundle.js:22:73069)
	ir (index.bundle.js:22:72817)
	zr (index.bundle.js:22:82988)
	Kr (index.bundle.js:22:85305)
	(anonymous function) (index.bundle.js:22:98512)
	unstable_runWithPriority (index.bundle.js:31:3196)
	Fl (index.bundle.js:22:98469)
	Nl (index.bundle.js:22:98223)
	xl (index.bundle.js:22:97568)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] ReferenceError: Can't find variable: IntersectionObserver
	xl (index.bundle.js:22:97773)
	Tl (index.bundle.js:22:96589)
	Qr (index.bundle.js:22:95463)
	Hl (index.bundle.js:22:99478)
	render (index.bundle.js:22:103323)
	(anonymous function) (index.bundle.js:22:101182)
	Vl (index.bundle.js:22:101111)
	(anonymous function) (index.bundle.js:37:987214)
	o (index.bundle.js:1:323)
	(anonymous function) (index.bundle.js:1:1973)
	Global Code (index.bundle.js:1:1983)
[Error] TypeError: null is not an object (evaluating 'i.content.clientHeight')
	_calculateContentHeight (index.bundle.js:37:961375)
	(anonymous function) (index.bundle.js:37:962695)
```

Using Safari Version 12.0.2 (14606.3.4)

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Fixes #2977

### CODE REVIEW

**Comment by montogeek** [comment]
You see, this is one of those things that I would change about the Web, now we are adding more code just for the sake of a newish API, your very first solution was just fine because it worked even in very old browsers, no need to add more code, more polyfills, etc.

What you think about use it? So we can save some bytes here.

**Comment by EugeneHlushko** [comment]
Do you mean the component from 1st commit here? https://github.com/webpack/webpack.js.org/pull/2956/commits/8ba8d6af3a6353fb55e48074fd66691fb32b1f5f

Yeah i can move it to a package under my git and use that component instead, would take us back to hundred bytes solution

**Comment by EugeneHlushko** [comment]
Or do you mean react-visibility-sensor package?

**Comment by EugeneHlushko** [comment]
I dont like how they didnt do an if check for `IntersecionObserver` in window... so lame to force everyone into a poly

**Comment by montogeek** [comment]
Yes, this one https://github.com/joshwnj/react-visibility-sensor/blob/master/lib/is-visible-with-offset.js, good old offsets.

It is in the docs: https://www.npmjs.com/package/react-intersection-observer#installation

**Comment by EugeneHlushko** [comment]
makes sense to me

**Comment by EugeneHlushko** [comment]
its funny i contributed to that package back in 2015-ish

**Comment by EugeneHlushko** [comment]
its up @montogeek

**Comment by montogeek** [comment]
Thank you!

**Pull request merged**
