### PR TITLE
Update hmr-react.md: Remove erroneous "/" in code snippet.

### PR DESCRIPTION
**Pull request by joshsantos**
Remove erroneous "/" in code snippet under Project Config.

### CODE REVIEW

**Comment by joshsantos** [comment]
@skipjack

Do you mean?
```
npm install --save-dev webpack webpack-dev-server
npm install --save-dev babel-core babel-loader babel-preset-es2015 babel-preset-react
npm install --save-dev style-loader css-loader postcss-loader
```
This is more readable but also more tedious to copy, paste, and run.

Or...
```
npm install --save-dev webpack webpack-dev-server
  babel-core babel-loader babel-preset-es2015 babel-preset-react
  style-loader css-loader postcss-loader
```
This is more readable but breaks the ability to copy, paste, and run as terminal doesn't like line breaks.

Let me know which one you prefer and I can make the change. Thanks.

**Comment by skipjack** [comment]
I meant the first one, and you're right it is a bit more tedious but I think it's more important for people to understand exactly what's happening, rather than just copy and pasting blobs of code.

**Comment by joshsantos** [comment]
Yep, for sure. Change committed - ready for review. Thanks @skipjack

**Comment by skipjack** [comment]
@joshsantos thank you sir! Plenty of other content related issues if you're interested in contributing any more 😉 !

**Pull request merged**
