### PR TITLE
Docs: fix typos

### PR DESCRIPTION
**Pull request by madhavarshney**
Fix a few typos, found by [github-spellcheck-cli](https://github.com/tbroadley/github-spellcheck-cli).

### CODE REVIEW

**Comment by byzyk** [comment]
Very interesting. Shall we consider adding something like that to our testing pipeline?

**Comment by montogeek** [comment]
@byzyk Yes

**Comment by madhavarshney** [comment]
@byzyk - I actually did have that in mind.  You can add [spellcheck-cli](https://github.com/tbroadley/spellchecker-cli) to your testing pipeline.  It will just require you to maintain a dictionary of the words that should be white listed, including all the GitHub usernames in the contributors section of the docs. (Amazing work by @tbroadley! 😄)

**Comment by tbroadley** [comment]
👋 Thanks @madhavarshney! If you're interested in using `spellcheck-cli`, I'd be happy to work on setting it up for this repo.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
