### PR TITLE
Improve display on mobile device

### PR DESCRIPTION
**Pull request by blade254353074**

### CODE REVIEW

**Comment by blade254353074** [comment]
image

image

**Comment by blade254353074** [comment]
image

image

**Comment by blade254353074** [comment]
@skipjack Thank you~
It was my fault...
I just use Chrome to test the vertical style.
Not notice the icon element is absolute.
Now I have added a top prop to make it vertical middle.

**Comment by skipjack** [comment]
@blade254353074 ok thanks I'll test this again soon. Can you take a look at my review comment, I'm trying to figure out what that `p { ... }` declaration is intended to fix.

**Comment by blade254353074** [comment]
That's the problem.

**Comment by skipjack** [comment]
Merged, thanks @blade254353074!

**Comment by blade254353074** [comment]
You are welcome~

**Pull request merged**
