### PR TITLE
fix: loader overridden explanation

### PR DESCRIPTION
**Pull request by liximomo**

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
@liximomo what is the reason of this change. e.g. pull request or issue link for context? previous version was reviewed by Tobias recently

**Comment by liximomo** [comment]
@EugeneHlushko 
image These two things can't match.

**Comment by EugeneHlushko** [comment]
In that case you are fixing it in the wrong place. Change the code comment instead?

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
