### PR TITLE
docs(plugins): revise DefinePlugin

### PR DESCRIPTION
**Pull request by chenxsan**
Closes https://github.com/webpack/webpack.js.org/issues/5087

### CODE REVIEW

**Comment by chenxsan** [comment]
cc @matthias-ccri Do you think the revised version is appropriate?

**Comment by matthias-ccri** [comment]
Hi @chenxsan thanks for doing this! I see the phrase "arbitrary code" which at least to me is very similar to "arbitrary code execution", which is a bad thing in the area of software vulnerabilities. That's just my perspective, but it might be good for the docs to say "values or expressions" instead of "arbitrary code".

```markdown
The `DefinePlugin` allows you to replace variables in your code with other values or expressions at **compile** time.
```

I see the previous effort to emphasize "at compile time", which I missed previously, but it reads like "this plugin does stuff at compile time" which is true for everything webpack, since webpack is a compiler. It can be removed:

```markdown
The `DefinePlugin` allows you to replace variables in your code with other values or expressions.
```

And it could be even more direct:

```markdown
The `DefinePlugin` replaces variables in your code with other values or expressions.
```

**Comment by chenxsan** [comment]
@matthias-ccri Actually webpack does have runtime code running in the browser, and I believe plugins can contribute to that as well.

What about:

```
The `DefinePlugin` replaces variables in your code with other values or expressions at **compile** time.
```

**Comment by matthias-ccri** [comment]
That looks good to me!

**Comment by chenxsan** [comment]
@matthias-ccri Thank you, I'm grateful for your help.

**Pull request merged**
