### PR TITLE
correct a path error in example

### PR DESCRIPTION
**Pull request by bingtimren**
in the example, webpack outputs to dist/bundle.js so index.html should use the same path

### CODE REVIEW

**Comment by montogeek** [comment]
Thanks for your contribution, Could you please change base branch to `next`? It is been used for the next version of webpack

**Comment by bingtimren** [comment]
Done. Base changed to next.

**Comment by bingtimren** [comment]
Done that too. Thanks.

**Comment by dhruvdutt** [comment]
@bingtimren It's still present. Check the [diff](https://github.com/webpack/webpack.js.org/pull/1899/files).

**Comment by bingtimren** [comment]
Ok committed to the patch-1 branch. This time did it right?

**Comment by dhruvdutt** [comment]
Looks good to me.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
