### PR TITLE
infra(site) Fix project run on Windows

### LINKED ISSUE #2380: Rebuild doesn't work
@Legends Following your comment https://github.com/webpack/webpack.js.org/pull/2039#issuecomment-406821825,
Could you please post content of your `./_content.json` file?

### PR DESCRIPTION
**Pull request by montogeek**
Fixes #2380

### CODE REVIEW

**Comment by montogeek** [comment]
@Legends Please let me know if this branch works for you.

I have a Windows machine, solved this issue on it and it worked, hope if works for you.

**Comment by Legends** [comment]
Yep works. Thanks!

Just another thing I noticed:
image

Why use hash routes in newer browsers?

**Comment by montogeek** [comment]
What you mean? It is an anchor.

**Comment by Legends** [comment]
Is it possible in `react` to  make it look like `http://localhost:3000/concepts/loader/cli`, without `#` ?

**Comment by montogeek** [comment]
No, that is another URL, we need anchors for each title (heading (h1, h2, h3)) in the docs.

**Comment by montogeek** [comment]
Glad it worked for you.

**Comment by Legends** [comment]
Thanks for taking care of windows users too ;-)

**Comment by montogeek** [comment]
No problem, thanks for detecting this before making it our stable solution, more potential contributors!

**Pull request merged**
