### PR TITLE
Add Support page

### PR DESCRIPTION
**Pull request by scottdj92**
Adding content based on #836

### CODE REVIEW

**Comment by bebraw** [comment]
Looks like proselint caught you:

* content/support/index.md:7:1: cliches.garner 'First and foremost,' is cliché.

**Comment by scottdj92** [comment]
I'm running into an issue testing proselint on my machine after running `yarn install`.

I did fix the error though, I'll make a commit.

**Comment by bebraw** [comment]
Yeah. proselint has to be installed through `pip` as it's a Python tool. `pip proselint` if I remember right.

**Comment by scottdj92** [comment]
The only issue I have with this PR is that it could potentially attract us a lot of contributions, so I'd like to have a more fleshed out content section mainly removing the `(add more slides here)` before merging this PR.

**Comment by bebraw** [comment]
Yup. Cut the slide bit. Good to go after that.

**Pull request merged**
