### PR TITLE
use github actions

### PR DESCRIPTION
**Pull request by chenxsan**
Travis provides 5 concurrent builds for open source builds, and it's sort of limited for a project like webpack documentation. This pull request https://github.com/webpack/webpack.js.org/pull/4032 was postponed for many minutes as there're other jobs running, and it's a waste of time. I'm wondering if github actions can improve the situation.

### CODE REVIEW

**Comment by jeffin143** [comment]
azure has good build prospects too, I guess we could try that too

**Comment by montogeek** [comment]
It is there a comparison between all 3 (or some more)? I know Actions will only give us 2000 minutes per month, right now in Travis (completely infrastructure) it takes 10 mins, so we will get 200 jobs per month, give or take. It is this better than Travis?

**Comment by chenxsan** [comment]
@montogeek Thanks for the information, I just took it for granted that github provides open source projects unlimited time as it mentioned `free` in its page:

image

I'll do more research later.

**Comment by chenxsan** [comment]
CI runs much faster now (before: ~16min, after: ~8min) after this pull request https://github.com/webpack/webpack.js.org/pull/4033, it's acceptable in my opinion, so I'll close this PR.

**Comment by chenxsan** [comment]
@montogeek FYI, I've written an email to github for clarifying and here's their answer:

image

**Comment by evilebottnawi** [comment]
I think in long term will be great to migration on github actions (a lot of features)

**Comment by chenxsan** [comment]
Maybe we can enable github actions along with travis for a while to see how one compared to another. When we collect enough data we can make a final decision which to use.

**Comment by evilebottnawi** [comment]
Good ide

**Comment by montogeek** [comment]
I will prefer GitHub actions just because everything will be here :)

**Comment by chenxsan** [comment]
With cache enabled, the `Lint` job can run in 1m https://github.com/chenxsan/webpack.js.org/actions/runs/300387454:

image

I think it's quite promising compared to travis:

image

**Comment by chenxsan** [comment]
Unfortunately the `Proselint` job on github actions runs much slower than travis:

image

image

**Comment by chenxsan** [comment]
Seems github actions can run multiple jobs simultaneously which bring a faster result than travis even though the `Proselint` job runs slower than travis.

**Comment by chenxsan** [comment]
Since I can't test the deploy job, I've include an empty `deploy-github.sh` for testing.

**Comment by chenxsan** [comment]
With the new pricing model introduced recently in travis https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, the time spent running CI is [much longer](https://twitter.com/geerlingguy/status/1324480667984498689) than before now. Thus I'm going to merge this PR once the CI pass so we can monitor the performance of Github Actions along with travis.

**Comment by chenxsan** [comment]
30 minutes, and it's not done yet.

image

**Pull request merged**
