### PR TITLE
Advertisement

### LINKED ISSUE #1033: Add Left Partner Banner for ag-Grid
* We need to have the attached asset added to the left gutter of the docs page (for desktop). We don't have any plans for mobile yet that provides as eloquent, and so for now we've agreed to not disrupt the delivery of content with the banner on mobile devices. 
* The banner needs to link to https://www.ag-grid.com/?utm_source=webpack&utm_medium=banner&utm_campaign=sponsorship

banner_ad_vertical 1

@skipjack Pinging you and adding as requested. We are shooting for Monday on this, so if for any reason you don't think you can get to this, that is fine, let me know, and I'll finish any work required for it.

### PR DESCRIPTION
**Pull request by skipjack**
Adding the sponsor banner requested by @TheLarkInn.

Additions:

- Adds a new space for advertisements in the left gutter on larger screens
- Hardcoded the ag-grid advertisement into the `Advertisement` component (however we should be able to make this scale to dynamically pulling advertisements fairly easily if needed)
- This new section is responsive and sticky in a very similar manner to the sidebar

The only thing left we might need to do is add a media query to hide the banner on screens smaller than around 1600-1550px to prevent the banner from getting cut off. See gif below for a demo...

Resolves #1033 

@TheLarkInn I did tweak the design slightly, I think the light background looks a bit cleaner. It's displayed on all pages except for the home page (there's not really any good place to put it there).

### CODE REVIEW

**Comment by TheLarkInn** [comment]
This looks incredible. I'm going to mark as approved. @bebraw should we try and address avoiding ad blockers from affecting that image.

**Comment by bebraw** [comment]
Step one: name the class as something else than `advertisement`. 👍

**Comment by skipjack** [comment]
Hahaha definitely a good idea, I'll rename this sponsors or sponsor-bar or something.

**Comment by skipjack** [comment]
@TheLarkInn @bebraw renamed the component/class.

**Comment by TheLarkInn** [comment]
@skipjack @bebraw Go ahead and merge now.

**Comment by skipjack** [comment]
@TheLarkInn re-running the build, not sure what those errors were about. Most just looked like network flakiness.

**Comment by bebraw** [comment]
Yeah, sometimes some badge provides goes down. Our system is a bit too strict with those (probably should be filtered out).

**Pull request merged**
