### PR TITLE
Fixed Link Conversion Error

### LINKED ISSUE #4055: [Bug] Link Conversion Error
image

I found a link exception and fixed it, when updating the Chinese document.

@EugeneHlushko 

Fixed #4054

### PR DESCRIPTION
**Pull request by QC-L**
Fixed #4055

### CODE REVIEW

**Comment by chenxsan** [comment]
Maybe we can include a unit test for `process-readme.js`.

**Comment by QC-L** [comment]
I agree. I'll try to write it.

**Comment by QC-L** [comment]
Done!

**Comment by montogeek** [comment]
Thank you @QC-L, please check lint errors :)

**Comment by QC-L** [comment]
@montogeek Done!

**Review by montogeek — APPROVED** [review]

**Review by chenxsan — APPROVED** [review]

**Pull request merged**
