### PR TITLE
Update/Fix Get-Started with ES6 standard import

### PR DESCRIPTION
**Pull request by Sieabah**
Changed 
```javascript
import _ from 'lodash';
```
to
```javascript
import * as _ from 'lodash';
```

### CODE REVIEW

**Comment by asapach** [comment]
It should work both ways: https://github.com/lodash/lodash/blob/4.17.2-es/lodash.js. Why change it?

**Comment by Sieabah** [comment]
@asapach It _should_ but for some reason doesn't when you follow the guide. My guess is it's trying to find '_' in the package to import.

**Comment by bebraw** [comment]
@Sieabah That sounds like a webpack bug esp. if it works through Babel. Any thoughts on the import issue @sokra?

**Comment by bebraw** [comment]
Can you rebase against `master`? The development happens against it now (faster deployments).

**Comment by bebraw** [comment]
@Sieabah I've changed the PR to be applied against master. I think you need to do something like this:

```bash
git rebase master
git push --force
```

It is possible you may have to pull the latest master.

**Comment by bebraw** [comment]
Ah, it's looking pretty good already. You could squash the commits, but apart from that it's fine.

**Comment by bebraw** [comment]
`import _ from 'lodash';` works for me against the current RC. Can you verify?

**Comment by bebraw** [comment]
Given `import _ from 'lodash';` should work, I'm going to close this one. Note that with lodash, the recommended way seems to be `import { omit } from 'lodash';`. There are also specific plugins that can help with it etc.

**Pull request closed without merging**
