### PR TITLE
docs(links) update the links to have trailing slash in order for anch…

### PR DESCRIPTION
**Pull request by EugeneHlushko**
…ors to work consistently

follow up to #3318 

P.S. @Munter is it possible to add that check to linkcheck? e.g. all internal links that have anchor but dont start with `#` ( e.g. same page anchor links ) would have to have trailing slash i.e. a `/#` combination

### CODE REVIEW

**Comment by Munter** [comment]
That's an interesting case. @papandreou is this actually a bug in the way assetgraph resolves index html files from directories? Or is it one of those nasty things where it depends on the server configuration?

**Comment by papandreou** [comment]
Hmm, so the issue is that `/configuration/configuration-types#exporting-a-function` gets redirected to `/configuration/configuration-types/`, losing the fragment identifier, and that hyperlink doesn't point that out?

I think assetgraph's modelling of this is correct. When a href of `/configuration/configuration-types` is encountered during population, and `stat` says that `configuration-types` is a directory, it will add a `FileRedirect` relation to the graph, which assumes that there's an `index.html` inside. That's a de facto standard for static web sites that also holds here, and the webpack.js.org server is also set up to correctly redirect, adding the slash to the url.

We should probably update hyperlink itself to complain when a link with a fragment but without a trailing slash points at an asset that gets redirected (has an outgoing `FileRedirect` or `HttpRedirect`). I can take a look at that.

Actually, I think I had convinced myself that browsers carried over the fragment when following a redirect, but maybe that changed, or I was imagining things :)

**Comment by montogeek** [comment]
Why is this needed now? or was is always broken?

**Comment by EugeneHlushko** [comment]
Not sure @montogeek 
I am sure it was working some time ago, but recently it stopped scrolling to an anchor at certain scenario (follow internal link vs full page load when paste url to the browser)

@papandreou thanks for filing a PR so quick :)

**Pull request merged**
