### PR TITLE
Improved spacing and color scheme of search

### PR DESCRIPTION
**Pull request by pastelsky**
In continuation with #285, here are some improvements for how search looks.

search

### CODE REVIEW

**Comment by SpaceK33z** [comment]
I just merged #374, which seems to have a few conflicting changes.

**Comment by pastelsky** [comment]
@SpaceK33z  I've rebased with the latest `develop` branch. What happened to the search button?

**Comment by skipjack** [comment]
@pastelsky gone? you might have to run an npm install to pick up the new loaders...

**Comment by skipjack** [comment]
LGTM 👍

**Pull request merged**
