### PR TITLE
Content/entry

### PR DESCRIPTION
**Pull request by saurick**
“Do not create a entry for vendors or other stuff which is not the starting point of execution.”
not "a",but "an".

### CODE REVIEW

**Comment by montogeek** [comment]
Sokra never created a PR?

**Comment by dhruvdutt** [comment]
cc @sokra, in case he was planning to add something before doing the PR.

**Comment by sokra** [comment]
Wasn't this already merged as #2525?

**Comment by montogeek** [comment]
Yes, it was merged. Not really sure what happened.

**Comment by montogeek** [comment]
It was missing a sync with master. Closing as duplicate.

**Pull request closed without merging**
