### PR TITLE
docs(plugins): update EnvironmentPlugin warning

### PR DESCRIPTION
**Pull request by snitin315**
Fix https://github.com/webpack/webpack.js.org/issues/7448

### CODE REVIEW

**Comment by fasiha** [comment]
I was hoping that this PR would include a note about the issue raised in https://github.com/webpack/webpack.js.org/issues/7448 where, if you use `process.env.SOMETHING` and that EnvironmentPlugin doesn't know about it, Webpack will happily ignore `process.env.SOMETHING` and include it in the output.

**Comment by snitin315** [comment]
>`EnvironmentPlugin` checks `process.env` for the specified variable. 

@fasiha This is mentioned in the warning EnvironmentPlugin checks only for the variables specified within this plugin. Otherwise, no errors.

**Comment by fasiha** [comment]
@snitin315 thanks for the note! Do you mean this warning?:

> W> `EnvironmentPlugin` checks `process.env` for the specified variable. If it’s missing, it searches for a default value provided in the configuration. If neither the environment variable nor the default value is defined, an error will be thrown: **"`EnvironmentPlugin` - `${key}` environment variable is `undefined`"**.

Re-reading this, I don't think it makes clear that the plugin ignores usages of `process.env` that it doesn't know about? So perhaps we could add a line to this paragraph, something like what you said:

> `EnvironmentPlugin` checks only for variables specified by this plugin. Using `process.env` with unspecified variables results in those usages being ignored: for example, `process.env.UNKNOWN` will be left intact.

**Comment by snitin315** [comment]
@fasiha sure, feel free to send a PR

**Pull request merged**
