### PR TITLE
Add link to react-markdown loader list

### PR DESCRIPTION
**Pull request by fernandopasik**

### CODE REVIEW

**Comment by fernandopasik** [comment]
We developed for use only in webpack, it doesn't work as standalone.

**Comment by skipjack** [comment]
Is it a loader itself though, or just used in conjunction with the `json-loader`? Just to clarify, I'm not saying we can't include it somewhere in the documentation -- we love to promote useful tools in the webpack ecosystem -- I'm just not sure the loaders page is best.

**Comment by fernandopasik** [comment]
Thanks for your help @skipjack! It is a loader itself, it's not used in conjunction with any other loader.
It's used with markdown files, all the content gets into a react component, and as a bonus if there is a react code block it gets also executed. It's ideal for building styleguides. That is why we added it in the previous webpack site in the templating loaders list.

**Comment by skipjack** [comment]
Ah I see, I was looking at the [wrong package](https://github.com/rexxars/react-markdown)!

**Comment by fernandopasik** [comment]
Thank you @skipjack !!

**Pull request merged**
