### PR TITLE
Update dev-server.md typo

### PR DESCRIPTION
**Pull request by phlco**
Switches "it's" for "its".

### CODE REVIEW

**Comment by bebraw** [comment]
Can you sign the CLA? Thanks.

**Comment by simon04** [comment]
@phlco: Don't forget to sign the CLA.

**Comment by simon04** [comment]
@phlco, ping!

**Comment by bebraw** [comment]
@simon04 Maybe it's easier to redo this PR and close this one? I'm not sure what's the correct way to deal with cases like this. Trivial fix.

**Comment by simon04** [comment]
Let's give him/her one more chance to get his/her first PR accepted? I agree that it would be easier to redo the fix. :smile:

**Comment by bebraw** [comment]
@simon04 Ok. Maybe we can agree on some period (a week?) for cases like this.

**Comment by phlco** [comment]
@simon04 @bebraw sorry I missed this! 🤕

**Comment by bebraw** [comment]
@phlco No worries. 👍

**Pull request closed without merging**
