### PR TITLE
optimize diff highlighting

### PR DESCRIPTION
**Pull request by chenxsan**
closes https://github.com/webpack/webpack.js.org/issues/3578

<del>Currently the dependency uses github branch of my forked repository, I'll update it after https://github.com/montogeek/remark-refractor/pull/1 is merged.</del>

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
This still has an issue, you select less spaces than you should where such characters had select disabled

**Comment by chenxsan** [comment]
@EugeneHlushko Indeed. But missing whitespace or indent doesn't break program in JavaScript. With tools like prettier, code without `+` `-` could be formatted while impossible if we have `+` `-` presented.

@SimonSiefke What do you think here? Do you mind the missing spaces?

**Comment by SimonSiefke** [comment]
Since I use prettier, I don't mind the spaces :)

**Comment by chenxsan** [comment]
I'll update the dependency when a new version of `remark-refractor` is published on npm.

**Review by EugeneHlushko — APPROVED** [review]

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
