### PR TITLE
docs: capitalize DOCTYPE

### PR DESCRIPTION
**Pull request by snitin315**
_describe your changes..._

P.S. the declaration is not case sensitive both are correct, but it's good to have a more standard (`<!DOCTYPE html>`)Declaration for official documentation. 

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by montogeek** [comment]
Thanks for your contribution, but this is not necessary.

**Comment by anshumanv** [comment]
> but it's good to have a more standard

Failing to understand how it is more standard? Are there any references?

**Comment by snitin315** [comment]
> Failing to understand how it is more standard? Are there any references? 

Sorry, I meant ~~standard~~ conventional. Wrong choice of words. My bad :-)

Like you can see `DOCTYPE`  mostly in a google search of `doctype`

**Comment by evilebottnawi** [comment]
It is more spam than real fix, no need it, better integrate prettier and forgot about it

**Comment by snitin315** [comment]
yes, you're right, I will integrate prettier if everyone agrees.

**Pull request closed without merging**
