### PR TITLE
Fix typos across webpack.js.org repo

### PR DESCRIPTION
**Pull request by yohix**
:writing_hand: **Fix typos across webpack.js.org repo**

**Files that have typos**

```
webpack.js.org/src/content/configuration/dev-server.md:778:20: "supress" is a misspelling of "suppress"
webpack.js.org/src/content/configuration/index.mdx:284:9: "properites" is a misspelling of "properties"
webpack.js.org/src/utilities/process-readme.js:40:23: "documenation" is a misspelling of "documentation"
```

**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos :heart: 

Making the world a better place :innocent:

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
Please sign the CLA.

**Comment by yohix** [comment]
@jamesgeorge007 **FYI:** I already signed!

Screenshot

**Comment by jamesgeorge007** [comment]
Try closing and reopening this PR.

**Comment by yohix** [comment]
Thanks, @jamesgeorge007 it worked! :heart:

**Comment by montogeek** [comment]
Is this all the typos that exist?

**Comment by yohix** [comment]
@montogeek I think yes, just fixed all the typos showed by the tool!

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
