### PR TITLE
Feat: Searchpage for webpack scaffold

### PR DESCRIPTION
**Pull request by evenstensberg**
Adds search page on discovering scaffolds made by webpack.

Ref #2718

Aligned to next branch

### CODE REVIEW

**Comment by evenstensberg** [comment]
@EugeneHlushko against master or next?

**Comment by EugeneHlushko** [comment]
Preview wont work until we update next branch and rebase this one. @evenstensberg i would like to do small refactor on jsx here, instead of leaving many suggestions if you are not planning on adding any more commits.

**Comment by evenstensberg** [comment]
@EugeneHlushko nope, I'm all done. Do you mind taking over the responsibility for this PR if so? I'll help you get it landed by what I can help out with. Thanks! 🥰

**Comment by EugeneHlushko** [comment]
JFY: this is blocked in until `next` is updated with `master` and this branch updated with latest next.

**Comment by evenstensberg** [comment]
Gotcha

**Pull request closed without merging**
