### PR TITLE
Add Korean translation site to dropdown list

### PR DESCRIPTION
**Pull request by YukJiSoo**
- Add [Korean translation site](https://webpack.kr/) to the dropdown list
  
Preview: 
image

### CODE REVIEW

**Comment by chenxsan** [comment]
Can you share the repository of the source code for the translation? For example, here's the Chinese version https://github.com/docschina/webpack.js.org

**Comment by YukJiSoo** [comment]
@chenxsan 
The Korean translation site is currently operated as a private repository.
Can't I merge this PR without sharing a repository?

**Comment by YukJiSoo** [comment]
@chenxsan 
We have created a public repository. 
Please check here. https://github.com/line/webpack.kr

**Comment by chenxsan** [comment]
@YukJiSoo Can you please sign up the CLA https://cla.js.foundation/webpack/webpack.js.org?pullRequest=4987?

**Comment by YukJiSoo** [comment]
@chenxsan I have a few questions.
1. I wonder why we sign up to the CLA.
2. Is it okay if only one person signs up?

**Comment by YukJiSoo** [comment]
@chenxsan 
I signed up. Please confirm.

**Review by chenxsan — APPROVED** [review]

**Pull request merged**
