### PR TITLE
Docs(migration): Add info about webpack.util.serialization

### PR DESCRIPTION
**Pull request by jeffin143**
fix : #2741

### CODE REVIEW

**Comment by montogeek** [comment]
It is still exposed in webpack 5?

**Comment by jeffin143** [comment]
> It is still exposed in webpack 5?

yes I suppose, because the change still persist.

Can you confirm @sokra ?

**Comment by sokra** [comment]
Yes this is exposed, but I don't think it make sense to mention in the migration guide. That's something for the changelog...

**Comment by jeffin143** [comment]
Since this is not needed anymore, let's close this

**Pull request closed without merging**
