### PR TITLE
Mobile friendly tables

### LINKED ISSUE #246: Fix Table Styling (esp. on mobile)
As mentioned in #244, we need to figure out a way to better handle markdown tables.

I'm pushing a quick fix in 6a95c83 to #225 but if others have better ideas please discuss here.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Added mobile friendly tables.

Resolves #246

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@skipjack what do you think?

**Comment by skipjack** [comment]
@NejcZdovc my inclination is to tie in some of the styling changes from #440, then merge this and come back to it more in-depth later on if we ever get to moving away from `marked`. 

I think the cleanest way to implement all these customizations in a react environment is to have something parse the markdown and pass that data to react components for any kind of special behavior. The only projects I have come across that seem to offer this functionality are:

- [markdown-to-react-components](https://github.com/christianalfoni/markdown-to-react-components)
- [reactdown](https://andreypopp.github.io/reactdown/)

My only worry would be trying to pick something that will continue to be maintained.

cc @bebraw @bdougie - interested in both of your thoughts here as well. I know we've discussed this a bit on #178.

**Comment by skipjack** [comment]
@NejcZdovc we should try to delineate the the two "rows" better here, they can blend together a bit.

image

In your screenshot in #246 you had removed the horizontal borders within each row:

image

which would be a good start although I'm not sure if this is tough to implement or not.

**Comment by NejcZdovc** [comment]
@skipjack yes you are correct. I only changed table parser, everything else was copied from an original library. I didn't find a way to override only table renderer so I needed to override `tok` function.

Regarding design, in this stage I only added basic styling, so that if you like the approach we can go one step further. So let's first check if we all agree to like this change and then invest some more time into CSS changes. Personally I like this approach, because it's a lot more readable on mobile and like you said it's not a perfect solution, but I am not aware of a perfect one :smile:

**Comment by NejcZdovc** [comment]
@skipjack I removed borders now for mobile

**Comment by bdougie** [comment]
@skipjack, having these customizations and overrides would be interesting in a React Component. I like the idea of generally making hi-jacks or overrides more declarative than implied, which is what the markdown.js does a lot of. TBH, it took me a bit of time just to get up to speed with the file, but that might just be a limit of my experience.

I also have reservations to adding more options to the markdown.js but only from the experience trying to swap/update marked to a moreup to date and maintained remarkable or showdown.

**Comment by bebraw** [comment]
@bdougie Yup, agreed. Ideally we should be able to push these kind of bits to React side. I would love to replace marked with something actively maintained btw.

That said, it's fine by me if we go with a solution that makes sense from user point of view even if the solution is not technically perfect. So keep up good work. 👍

**Comment by skipjack** [comment]
@NejcZdovc looks much better with the removed borders on mobile... one last question:

image

It seems more than just the table contents is wrapped in `table-wrap` class, is this intentional?

Aside from that I think this is good to go, as you mentioned I'll probably be submitting another PR shortly after we get this one merged to do a bit more styling (somewhat based off of #440).

**Comment by NejcZdovc** [comment]
@skipjack No it was not intentional, I forgot to close `table-wrap`. It's fixed now.

**Pull request merged**
