### PR TITLE
建议

### PR DESCRIPTION
**Pull request by jean-lee**
阅读中建议，如下图所示：

图1
image

图2
image

图3
image
图3所对文字 --- “编译时,在不知道最终输出文件的 publicPath 的情况下，publicPath 可以先忽略,暂时留空，然后在入口点文件运行时，通过 __webpack_public_path__  动态设置。”

### CODE REVIEW

**Comment by SpaceK33z** [comment]
What is this? Please speak English here, so we can all understand it.

**Comment by bebraw** [comment]
Looks like it's a Chinese(?) translation. See https://github.com/vuefe/webpack2 and https://webpack.vuefe.cn .

**Comment by SpaceK33z** [comment]
Jup, that's okay, but what I wonder why it's a PR against this repo.

**Comment by bebraw** [comment]
It might have gone against the wrong repo, yeah. Better close this one.

**Pull request closed without merging**
