### PR TITLE
search results link to right place

### LINKED ISSUE #3366: v4.webpack.js.org
Known issues:

- search results link to the wrong domain
- edit page links to wrong branch

Features missing:
- persistent message on top saying that "You are browsing old docs"

### PR DESCRIPTION
**Pull request by niravasher**
Search results link to right place, not below. Closes #3366 
Screenshot from 2020-01-03 11-47-03

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/

### CODE REVIEW

**Comment by niravasher** [comment]
I don't understand why CI tests fail. Used --no-verify to commit. ESlint is present.

**Comment by niravasher** [comment]
@jamesgeorge007 @montogeek @EugeneHlushko what else is required to merge the PR? Please suggest required changes

**Comment by anikethsaha** [comment]
dont use `--no-verify`
resolve the linting issues locally 
https://github.com/webpack/webpack.js.org/blob/master/package.json#L44-L49

**Comment by anikethsaha** [comment]
Please check the tests locally !!!!

**Comment by niravasher** [comment]
Sorry for the previous commit
While making changes in the Link/link.jsx file, react does not support DOM elements, hence I can't use window or document element directly.
So I did this
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Link } from 'react-router-dom';
var createReactClass = require('create-react-class');

function offsetAnchor() {
  if(location.hash.length !== 0) {
    window.scrollTo(window.scrollX, window.scrollY - 100);
  }
}

var Box = createReactClass({
  componentDidMount: function() {
    document.addEventListener('hashchange', offsetAnchor);
    document.setTimeout(offsetAnchor, 1);
  }
});
ReactDOM.render(<Box />);

```
Build shows this error
`ERROR in Invariant Violation: createClass(...): Class specification must implement a render method.`
What should I do?

**Comment by montogeek** [comment]
@anikethsaha No need to add 4 exclamation points to your comment.

**Comment by anikethsaha** [comment]
> Sorry for the previous commit

Why sorry ?

> @anikethsaha No need to add 4 exclamation points to your comment.

@montogeek I didnt get this, does having 4 exclamation points mean something wrong ?
I am not getting the thing here.

**Comment by EugeneHlushko** [comment]
@anikethsaha it looks like an order or in a command tone, i suggest you keep it friendly and rather advise or suggest, e.g. `I would suggest you run the tests locally before requesting reviews to save both yours and reviewers time.`

If i would apply the same technique you've used there, my suggestion would also look rude:
`Stop giving orders to contributors @anikethsaha !`

**Comment by anikethsaha** [comment]
> @anikethsaha it looks like an order or in a command tone, i suggest you keep it friendly and rather advise or suggest, e.g. `I would suggest you run the tests locally before requesting reviews to save both yours and reviewers time.`
> 
> If i would apply the same technique you've used there, my suggestion would also look rude:
> `Stop giving orders to contributors @anikethsaha !`

I am sorry , i kind of have a habit of using `!` frequently not just in GitHub but in other platforms as well.
I will try to change my commenting style

**Comment by EugeneHlushko** [comment]
This was fixed via css

**Pull request closed without merging**
