### PR TITLE
Improve lint:links - exclude support images/links

### PR DESCRIPTION
**Pull request by simon04**
* Ignore failures on sponsor/backer images/links
* Do not allow any other failure to not miss broken links such as https://github.com/webpack/webpack.js.org/pull/1188 or https://github.com/webpack-contrib/less-loader/pull/194

### CODE REVIEW

**Comment by skipjack** [comment]
This is great, unfortunately we still have to figure out this `FATAL ERROR: ...` thing happening in the hyperlink package. I may test the suggestion [here](https://github.com/webpack/webpack.js.org/pull/1170#issuecomment-298858925) if that works as a temporary solution. @Munter maybe we should create an issue for this over at the hyperlink package to track a more stable fix?

**Comment by skipjack** [comment]
@Munter thanks for being so responsive and helpful with this package... just created Munter/hyperlink#117 so we can track this.

**Comment by simon04** [comment]
Currently the check correctly fails due to one broken link. Maybe we should wait for https://github.com/webpack-contrib/less-loader/pull/194 to be merged?

**Comment by skipjack** [comment]
@simon04 yea I'm good with that, I'll leave this to you then.

**Comment by simon04** [comment]
Since the other PR is merged, I'll merge this one as well. :smile:

**Pull request merged**
