### PR TITLE
Fix typo 'matro' -> 'metro' in asset documentation

### PR DESCRIPTION
**Pull request by hiddewie**
The title speaks for itself ;)

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
Can you accept CLA?

**Comment by hiddewie** [comment]
Yeah, I did yesterday but maybe with the wrong email address? I will try again.

**Comment by snitin315** [comment]
Try closing and re-opening PR.

**Comment by hiddewie** [comment]
Yeah there is a :heavy_check_mark: now :)

**Review by chenxsan — APPROVED** [review]

**Comment by chenxsan** [comment]
@hiddewie Thank you for your contribution to webpack.

**Pull request merged**
