### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by selbekk**
Walked through this guide as I was porting a project from webpack 1 to 2 - and spotted a few typos.

### CODE REVIEW

**Comment by simon04** [comment]
Thanks for the PR. Looks good, but I'd stick with `webpack 1` instead of `webpack v1` since it is far more common (using [ag](https://github.com/ggreer/the_silver_searcher)):
```
$ ag 'webpack [123]' | wc -l 
30
$ ag 'webpack v[123]' | wc -l 
3
```

**Comment by selbekk** [comment]
Ah good point, just looked at the one document - I'll correct it tomorrow 😊

**Comment by simon04** [comment]
Please rather get rid of the 3 instances of `webpack v[123]` than changing 30 the other way. Feel free to open a separate PR on that. Thanks.

**Comment by selbekk** [comment]
There you go - a global search replace for `webpack v[123] -> webpack [123]`

**Comment by selbekk** [comment]
Not sure about this CLA issue - I pushed from my work computer (instead of my personal computer as I did yesterday), and even though I've now added that email to my github-account it still seems slightly broken.

**Comment by simon04** [comment]
Please fix the CLA check. Your commits are done with different mail addresses, see the `From:` lines in https://patch-diff.githubusercontent.com/raw/webpack/webpack.js.org/pull/1002.patch

**Comment by selbekk** [comment]
@simon04 - I've added the email in question to my user profile, and then I revoked the access tokens for the js.foundation CLA app before logging in again - but I can't figure out how to re-sign it with my new email.

Any tips? =)

**Comment by simon04** [comment]
I rebased your commit following https://stackoverflow.com/a/750182. After the Travis build we should be set.

**Pull request merged**
