### PR TITLE
ui(homepage) fix heading alignment

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Heading were all aligned left on homepage splashes, probably we broke it when merged rebuild.

### CODE REVIEW

**Comment by montogeek** [comment]
And how does it look?

**Comment by pranshuchittora** [comment]
@EugeneHlushko  please share the screenshot of the changes.

**Comment by anshumanv** [comment]
I'll just plug in the local changes that I pulled to review to make things quick - 
image

Before - 
image

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
