### PR TITLE
docs(contribute): improve code example

### PR DESCRIPTION
**Pull request by radiocity**

### CODE REVIEW

**Comment by radiocity** [comment]
I`ve found the example code leads to `Failed: null` during jest tests

**Comment by radiocity** [comment]
@EugeneHlushko, https://github.com/radiocity/webpack-pr-2818

**Comment by EugeneHlushko** [comment]
There is a reference error in loader's code:
```
 FAIL  test/index.test.js
  ✕ Build (1184ms)

  ● Build

    ReferenceError: callback is not defined

      2 |   return new Promise(resolve => {
      3 |     setTimeout(() => {
    > 4 |       resolve(callback(null, content, map, meta));
        |       ^
      5 |     }, 500);
      6 |   });
      7 | }
```

**Comment by radiocity** [comment]
image

**Comment by EugeneHlushko** [comment]
Maybe it doesn't work for me because i am on macos, can anyone try this the demo repo on Win pls to confirm?

**Comment by radiocity** [comment]
image

**Comment by EugeneHlushko** [comment]
hi @jeremenichelli
IIRC you had a windows available somewhere or do i remember wrong?

**Comment by jeremenichelli** [comment]
@EugeneHlushko nope, I'm on mac too

**Comment by radiocity** [comment]
@jeremenichelli, would you mind to run test on your machine, please?

**Comment by montogeek** [comment]
I have Windows, can test it in 4 hours

**Comment by EugeneHlushko** [comment]
thanks @montogeek because after pulling demo repo i have unrelated errors (path of include is off, and then another ref error in the code, which actually looks valid)

**Comment by montogeek** [comment]
It looks correct, right?
image

**Comment by EugeneHlushko** [comment]
Yes indeed

**Comment by EugeneHlushko** [comment]
If anyone else wants to try this out please do otherwise we will merge this based on windows run in a day or two

**Comment by radiocity** [comment]
Closed due to lack of activity.

**Comment by montogeek** [comment]
@radiocity Please reopen it, it is ready to merge

**Comment by EugeneHlushko** [comment]
Yes only needs update and tests to pass 👍

**Pull request closed without merging**
