### PR TITLE
use correct URL encoded value for space

### PR DESCRIPTION
**Pull request by sudo-barun**

### CODE REVIEW

**Comment by chenxsan** [comment]
@sudo-barun Could you sign cla here https://cla.js.foundation/webpack/webpack.js.org?pullRequest=5155?

**Comment by sudo-barun** [comment]
> @sudo-barun Could you sign cla here https://cla.js.foundation/webpack/webpack.js.org?pullRequest=5155?

@chenxsan Why is that necessary?

**Comment by chenxsan** [comment]
As far as I know, it's how the webpack repository deals with the intellectual property. You might want to check https://github.com/webpack/webpack/pull/13576#issuecomment-871355802 for details from the author.

**Comment by sudo-barun** [comment]
@chenxsan Then, create your own this pull request with this change. I am not going into the hassle just for this small change.

**Comment by chenxsan** [comment]
Superseded by https://github.com/webpack/webpack.js.org/pull/5156. @sudo-barun Thanks for heads-up.

**Pull request closed without merging**
