### PR TITLE
docs(configuration): Using mdx syntax.

### PR DESCRIPTION
**Pull request by 1010543618**
The `js-with-links` language tag of code blocks  can't recognize by `.md` file, so I change it to `.mdx`.

### CODE REVIEW

**Comment by 1010543618** [comment]
In line 223

```
\`\`\`js-with-links
module.exports = {
  //...
  module: {
    rules: [
      {
        //...
```

**Comment by montogeek** [comment]
@1010543618 How does it look?

**Comment by 1010543618** [comment]
@montogeek 
```
node: {...} // reconfigure [node](/configuration/node) layer on module level
```
This link displays normally. I'll take a screenshot tomorrow.

**Comment by 1010543618** [comment]
Before：

before

After：

after

Full Web Page Screenshot：

FireShot

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
