### PR TITLE
Fix home's SVG

### LINKED ISSUE #1752: Bug - Blurry SVG Text on Firefox 57.0.2 (64-bit) Win10
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

image

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Legible text.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Site: https://webpack.js.org
Browser: Firefox 57.0.2 (64-bit)
OS: Win10

### PR DESCRIPTION
**Pull request by pierreneter**
Fixed and close #1752 
@duncanawoods can you clone this branch and check this issue still exist or not? I fixed this problem but, maybe, this is a temporary solution because I can't use `raw-loader`.

/cc @skipjack

### CODE REVIEW

**Comment by pierreneter** [comment]
Have still a small problem when resize

**Comment by skipjack** [comment]
I'll merge once the build passes again.

**Comment by Mizziw** [comment]
Ok merge

**Pull request merged**
