### PR TITLE
feat(printable) cherry-pick SetTrends work and resolve confclicts

### LINKED ISSUE #2632: Documentation in printable format (CSS media queries)
## Feature request

Please add appropriate CSS media queries to allow for printing the documentation.
And please add a web page containing the whole documentation as one single large HTML file, including a TOC.

**What is the expected behavior?**

The documentation is supposed to be printable; without navigation, comment and other chrome.

**What is motivation or use case for adding/changing the behavior?**

Learning Webpack in environments where there is neither electricity nor radio reception.

**How should this be implemented in your opinion?**

Using CSS `print` media queries and CSS generated content for page numbering / TOC.

**Are you willing to work on this yourself?**

No, I'm working on other projects.

---

This issue was moved from webpack/webpack#8331 by @montogeek. Original issue was by @SetTrend.

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Fixes #2632

Based on @SetTrend 's initial work in #2754
Cherry-picked to not lose contribution.

Changes:
- Hand drawn icon of the printer to not have issues with copyrights
- Adding an ability to print current page
- Adding ability to print current section in the new tab, which automatically closes when cancelled/printed dialog closed
- Made it possible to not include the concatenated pages into FE bundle to not increase bundle size
- Made service worker ignore the printable URLs as it would serve 404 from FE bundles
- Made service worker to go network-first for less problems with caching when your device is online
- Refactored scss to not have importants
- Added respective components to support the feature

Screen Shot 2019-06-05 at 4 39 07 PM

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Ideas why this fails on travis are welcome:
```
✖ FAIL load https://david-dm.org/webpack-contrib/url-loader.svg
  | operator: load
  | expected: 200 https://david-dm.org/webpack-contrib/url-loader.svg
  |   actual: ETIMEDOUT
  |       at: dist/loaders/url-loader/index.html:3:69 <img src="https://david-dm.org/webpack-contrib/url-loader.svg" alt="deps">

```

**Comment by montogeek** [comment]
It says there: ETIMEDOUT, Maybe increase it?

**Comment by EugeneHlushko** [comment]
There is no API for it in the package, CC @munter maybe you want to add this later

**Comment by EugeneHlushko** [comment]
Another one randomly failed :) `FAIL load https://david-dm.org/webpack-contrib/css-loader.svg`

**Comment by EugeneHlushko** [comment]
Could be that travis cannot handle 25 concurrents well enough. Just lowered to 8

**Comment by EugeneHlushko** [comment]
We might want to discuss disabling the checks for downloaded pages? @montogeek

**Comment by EugeneHlushko** [comment]
Okay that worked, will remove the exception and its good to go

**Comment by EugeneHlushko** [comment]
Going to merge when build passes and make a short intro in twitter :)

**Comment by EugeneHlushko** [comment]
TY @SetTrend , myself and people who supported this feature

**Comment by SetTrend** [comment]
@EugeneHlushko : Thanks so much, Eugene. That's such an excellent work you did. I love it!! ❤️ 👍

**Pull request merged**
