### PR TITLE
Update docs with info-verbosity option

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Add the newly added `info-verbosity` to the docs. Reference to addition: webpack/webpack-cli#200

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hi man @skipjack 
Can you review this one? We did close a linked issue in webpack repo but the doc is not showing how to use the flag without this pr

**Comment by EugeneHlushko** [comment]
I've rebased this on as it got too old :/

**Comment by EugeneHlushko** [comment]
This landed into master, so its live in latest cli version @skipjack

**Comment by skipjack** [comment]
Yeah, my question is more that it doesn't seem like `webpack-cli` is shipped with `webpack` in `v3`:

https://github.com/webpack/webpack/blob/v3.11.0/bin/webpack.js

In `v4` I think it's required as a separate install. So I might switch this to `next` seeing as `v4` actually requires users to use `webpack-cli`. Let me know if this makes sense or not, if yes then I'll repoint it to `next` and merge.

**Comment by EugeneHlushko** [comment]
very true, i forgot that 3.11 still not sing cli. So `next` it is @skipjack

**Pull request merged**
