### PR TITLE
chore(glossary): removes blank sections

### PR DESCRIPTION
**Pull request by pranshuchittora**
**Description**
Blank sections don't look good.

Screenshot from 2019-06-28 14-47-00

### CODE REVIEW

**Comment by pranshuchittora** [comment]
IMO, a glossary should have sections only where content exists. It is not compulsory that a glossary must cover the entire set of alphabets. It can be built over a period of time.

**Comment by anshumanv** [comment]
> IMO, a glossary should have sections only where content exists. It is not compulsory that a glossary must cover the entire set of alphabets. It can be built over a period of time.

I second this. 👍

**Comment by pranshuchittora** [comment]
It's been a long time since this PR has been updated. Pls, let me know your final reviews.

**Comment by EugeneHlushko** [comment]
@pranshuchittora 
It looks like we did not get any traction or issues with glossary letters recently, but if you are willing to contribute this, remove them completely instead of commenting out.

**Comment by pranshuchittora** [comment]
@EugeneHlushko suggested changes has been made :smile: :+1:

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
