### PR TITLE
Update why-webpack.md

### PR DESCRIPTION
**Pull request by Vitegor**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
webpack should always be written in lower case, as documented in the webpack/media repo

**Comment by bebraw** [comment]
@SpaceK33z That would be a good thing to lint (mdlint plugin?). No need to worry after that.

**Comment by bebraw** [comment]
Here's a related issue if you want to track: https://github.com/DavidAnson/markdownlint/issues/39 .

**Comment by bebraw** [comment]
I think I'll close this. We'll get a linting rule in place eventually to force the writing style in this particular case.

**Pull request closed without merging**
