### PR TITLE
Opencollective

### PR DESCRIPTION
**Pull request by NejcZdovc**
Fixed svg limitation discussed in #259. PR is created based on #260, so that can be easily tested. It can be then merged into #260 or rebased to the develop after #260 is in develop branch.

I am not sure about naming of the component yet. Is support ok? What do you think @skipjack?

### CODE REVIEW

**Comment by skipjack** [comment]
Support seems fine, thanks for jumping on this. Can you share a screenshot?

**Comment by bebraw** [comment]
@skipjack Quick way to check these - `git fetch origin pull/261/head:tmp` (fetches PR to `tmp` branch you can delete).

**Comment by NejcZdovc** [comment]
For now I only printed them in the wrapper of the page. Every badge is an simple a link, so you can style them however you like it. You can set how many people you would like to display with passing number into the component.

`<Support number={ 20 } type={"backer"} />`

image

**Comment by NejcZdovc** [comment]
One thing that I like on http://mochajs.org/ page is that they split backers and sponsors into two sections. For now, we have it in a single block. I suggest to add title for each one.

**Comment by skipjack** [comment]
I can split 'em 👍 and clean up the layout a bit more. Just getting them to wrap was the big thing. I'll merge this into #260 tonight.

**Comment by NejcZdovc** [comment]
Ok great

**Comment by TheLarkInn** [comment]
Let us know when this is good to go, and we'll test and approve.

**Comment by NejcZdovc** [comment]
@TheLarkInn as far as I know @skipjack already tested it and it's ok from his end. From my end is finished. I only fixed generator for him. He will now implement it into his PR and add sections as we discussed above.

**Comment by TheLarkInn** [comment]
So this is good to merge? Just double checking for sanities sake.

**Comment by NejcZdovc** [comment]
@TheLarkInn This PR shouldn't be merged with develop branch. This should be merged with #260 (branch feature/splash-page).

**Comment by skipjack** [comment]
@TheLarkInn - @NejcZdovc branched off another PR, #260, so I'll merge this into there and we can close this one and focus on getting #260 merged.

**Comment by TheLarkInn** [comment]
Ship it!

**Comment by skipjack** [comment]
Successfully merged into #260, thanks @NejcZdovc!

**Pull request closed without merging**
