### PR TITLE
docs(contribute): remove broken link to the documentation team

### PR DESCRIPTION
**Pull request by dkdk225**
I was unable to find a new documentation team link. As a solution i suggest removing it completely

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
The link is actually valid, but it's accessible only for webpack org members on GitHub

**Comment by dkdk225** [comment]
Oh i see. Do you have a suggestion for improvement (like making the link avalible to non-members) or should we leave it as it is

**Comment by dkdk225** [comment]
Oh i see. Then should i change commit/PR name or do you suggest another solution ?

**Review by evenstensberg — APPROVED** [review]
lgtm, an author can just cc a maintainer by looking at github contributors page

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
