### PR TITLE
add eslint-webpack-plugin to plugins list

### PR DESCRIPTION
**Pull request by chenxsan**
CI for pull request https://github.com/webpack/webpack.js.org/pull/3963 failed now https://travis-ci.org/github/webpack/webpack.js.org/jobs/730802775#L992, it might be a result of the update here https://github.com/webpack-contrib/eslint-loader/commit/fc94b5d976f3176eba6d1460fba9dde99227ac32 because eslint-webpack-plugin is not existed yet in this repository.

BTW, it's wrong to edit the `plugins.json` or `loaders.json` file like this, they should be generated by `src/utils/fetch-package-repos.js` automatically. But let's fix that later after the webpack 5 branch get merged as there're already multiple manual edits as I found, e.g. https://github.com/webpack/webpack.js.org/pull/3985, https://github.com/webpack/webpack.js.org/pull/3903

### CODE REVIEW

**Comment by chenxsan** [comment]
CI [failed](https://travis-ci.org/github/webpack/webpack.js.org/jobs/730804736#L1511):

```
ERROR in Error: Module build failed (from ../node_modules/remark-loader/src/index.js):
TypeError: Cannot read property 'contents' of undefined
    at plugins.reduce.use.process (/home/travis/build/webpack/webpack.js.org/node_modules/remark-loader/src/parse.js:30:35)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/unified/index.js:377:11)
    at next (/home/travis/build/webpack/webpack.js.org/node_modules/trough/index.js:42:9)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/trough/wrap.js:55:16)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/unified/index.js:32:7)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/unified/index.js:306:11)
    at next (/home/travis/build/webpack/webpack.js.org/node_modules/trough/index.js:42:9)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/trough/wrap.js:55:16)
    at wrapped (/home/travis/build/webpack/webpack.js.org/node_modules/trough/wrap.js:36:14)
    at next (/home/travis/build/webpack/webpack.js.org/node_modules/trough/index.js:57:24)
    at done (/home/travis/build/webpack/webpack.js.org/node_modules/trough/wrap.js:55:16)
    at then (/home/travis/build/webpack/webpack.js.org/node_modules/trough/wrap.js:62:5)
```
It seems to be caused by this empty table head in eslint-webpack-plugin's readme:

image

cc @evilebottnawi Any chance we can fix it in eslint-webpack-plugin repository? Just add something non-empty like `-` should be enough. Otherwise we have to fix it in https://github.com/montogeek/remark-responsive-tables/blob/master/src/index.js#L20 with something like below to permit empty head:

```js
headers = node.children.map(header => typeof header.children[0] !== 'undefined' ? header.children[0].value : '');
```

**Comment by chenxsan** [comment]
I think we have another choice here as we can remove the deprecated eslint-loader to work around the empty table head problem.

**Review by EugeneHlushko — COMMENTED** [review]
yes lets remove, maybe also stick a redirect on the loader page to plugin page?

**Comment by evilebottnawi** [comment]
@chenxsan Feel free to send a fix

**Comment by EugeneHlushko** [comment]
ok there is already #4010, nevermind

**Review by EugeneHlushko — APPROVED** [review]

**Pull request merged**
