### PR TITLE
Fix odd dependency in landing page graphic

### PR DESCRIPTION
**Pull request by skipjack**
Fixing #562.

Also tweaking the graphic positioning to center it more...

**Before:**

image

**After:**

image

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Oh sorry, didn't see the review request!

**Comment by skipjack** [comment]
No worries, do those not fire off notifications or something? I can add a comment next time if that helps..

**Comment by SpaceK33z** [comment]
Yeah they do, but since I was watching all issues in this repo, the list of notifications is sometimes so long that I just click on mark as read to keep my mind at ease. I have now unwatched this repo so I'll see notifications directed at me better 😄 . GitHub really should make a distinction between these two notifications...

**Comment by skipjack** [comment]
Yeah I hear you, I recently turned off email notifications except for mentions for same reason (getting pinged way too many times a day). If you have time take a look at #928, interested in your thoughts on the table customizations (it's a follow-up PR from #875).

**Pull request merged**
