### PR TITLE
Update alex@9.1.0

### LINKED ISSUE #4196: Upgrade alex
The latest version of [alex](https://github.com/get-alex/alex/releases) is 9.1.0 while we have [5.1.0](https://github.com/webpack/webpack.js.org/blob/master/package.json#L90) which is quite outdated. We should consider upgrading it and fix any potential issues.

### PR DESCRIPTION
**Pull request by jeffin143**
Fix #4196 

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].

### CODE REVIEW

**Comment by jeffin143** [comment]
@chenxsan  There are 145 warnings , but I think they are more or less ok, Like it was throwing an error on `Special Thanks` and was asking to replace it by `Has a ability` which I think is out of context

**Comment by jeffin143** [comment]
We can hide them by using `<!--alex ignore-->` although I feel 145 such comments are too much :)

**Comment by chenxsan** [comment]
> We can hide them by using `<!--alex ignore-->` although I feel 145 such comments are too much :)

Yep, that would render `alex` useless.

**Comment by chenxsan** [comment]
How about removing it? So far `alex` has never caught one error, and upgrading it to v9 would need a lot of changes not really necessary in my opinion.

**Comment by chenxsan** [comment]
Closed in favor of https://github.com/webpack/webpack.js.org/pull/4840

**Pull request closed without merging**
