### PR TITLE
docs(module): update Rule.enforce typo

### PR DESCRIPTION
**Pull request by hisland**
docs(module): update Rule.enforce typo
according to my test, it might be like this

### CODE REVIEW

**Comment by skipjack** [comment]
This change looks valid to me.. I'm pinging the rest of the team though just to be sure.

cc @webpack/documentation-team

**Comment by hisland** [comment]
my test is here: https://github.com/hisland/my-learn/tree/master/webpack2/write-loader/07.prefixing-omit-some

**Comment by simon04** [comment]
I tried to verify this change with the [source code of `NormalModuleFactory`](https://github.com/webpack/webpack/blob/cd688f8/lib/NormalModuleFactory.js#L185-L202) and I'm confused due to [`asyncLib.parallel`](https://caolan.github.io/async/docs.html#parallel) there.

**Comment by skipjack** [comment]
@sokra can you clarify if this change is valid?

**Comment by sokra** [comment]
It's not valid. The original was correct.

Regarding the order: It's expected that the log statements are emitted in reverse order, because the normal phase of loaders are executed in right to left order.

**Pull request closed without merging**
