### PR TITLE
Fix repo url with the correct default branch

### PR DESCRIPTION
**Pull request by yoriiis**
The plugins and loaders documentation contains links to edit the page with the default branch set to `master` while it may have another value, e.g. `main`.

Example of broken url on the plugin [svg-chunk-webpack-plugin](https://webpack.js.org/plugins/svg-chunk-webpack-plugin) (see `Edit this page` link at the bottom of the page)

```
https://github.com/yoriiis/svg-chunk-webpack-plugin/edit/master/README.md
```

The PR gets the default branch for each repository from the GitHub API. The README url also takes this change into account.

---

Question, should the npm script "lint:links" found this 404?

### CODE REVIEW

**Comment by yoriiis** [comment]
@snitin315 @chenxsan Could you take a look at this PR please?
(The Vercel deployment needs to be retry I think)

**Review by snitin315 — APPROVED** [review]
LGTM.

>(The Vercel deployment needs to be retry I think)

I guess it's the API rate limit issue. Unfortunately, I can't access the Vercel logs.

**Comment by chenxsan** [comment]
> LGTM.
> 
> > (The Vercel deployment needs to be retry I think)
> 
> I guess it's the API rate limit issue. Unfortunately, I can't access the Vercel logs.

Yeah, api limit. I've pushed a fix here https://github.com/webpack/webpack.js.org/pull/6797.

**Comment by chenxsan** [comment]
Unfortunately we just introduced a side effect now because of the vercel environment variable:





Not sure I should disable it.

**Comment by snitin315** [comment]
@chenxsan I think it's fine. Perhaps, can you also invite me (`snitin315@gmail.com`) to the Vercel account so that I can also authorize these deployments?

**Comment by chenxsan** [comment]
> @chenxsan I think it's fine. Perhaps, can you also invite me (`snitin315@gmail.com`) to the Vercel account so that I can also authorize these deployments?

Sorry, I don't have the permission to invite, you'll have to ask sokra to invite you.

**Pull request merged**
