### PR TITLE
docs(concepts): clarify `chunks.__./src/index.js` file extension name

### LINKED ISSUE #3874: confusion on under the hood chunks
document link https://webpack.js.org/concepts/under-the-hood/#chunks

since in line 96 we are naming the file as index.jsx and talking about jsx

> ./src/index.jsx
> react
> react-dom

so the subtitle chunks > ./src/index.js should be changed to chunks > ./src/index.jsx

### PR DESCRIPTION
**Pull request by amirsaeed671**
closes #3874

### CODE REVIEW

**Comment by chenxsan** [comment]
@amirsaeed671 Can you change PR title to `docs(concepts): ....`? Usually we use the folder name instead of the filename.

**Comment by amirsaeed671** [comment]
yeah sure

**Comment by amirsaeed671** [comment]
done @chenxsan

**Comment by EugeneHlushko** [comment]
Thanks!

**Comment by amirsaeed671** [comment]
@EugeneHlushko your welcome! it was my first contribution in github, and I am happy that it's in webpack documentation 😊

**Pull request merged**
