### PR TITLE
docs: fix webpack repo links that use legacy branch name

### PR DESCRIPTION
**Pull request by hex2dec**
The new default branch name of webpack repository is `main`, and the links in the docs still use the legacy branch name `master`.

### CODE REVIEW

**Comment by hex2dec** [comment]
hi @chenxsan, the E2E testing failed because `sass` and `dart2js` don't support the latest Node.js 21 at the moment. Can we fix the GitHub Action CI to use Node.js 20. If so, i will submit a PR.

* https://github.com/sass/dart-sass/issues/2122#issuecomment-1767256228

**Comment by chenxsan** [comment]
> hi @chenxsan, the E2E testing failed because `sass` and `dart2js` don't support the latest Node.js 21 at the moment. Can we fix the GitHub Actions CI to use Node.js 20. If so, i will submit a PR.
> 
> * [Node v21 - `navigator` object sass/dart-sass#2122 (comment)](https://github.com/sass/dart-sass/issues/2122#issuecomment-1767256228)

Probably wait for Node.21 to get it fixed? https://github.com/nodejs/node/issues/50269

**Comment by hex2dec** [comment]
@chenxsan 

Thanks! I found that Node.js has added the `navigator.userAgent` property, so we wait for it to release a new version.

* https://github.com/nodejs/node/pull/50200

**Comment by hex2dec** [comment]
hi @chenxsan, the Node.js v21.1.0 has been released. How can i recheck the e2e testing?

- https://github.com/nodejs/node/releases/tag/v21.1.0

**Review by chenxsan — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
