### PR TITLE
feat(pluginapi): implement separate directory structure for plugins api

### PR DESCRIPTION
**Pull request by TheLarkInn**
### This is just the directory structure
This directory structure allows contribs like @pksjce and myself to independently work on different sections of the plugin api with little friction. I'm going to close the existing PR I have open and we can start from here.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@bebraw I'd like to get this merged right away so that @pksjce can start working on individual sections. I also applied some of the content she originally added to this PR as well. 

Based on the antwar configuration, the section is accessible, but not publicly listed anywhere.

**Comment by TheLarkInn** [comment]
@pksjce Heads up when you want to test this page you goto `
localhost:3000/pluginsapi`

**Comment by pksjce** [comment]
Hey awesome! Thanks for doing this. Will wait for this to merge and then branch from there.

**Comment by SpaceK33z** [comment]
Realise now that you initially asked @bebraw to merge this, hope you don't mind...

**Comment by TheLarkInn** [comment]
Don't mind at all!!

**Pull request merged**
