### PR TITLE
fix dark mode toggle button

### PR DESCRIPTION
**Pull request by chenxsan**
See a gif below:

wp

A weird bug, seems react is reusing the outer `svg` which applied the wrong `viewBox` when hydrating.

## how to reproduce

1. open webpack.js.org
2. enter the dark mode
3. refresh the page

### CODE REVIEW

**Comment by snitin315** [comment]
I am not able to change to the dark mode or click the language dropdown in the [preview](https://webpack-js-org-git-fork-chenxsan-bugfix-fix-cdec26-webpack-docs.vercel.app).

dark-mode

**Comment by snitin315** [comment]
> I am not able to change to the dark mode or click the language dropdown in the preview.

Working now.

**Comment by chenxsan** [comment]
The service worker will cache quite a lot of files the first time accessing the url, which means you might have to wait a sec.

**Comment by chenxsan** [comment]
It's a quick fix because I want to fix this as soon as possible since this seems a urgent bug. Feel free to file a better fix if you have one.

**Pull request merged**
