### PR TITLE
Add MONEI and MoonMail sponsor logos as agreed with Alexandre Saiz

### PR DESCRIPTION
**Pull request by jimmyn**
Add MONEI and MoonMail sponsor logos as agreed with Alexandre Saiz Verdaguer  <a@alexandresaiz.com> (SEO at [microapps SL](http://microapps.com/))

### CODE REVIEW

**Comment by skipjack** [comment]
@jimmyn these are sponsors not going through open collective? This addition feels a bit hacky but if @webpack/core-team is good with it, I'm happy to review and merge for now and revisit this later on.

**Comment by bebraw** [comment]
@jimmyn Can you give a bit of background? Why OC isn't picking these up? What if the sponsorship provided by these companies stops?

**Comment by alexandresaiz** [comment]
@bebraw as discussed with Tobi see screensot: https://www.dropbox.com/s/kv1mxx40np0wqbm/Screenshot%202017-04-25%2023.33.00.png?dl=0

he was ok on adding this on https://webpack.js.org/ as per our contribution. We have no intention to stop the sponsorship in the coming at least 12 months.

**Comment by bebraw** [comment]
@alexandresaiz Ok, thanks for the clarification. 👍

**Comment by alexandresaiz** [comment]
@bebraw is it ok to be merged then?

**Comment by bebraw** [comment]
Yeah, I'll let @skipjack do the final call on this.

**Pull request merged**
