### PR TITLE
added yarn to installation way

### PR DESCRIPTION
**Pull request by behnammodi**
_describe your changes..._

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- **Remove these instructions from your PR as they are for your eyes only.**

[1]: https://github.com/openjs-foundation/EasyCLA#openjs-foundation-cla
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by chenxsan** [comment]
Thank you but I think it's not necessary. We have so many package managers like pnpm, etc. other than npm/yarn. Not gonna list them all.

**Comment by chenxsan** [comment]
> Thank you, but I think we can have something like this:
> 
> ```js
> const HtmlWebpackPlugin = require('html-webpack-plugin'); //installed via npm or any package managers
> ```
> 
> Why? because at the first time I read the document I was thinking we have to Install that just by `npm`

Or maybe we can just remove the comment to avoid misunderstanding.

**Comment by behnammodi** [comment]
> > Thank you, but I think we can have something like this:
> > ```js
> > const HtmlWebpackPlugin = require('html-webpack-plugin'); //installed via npm or any package managers
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why? because at the first time I read the document I was thinking we have to Install that just by `npm`
> 
> Or maybe we can just remove the comment to avoid misunderstanding.

Good idea, I changed

**Review by snitin315 — APPROVED** [review]
Thank you.

**Review by chenxsan — APPROVED** [review]

**Pull request merged**
