### PR TITLE
Recast this sentence about `externals`

### PR DESCRIPTION
**Pull request by n3dst4**
I really tripped over the original version because I read it as if the *consumer* was required to use `externals`. Obvious in hindsight but maybe this change will spare someone else a few minutes of confusion 😊

### CODE REVIEW

**Comment by montogeek** [comment]
Please sign CLA.

**Comment by n3dst4** [comment]
> Please sign CLA.

I have!

**Comment by EugeneHlushko** [comment]
Thanks!

**Comment by montogeek** [comment]
Bot still says Pending. We can't merge code without it.

**Comment by n3dst4** [comment]
> Bot still says Pending. We can't merge code without it.

Not sure if I'm missing something but over here it says:
image

**Comment by montogeek** [comment]
Hook doesn't, lets trust that bagde. :)
image

**Pull request merged**
