### PR TITLE
Fix #924 - Make Sidebar anchor links not reload/refresh page. 

### LINKED ISSUE #924: Proposal: Make Sidebar anchor links not reload/refresh page.
All Sidebar links pointing to anchors in the **current** page should only have URL fragments in their `href` attribute `<a href="#example">`.

 For example, when I'm in _https://webpack.js.org/concepts/loaders/_, clicking **Example**, under **Loaders**, on the Sidebar, should not reload the page because I'm already on the page. It should simply take me to **Example** section of the page

### Solution

In the `sidebar-item.jsx`, line 21 - 30, utilizing the title props, the `sidebar-item` component should be able to determine when to render the full anchor URL or only the `anchor.id`. 
Render either this 
`<a href={ anchorUrl + anchor.id }>{ anchor.title}</a>`, 
or  this 
`<a href={anchor.id }>{ anchor.title}</a>`

Can I help? :hand:

### PR DESCRIPTION
**Pull request by Dajust**
Based on #924, I compared the `currentPage` props to the `url` props, to determine what should be the `href` value of the Sidebar anchor links. 

It works! :dancer: :smile:

### CODE REVIEW

**Comment by skipjack** [comment]
@Dajust please sign the CLA, I'll review, and hopefully we can get this merged!

**Comment by simon04** [comment]
@Dajust, ping! Please sign the CLA.

**Comment by Dajust** [comment]
@skipjack @simon04 I need help!
 Sorry for the delay, thought I've signed the CLA earlier. The CLA page is showing that I've signed this (image bellow). 
webpack-cla
But it appears the system doesn't still recognise my email. I've reset my github email address to the email address on my local git repository - the one I used for this commit - still, the check is still failing

Please what else can I do to resolve this? 
Could a new PR fix this?

**Comment by simon04** [comment]
I'll try to close + reopen the PR. That should trigger another CLA check.

**Comment by Dajust** [comment]
It works! :smile: 
Thanks :+1: @simon04

**Pull request merged**
