### PR TITLE
chore: remove unused file

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Removed the respective file that isn't used anymore.

### CODE REVIEW

**Comment by montogeek** [comment]
Thanks for your contribution, unfortunately this file shouldn't even exist. But you can delete it :)

**Comment by jamesgeorge007** [comment]
@montogeek if that's the case, should I close this one or delete the respective file and have it appear as the `diff` instead.

**Comment by jamesgeorge007** [comment]
Also, there're instances of `var` still being used within `src/utilities`. Shall I shoot yet another PR updating them to be `let`?

**Comment by jamesgeorge007** [comment]
\cc @montogeek @EugeneHlushko

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
