### PR TITLE
Update yarn.lock file

### PR DESCRIPTION
**Pull request by silvenon**
Not sure why, but this happened when I ran `yarn`.

### CODE REVIEW

**Comment by skipjack** [comment]
@bebraw do you know what's going on with this? I'm not too familiar with yarn.

**Comment by bebraw** [comment]
Looks like it pulled some new deps. It *might* be ok but you would have to check locally with a fresh install (nuke `node_modules` first).

**Comment by silvenon** [comment]
I ran `yarn` when I cloned the repo, so it didn't have an existing `node_modules`.

**Comment by simon04** [comment]
I can confirm this. Running `yarn` on a fresh clone of this repository, I get a different diff: https://github.com/webpack/webpack.js.org/compare/master...simon04:yarn

**Pull request merged**
