### PR TITLE
fix: indentation in code sample of split-chunks-plugin

### PR DESCRIPTION
**Pull request by Priestch**

### CODE REVIEW

**Comment by Priestch** [comment]
It would be better if the markdown linter can detect such error, @EugeneHlushko you know why my CLA not signed, I had signed already

**Comment by byzyk** [comment]
Agree with @EugeneHlushko, I guess linter scripts have to be revised since it's not the first time formatting is broken in the examples.

I've created an issue for this one #2151

**Comment by jeremenichelli** [comment]
Good point, yeah we should try to actually update the linter and run it on all the content.

**Comment by byzyk** [comment]
@jeremenichelli does it mean we can start on #2151? Please check my comment there with a suggested approach.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
