### PR TITLE
chore: added note for serve config

### LINKED ISSUE #3565: Document webpack change: improve schema and validation
*A pull request by @sokra was merged and maintainers requested a documentation change.*

See pull request: https://github.com/webpack/webpack/pull/10406

---

* remove serve property from options
* Add "did you mean" to schema validation for common errors

**What kind of change does this PR introduce?**
feature, removal

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
yes

**What needs to be documented once your changes are merged?**
`serve` property do no longer exist in configuration

### PR DESCRIPTION
**Pull request by anikethsaha**
fix #3565

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
I think this actually closes the issue: #3567

**Comment by anikethsaha** [comment]
@EugeneHlushko should I close this one ?

**Comment by EugeneHlushko** [comment]
@anikethsaha yes in my opinion, i keep it open only for discussion

**Comment by anikethsaha** [comment]
@EugeneHlushko I am fine with either way.  Yes, it's true that it is not documented and neither anyone uses it. But still, I think it would be good if it's mentioned. 

So I will close this and can you add a note in #3567 's changes about the removal of this!

Thanks

**Pull request closed without merging**
