### PR TITLE
docs(configuration): fix heading level

### PR DESCRIPTION
**Pull request by chenxsan**
`infrastructureLogging` should be heading 2 instead of heading 3.

## Before

image

## After

image

### CODE REVIEW

**Comment by montogeek** [comment]
Would be good to strip the first part of the sub sub heading if the name is too long, see for example in your second screenshot that you can't really read the real option name.

**Comment by montogeek** [comment]
I can't ignore this CLA bot :D, it seems its resources are too low to process its state correctly or maybe it is using something old to check for statutes.

**Comment by chenxsan** [comment]
@montogeek updated.

image

**Comment by EugeneHlushko** [comment]
In this case its fine, but i assume there can be cases where we wont do this for SEO reasons

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
