### PR TITLE
docs(writing-a-plugin): minor grammar fix

### LINKED ISSUE #3606: docs(writing-a-plugin): minor grammar error
__Feature to document__

> 
Screenshot from 2020-03-08 09-45-01
it should be `passed as an argument`

__Additional information__

I will work on this issue.

### PR DESCRIPTION
**Pull request by snitin315**
Fixes #3606  , minor grammar fix

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
We don't really check grammar in comments of the js (and other language) snippets, i don't think this is necessary at all but maybe someone else has other opinion from maintainers

**Comment by himanshu010** [comment]
I think that this change is in a comment and therefore it doesn't make any sense but yeah opinions of others are highly respected.

**Comment by snitin315** [comment]
@EugeneHlushko actually this comment created confusion while changing the docs in `webpack-cli` , hence I thought to fix it. 

Screenshot from 2020-03-10 10-13-19

**Comment by montogeek** [comment]
Let's add it, it is common to copy/paste it as explanation and it is better if it comes correctly from the official documentation.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
