### PR TITLE
Updates asset-management.md

### PR DESCRIPTION
**Pull request by TheDutchCoder**
Changed index.js to better line up with the next guide (Output Management).

### CODE REVIEW

**Comment by TheDutchCoder** [comment]
@skipjack not sure what this failed on :)

**Comment by skipjack** [comment]
Ah it failed on some other stuff that slipped in from other PRs. #1355 should address them, feel free to ignore.

**Comment by skipjack** [comment]
@TheDutchCoder can you see the [commit guidelines here](https://conventionalcommits.org/)? Not a big deal, but we're trying to follow it so we can do some cool stuff later on like auto-generating changelogs and doc versioning. For examples you can look at the master branch or ping me if you have questions.

I still need to update the readme and writers-guide soon to reflect some of these things.

**Comment by TheDutchCoder** [comment]
@skipjack will do, I'm not familiar with them yet, so I'll try my best not to make this a mess ;)

**Comment by skipjack** [comment]
No worries I can always "Squash and Merge" things later on to keep the history clean but seeing as you're a frequent contributor, it's good for you to know.

**Pull request merged**
