### PR TITLE
Update module-resolution.md

### PR DESCRIPTION
**Pull request by adam-beck**
Fixes small grammatical error

### CODE REVIEW

**Comment by simon04** [comment]
"webpack" is a singular noun. Thus "finds" is correct.

**Comment by adam-beck** [comment]
@simon04 I agree that "webpack" is a singular noun. However, `find` is still the correct word to use here. Unfortunaley I don't know the exact name of the rule or why it is that way.

```
Jack helps Jill tests the code

 **VS**

Jack helps Jill test the code
```

**Comment by adam-beck** [comment]
@simon04 It's called an infinitive. I found an article but unfortunately I can't link exactly where at on the page since it isn't using #ids.

http://www.chompchomp.com/terms/infinitive.htm

Then scroll to: **Recognize an infinitive even when it is missing the to**

**Comment by simon04** [comment]
Sorry, I overlooked your comment since the ticket was closed. Due to majority vote, I'll merge this one. 😉

**Pull request merged**
