### PR TITLE
doc(plugins): add SvgChunkWebpackPlugin

### PR DESCRIPTION
**Pull request by yoriiis**
This PR adds the `SvgChunkWebpackPlugin` to the plugins documentation page on the community group.
A dedicated page with instructions for use is also added.

Note: The readme is based on the [GitHub repository](https://github.com/yoriiis/svg-chunk-webpack-plugin). The latest version of the package and therefore of the readme is not yet available on npm in order to be able to synchronize any feedback made on this MR with the project's readme.

cc @alexander-akait

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
This is a 3rd party plugin and will add a maintenance burden for us to keep it in sync with GitHub's readme of the plugin. 

We already have a script to [fetch package readme](https://github.com/webpack/webpack.js.org/blob/main/src/utilities/fetch-package-readmes.mjs) for [loaders](https://webpack.js.org/loaders/css-loader/) & [plugins](https://webpack.js.org/plugins/compression-webpack-plugin/) from the[ webpack-contrib ](https://github.com/webpack-contrib)organisation. 

Maybe you can tweak the script to support fetching the readme of this plugin as well.

**Comment by yoriiis** [comment]
@snitin315 Good idea for readme synchronization. Changes can be centralized in the plugin's GitHub readme file. I made the changes, let me know what you think.

Also, I moved the package to the "Community" section, more suitable for 3rd parties imo. If you have any guidelines for the readme, I can make changes.

**Review by chenxsan — APPROVED** [review]
Thanks, looks good to me.

**Comment by chenxsan** [comment]
Just a note here, we might want to avoid including any community plugins in our repository as we already had the [`awesome-webpack`](https://webpack.js.org/awesome-webpack/) page reserved for third-party plugins/loaders. So far there's only `html-webpack-plugin` under the `Community` group because it's sort of required to use alongside webpack. Fetching too many community plugins in our repository is a burden to our build system, and we can't afford including all third-party plugins even though it's doable technically.

**Comment by yoriiis** [comment]
@chenxsan The job `Deploy Site (ubuntu-latest, lts/*)` has failed, did I mis something?

https://github.com/webpack/webpack.js.org/actions/runs/4796340976/jobs/8532004097

**Comment by snitin315** [comment]
The build site step failed, trying a re-run.

**Pull request merged**
