### PR TITLE
docs(config) warnings about configuration removal

### LINKED ISSUE #3170: Document webpack change: update enhanced-resolve
*A pull request by @sokra was merged and maintainers requested a documentation change.*

See pull request: https://github.com/webpack/webpack/pull/9366

---

**What kind of change does this PR introduce?**
deps upgrade

**Did you add tests for your changes?**
existing tests

**Does this PR introduce a breaking change?**
yes

**What needs to be documented once your changes are merged?**
resolve.enforceModuleExtension and resolve.moduleExtensions removed

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Closes #3170 

I decided to not remove the description of them just yet, it might be useful to keep for some time therefore PR is against `master` branch

### CODE REVIEW

**Comment by montogeek** [comment]
Uhmm, but webpack 5 is not released, this should point to `next`

**Comment by EugeneHlushko** [comment]
@montogeek i think it should go in master as a warning to those who are going to use these options in time period between now and webpack 5 release

**Comment by montogeek** [comment]
Sounds good

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
