### PR TITLE
fix(guides): Fixed example code typo

### PR DESCRIPTION
**Pull request by huang-x-h**
Update writing-a-plugin.md

### CODE REVIEW

**Comment by huang-x-h** [comment]
@montogeek Hi, how to review this PR, or is it incorrect and need to change?

**Comment by montogeek** [comment]
It was compilation before and was changed to `compiler`. I am not sure which one is the correct one.

**Comment by montogeek** [comment]
But given webpack own source code, it is compilation.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
