### PR TITLE
Swipable navigation menu on mobile

### PR DESCRIPTION
**Pull request by prateekbh**
This adds the capability for the navigation menu to open and close by swiping in either direction.

This also takes care that a diagonal swipe should result in only one of the two things
wither horizontal navigation close/open or vertical scroll.

### CODE REVIEW

**Comment by skipjack** [comment]
Tested this out, looks good thank you! I would just ask that you continue to follow [BEM](http://getbem.com/naming/) for the new elements you added and sign the CLA. Once that's done this should be good to go.

**Comment by prateekbh** [comment]
@skipjack the opener element right?
I guess sidebar-content should do good.

**Comment by skipjack** [comment]
@prateekbh it would be both. Basically, with BEM and react, each component is a "block" (in this case `sidebar-mobile`) and every other element is classed within that block so it has to be `sidebar-mobile__***`. Especially in this case where we have another Sidebar component thus making the `sidebar-content` somewhat confusing.

**Comment by skipjack** [comment]
Hey @prateekbh, hope you don't mind I pushed the fixes to your fork. Would you mind signing the CLA? Once that's done that I can merge 👍

**Comment by prateekbh** [comment]
Hey @skipjack, done :)
Thanks for fixing the stuff

**Comment by prateekbh** [comment]
Also please let me know when will it be deployed?

**Comment by skipjack** [comment]
Closing and re-opening with some last fixes and resolving of merge conflicts. @prateekbh thank you, I'll be merging the updated PR momentarily.

I don't do the deployments, but I suspect you'll see a PR called "Deploy" or "Publish" pop up this week -- once that's merged you should see the live site updated with these changes and others.

**Pull request closed without merging**
