### PR TITLE
update .travis.yml to fix warning

### PR DESCRIPTION
**Pull request by chenxsan**
See issue here https://github.com/webpack/webpack.js.org/issues/4031

### CODE REVIEW

**Comment by chenxsan** [comment]
Seems `prestart` won't run on CI.

**Comment by sokra** [comment]
I made a similar change. Could you rebase that on top of that?

**Comment by chenxsan** [comment]
@sokra sure.

**Review by sokra — APPROVED** [review]

**Comment by chenxsan** [comment]
@EugeneHlushko I'm afraid it's a bug introduced by me when I was adding cypress. Cypress needs to start the development server to run the end to end test, but according to https://github.com/webpack/webpack.js.org/blob/master/.github/CONTRIBUTING.md#setup we're required to run `npm fetch` manually the first time running `yarn start` which is missing in the CI. I've added two scripts preparing the missing json files for cypress in this PR, and they did eliminate those warnings https://travis-ci.org/github/webpack/webpack.js.org/jobs/733711718.

**Pull request merged**
