### PR TITLE
Update output.md

### PR DESCRIPTION
**Pull request by JerryYuanJ**
Update default value for output.chunkLoadingGlobal

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by montogeek** [comment]
Where is this default value defined?

**Comment by JerryYuanJ** [comment]
> Where is this default value defined?

I checked the output file and found it.

**Comment by chenxsan** [comment]
Maybe you have it set somewhere? According to https://github.com/webpack/webpack/blob/60f7ce301df553d8ab0276ba2838ddb60ead1c94/test/Defaults.unittest.js#L278, the default value is `webpackChunkwebpack`.

**Comment by JerryYuanJ** [comment]
Sorry that I made a mistake, I didn't read the source code and just run some demos for webpack 5 configs, I named my project 'webpack5' and it's set as name in `package.json`, so it's taken as part of `chunkLoadingGlobal`. I'll close this one.

**Pull request closed without merging**
