### PR TITLE
Update asset-management.md

### PR DESCRIPTION
**Pull request by brigham-hausman**
The instructions for  updating index.js with `css-loader` do not work unless you write the `import` statement correctly. The `css-loader` documentation is accurate and I figured this out by reading that doc.

### CODE REVIEW

**Comment by anshumanv** [comment]
Please sign the CLA ✨

**Comment by brigham-hausman** [comment]
Not sure what's up w the CLA UI here, but if you follow the link, you'll see that I signed it. *scratches head* :)

Screen Shot 2019-05-24 at 9 10 00 AM

**Comment by anshumanv** [comment]
This is happening too often, sorry about it, think reopening this PR should fix it. :)

**Comment by brigham-hausman** [comment]
Closed/reopened to bounce the CLA status.

**Comment by EugeneHlushko** [comment]
Was this error happening on the bundle that you've created after following the guide as-is or on different setup? This might be as well related to the whole webpack config or plugin versions. Need to understand why the `import "file.css"` didn't work for you and does work for us @brigham-hausman

**Comment by brigham-hausman** [comment]
@EugeneHlushko I was following the tutorial verbatim. I could not get the css rule to apply as described in the tutorial here: https://webpack.js.org/guides/asset-management#loading-css
Using `import './style.css';` in `src/index.js` never successfully applied the font color.

When I looked up the example for css-loader here:  https://webpack.js.org/loaders/css-loader/, I saw that the example assigned a variable name to the css import: `import css from 'file.css';`. When I added the `css` variable declaration to my tutorial code, the page rendered as expected.

**Comment by brigham-hausman** [comment]
@EugeneHlushko Now I can get things working exactly as described in the tutorial. I have no idea what I did wrong before. Sorry for the noise. This proposed change is indeed not needed.

**Pull request closed without merging**
