### PR TITLE
Prepend https:// to supporter website if it doesn't exist already

### PR DESCRIPTION
**Pull request by Munter**
The front page's supporters section has a lot of broken links where donors forgot to add a scheme in front of their domain of their website. All the links not containing schemes are broken.

This PR prepends a `https://` scheme in front of the website URL's that need it.

### CODE REVIEW

**Comment by montogeek** [comment]
@xdamman Do you think this could be solved in OpenCollective website?

**Comment by xdamman** [comment]
Good idea. Anyone up to do a quick pull request to the Open Collective codebase?
This would be the place to do it: https://github.com/opencollective/opencollective-api/blob/master/server/models/Collective.js#L190-L199

**Comment by Munter** [comment]
Done. That's a much better place to fix it. Closing this PR

**Comment by montogeek** [comment]
Thanks @Munter !

**Pull request closed without merging**
