### PR TITLE
feat: add option to hide sidebar using keycode

### PR DESCRIPTION
**Pull request by anshumanv**
Fixed https://github.com/webpack/webpack.js.org/issues/3538

Cmd + K presently, let me know if some other option would be more relevant

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by anshumanv** [comment]
Looking neat 

image

**Comment by montogeek** [comment]
This is nice, but it is really needed?
There is also no indication whatsoever that it is possible.

**Comment by anshumanv** [comment]
> This is nice, but it is really needed?
You said feel free to PR in the issue.

> There is also no indication whatsoever that it is possible.
Yeah we should add some indication, where though?

**Comment by montogeek** [comment]
> You said feel free to PR in the issue.

Me, but I don't have the final word.

> Yeah we should add some indication, where though?

Yeah, I don't know either. Probably just below the sidebar saying: "You can hide using Cmd+K", but then this is also solvable by using a button "<-" or something like that, then a tooltip on top that says, "You can also hide using Cmd+K".

I think the button is better.

**Comment by anshumanv** [comment]
Yeah let's go for the button 👍

**Comment by anshumanv** [comment]
Stale, closing - will reopen if we decide to have it

**Pull request closed without merging**
