### PR TITLE
docs(configuration): output.library.umdNamedDefine example fix

### PR DESCRIPTION
**Pull request by vsn4ik**
Related PR #4691.

Preview URL: https://webpack-js-org-git-fork-vsn4ik-output-library-umd-named-508c51.vercel.app/configuration/output/#outputlibraryumdnameddefine

### CODE REVIEW

**Review by chenxsan — APPROVED** [review]
Thanks.

**Comment by chenxsan** [comment]
@vsn4ik Can you sign the CLA here https://cla.js.foundation/webpack/webpack.js.org?pullRequest=4934?

**Review by noharashinchan — APPROVED** [review]

**Review by rishabh3112 — APPROVED** [review]

**Comment by vsn4ik** [comment]
@chenxsan Done!

**Review by snitin315 — APPROVED** [review]
Thanks!

**Pull request merged**
