### PR TITLE
More Robust Branding Guideline

### PR DESCRIPTION
**Pull request by rouzbeh84**
This is just to further flesh out the branding guidelines as well as set up some friendly links to font foundry, webpack shop, and threadless as well a special treat for those that actually use the guidelines.

### CODE REVIEW

**Comment by bebraw** [comment]
Nice. Can you check that proselint warning on Travis?

**Comment by bebraw** [comment]
Only

> content/branding.md:9:52: misc.tense_present 'in regards to'.

left I think.

**Comment by rouzbeh84** [comment]
I think it may be the file I added. If you like I can commit to core assets and hot-link to it or just remove. Most people in my slack channels seem to love it when I add these emojis so I thought it'd be fun.

**Comment by rouzbeh84** [comment]
Thanks for your help with the verbiage/tense issue btw as I was unaware that was a check here.

**Comment by bebraw** [comment]
Hi,

I think `./assets/icon-square-small-slack.png` is a relative import making the link check fail. I think going with `/assets/icon-square-small-slack.png` might fix the lookup as then it's relative to the root.

**Comment by rouzbeh84** [comment]
updated, let's hope this does the trick. gonna have to look into guidelines a bit further after this PR!

**Comment by rouzbeh84** [comment]
Hoooooray!!! Haha.

**Comment by bebraw** [comment]
Nice work. Thanks!

**Comment by rouzbeh84** [comment]
Thanks! Coming from design(ish) background I love having brand guidelines easily accessible 💯

**Comment by SpaceK33z** [comment]
Awesome work @rouzbeh84!

**Pull request merged**
