### PR TITLE
docs(config) apply consistent types format, small example added to co…

### PR DESCRIPTION
**Pull request by EugeneHlushko**
- consistent types across configuration section
- one more example to contrib for array mixed type

### CODE REVIEW

**Comment by montogeek** [comment]
Really nice :D

**Comment by montogeek** [comment]
Thanks!

**Comment by EugeneHlushko** [comment]
@montogeek i am thinking to link our types to that contrib section explaining types in a new tab, what do you think?

**Comment by EugeneHlushko** [comment]
not via <a href> but rather onlick

**Comment by montogeek** [comment]
How would that work? A link every page that uses that notation? That is too much.

**Comment by EugeneHlushko** [comment]
no, a global on click handler on a document was my initial thought @montogeek

**Pull request merged**
