### PR TITLE
Documentation on output.libraryTarget property

### PR DESCRIPTION
**Pull request by tomasAlabes**
Taken from [my post](http://tomasalabes.me/blog/_site/web-development/2016/04/30/Webpack-Series-Part-1.html) explaining this property among others. Suggested by Sean Larkin [tweet](https://twitter.com/TheLarkInn/status/790547583965863936).
Let me know what you think and what changes should we make to it.
: )

### CODE REVIEW

**Comment by sokra** [comment]
You modified the wrong page. concepts/output should be something completely different. It should explain the concepts and don't list the options. That's not your fault, I don't know why this content was in this page.

Could you merge the content from concepts/output into configuration/output (the configuration/output page is newer, so the content there is probably more true, but there is probably still some valuable content in the concept/output page)?

Leave concepts/output empty after merging. We don't have content for this page yet.

**Comment by tomasAlabes** [comment]
@sokra like this?
I will try to add some content to the concepts page in a different PR.

**Comment by bebraw** [comment]
@tomasAlabes Can you fix the conflicts as some related content was merged? I'll have a look after that.

**Comment by tomasAlabes** [comment]
Hi @bebraw, I think I messed up with the merge. I created a new PR with the changes, a cleaner PR #484.

**Comment by bebraw** [comment]
Alright.

Note that it should be safe to rebase and force push to a PR like this. Good technique to pick up.

**Comment by tomasAlabes** [comment]
Yeah, that was another way to go. Sorry about that.

**Comment by bebraw** [comment]
No probs. 👍

**Pull request closed without merging**
