### PR TITLE
docs(vote): redirect voting page in sidebar to v4 instead

### PR DESCRIPTION
**Pull request by mhnaeem**
Changes:

Redirecting the sidebar link for the Vote page to open the v4 version instead of a blank page. (#6002)

### CODE REVIEW

**Comment by chenxsan** [comment]
Weird, it works just fine in this pull request. https://webpack-js-org-git-fork-mhnaeem-bug-vote-pa-f14bfa-webpack-docs.vercel.app/vote

**Comment by snitin315** [comment]
The only difference is hosting, Github pages vs Vercel

**Comment by chenxsan** [comment]
So I spent some time troubleshooting the problem, seems the placeholder `Vote.mdx` is overriding the real Vote page. I've filed another pull request here https://github.com/webpack/webpack.js.org/pull/6017 to see if it fixes the problem.

**Comment by chenxsan** [comment]
I believe it was fixed in that pull request now, check https://webpack.js.org/vote/. @mhnaeem Thank you for raising this issue and your help to fix it!

**Pull request closed without merging**
