### PR TITLE
feat(nav): adds link for the swag store in the footer

### PR DESCRIPTION
**Pull request by pranshuchittora**
added link for the swag store in the navbar

### CODE REVIEW

**Comment by pranshuchittora** [comment]
> Navbar doesn't look like the most appropriate place to add this to me, maybe footer?

Makes sense.
Pls have a look at the new changes.

**Comment by anshumanv** [comment]
Did you forget to push maybe? 😆

**Comment by EugeneHlushko** [comment]
Hi @TheLarkInn pls take a look

**Comment by pranshuchittora** [comment]
@TheLarklnn & @EugeneHlushko any updates?

**Comment by montogeek** [comment]
Let's put it there, thanks!

**Pull request merged**
