### PR TITLE
Sidebar Redesign

### PR DESCRIPTION
**Pull request by skipjack**
Redesigning the sidebar to match @pastelsky's comp (see #438).

This is phase one of two for getting everything discussed in #438 (and things mentioned in some other issues like #1039) knocked out. My next task is updating the structure of the `/content` directory, the antwar config, etc to match our actual hierarchy in the site. This should allow us to map the banner links more dynamically and to allow grouping in the sidebar (with a few more tweaks).

Changes:

- Changing webpack version in sidebar to an image shield
- Updating sidebar design to come closer to the comp
- Doing some code cleanup/refactoring

Here's a gif of the updates:

### CODE REVIEW

**Comment by skipjack** [comment]
@SpaceK33z if you have time could you give this a quick go and see if anything needs fixing/tweaking?

**Comment by scottdj92** [comment]
Is there a reason why you switched from % based values to px based?

**Comment by skipjack** [comment]
@scottdj92 you mean in `page-style.scss`? I just wanted to ensure the sidebar always had enough room to look decent however I don't feel too strongly about that change... if you want to propose some widths that you think look better on more screens I'm all ears.

**Comment by scottdj92** [comment]
Oh no I trust you. I was just asking about it, because I know % based widths scale a bit better than direct px.

**Comment by skipjack** [comment]
Yea there are some screens in between our largest width and smallest width (e.g. like around 750px - 900px) that look a bit tight both in the sidebar and content areas). One option would be to break to our mobile view a bit earlier. 

Probably worth playing around with a bit more.

**Comment by skipjack** [comment]
Merged as I think this is a pretty significant improvement over what we have now.

@SpaceK33z @webpack/documentation-team feel free to to test and ping me or create a ticket if you notice any issues.

**Pull request merged**
