### PR TITLE
Implement fixed sidebar for docs page

### LINKED ISSUE #400: sticky sidebar when scrolling down the pages

### PR DESCRIPTION
**Pull request by rafaelrinaldi**
This is a first shot on implementing a fixed sidebar for the docs page.

Please, let me know if implementation looks OK.

Closes #400

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@SpaceK33z Thanks for the review, this is a good catch! Working on it.

**Comment by skipjack** [comment]
Hey @rafaelrinaldi this looks great, I noticed what @SpaceK33z said as well. There's kind of two problems there -- we **should** add a catch in the Sidebar stylesheet for text overflow but we **should also** try to fix some of the extra long titles 😁  as most can probably be rephrased a bit better. The second point obviously doesn't need to be fixed on this PR. Probably adding an ellipsis for extra-long titles would be fine IMO.

Also I noticed it overlaps the footer on at the bottom if you expand it enough:

image

Probably a quick check on the height of the footer vs. allowed space would do the trick.

**Comment by bebraw** [comment]
Can you rebase against `master`? The development happens against it now (faster deployments).

**Comment by rafaelrinaldi** [comment]
@bebraw 👍

**Comment by skipjack** [comment]
@rafaelrinaldi any updates on this? No pressure... just wanted to offer some help if you haven't already figured out solutions.

**Comment by skipjack** [comment]
Closing this in favor of an updated version of this branch. Opening the new PR momentarily...

**Pull request closed without merging**
