### PR TITLE
Feature/upgrade deps

### PR DESCRIPTION
**Pull request by chenxsan**
Unfortunately the [dependabot can't sign CLA](https://github.com/webpack/webpack.js.org/pull/4275) which means we can only use its pr for notification.

### CODE REVIEW

**Comment by montogeek** [comment]
These notifications are more spammy than useful. I would rather just upgrade dependencies every week.

**Comment by chenxsan** [comment]
> These notifications are more spammy than useful. I would rather just upgrade dependencies every week.

Then you would have to read the changelogs spanning multiple versions, it's more painful for me, that's why I prefer those notifications.

**Comment by snitin315** [comment]
We ignore CLA for dependabot in webpack and webpack-cli repo

**Comment by chenxsan** [comment]
> We ignore CLA for dependabot in webpack and webpack-cli repo

I have known that for a while. The reason I don't ask sorka for help is because we can't let the bot merge naively, there's no CI job ensuring it will run fine in development environment.

Every time I upgrade them, I would test those upgrades against development environment locally.

**Comment by montogeek** [comment]
> Then you would have to read the changelogs spanning multiple versions, it's more painful for me, that's why I prefer those notifications.

That's what I do every week in several repos. I can do it :)

**Comment by montogeek** [comment]
> We ignore CLA for dependabot in webpack and webpack-cli repo

It is that ok from the JS Organization perspective?

**Comment by chenxsan** [comment]
> > Then you would have to read the changelogs spanning multiple versions, it's more painful for me, that's why I prefer those notifications.
> 
> That's what I do every week in several repos. I can do it :)

Then feel free to remove https://github.com/webpack/webpack.js.org/blob/master/.github/dependabot.yml.

**Comment by montogeek** [comment]
Let's wait for confirmation about the legal side of it.

**Comment by snitin315** [comment]
> > We ignore CLA for dependabot in webpack and webpack-cli repo
> 
> It is that ok from the JS Organization perspective?

I'm not sure about it. 

/cc @sokra @alexander-akait

**Comment by sokra** [comment]
You can ignore CLA for bots.

In the webpack/webpack repo we use the webpack-bot to override the CLA check so merging is not blocked by that.

**Pull request merged**
