### PR TITLE
Add missing config options to cli.md

### PR DESCRIPTION
**Pull request by joshunger**
Add missing config options to cli.md.  I executed a `webpack --help` and then copied the information into this md.  I wish this was automatic eh?

image

### CODE REVIEW

**Comment by TheDutchCoder** [comment]
@joshunger Thanks for this!

Do you happen to know if this is a v4 or v3 thing?

**Comment by joshunger** [comment]
@TheDutchCoder v4 see https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

**Comment by TheDutchCoder** [comment]
Alright, I'll PR it against the `next` branch then ;)

**Comment by joshunger** [comment]
Thanks @TheDutchCoder 👌

**Comment by TheDutchCoder** [comment]
My pleasure!

**Pull request merged**
