### PR TITLE
chore: add package-lock to gitignore, add note about yarn

### PR DESCRIPTION
**Pull request by byzyk**
as per comments in #2250

### CODE REVIEW

**Comment by byzyk** [comment]
Having both `yarn.lock` and `package-lock.json` is not a good practice. In addition, we're disabling it in core repo as well.

**Comment by byzyk** [comment]
@montogeek let me know please if there is anything else pending to get this one merged?

**Comment by montogeek** [comment]
Thanks!

**Comment by montogeek** [comment]
Please avoid merging master constantly, this repo changes quickly and every merge is wasting our limited CI time.

**Comment by byzyk** [comment]
Sure, noted 👍🏽

Btw, a few days ago I noticed the same CI error, seems the requests are still not authenticated. Do you want me to have a look at it?

**Comment by montogeek** [comment]
@byzyk Yeah, no idea :/

**Pull request merged**
