### PR TITLE
feat(site) Add v3 docs to deployment

### PR DESCRIPTION
**Pull request by montogeek**
Added v3 docs to deploy script by git checking `fix/v3-docs` branch which have necessary changes to make site works under a subfolder and also last v3 docs.

### CODE REVIEW

**Comment by montogeek** [comment]
@jeremenichelli Could you please review this one?

**Comment by montogeek** [comment]
@sokra `gh-pages` command doesn't support excluding directories.
My changes only apply to deployment, PRs and other branches only run `build` and `test`.

There is no other output for v3 docs, they have to be build from `fix/v3-docs` branch, which contains specific changes to make website work in a subfolder.

I already tried to preserve previous files https://github.com/webpack/webpack.js.org/pull/1972, but it won't work because any our file names doesn't change, if we add new docs to a page they won't be updated.

**Comment by kirkholloway** [comment]
Could be good to take @sokra's suggestion by creating a `webpack-3` branch off the `3.11.0` tag. I'd do so myself but I don't have permissions to create a branch.
Then you could modify this build to create `v3/` on merge into `webpack-3`

**Comment by JaKXz** [comment]
Is there anything I can do to help get this merged?

**Comment by JaKXz** [comment]
Would it be possible to merge this as a temporary measure while the infrastructure for v3 is figured out?

**Pull request closed without merging**
