### PR TITLE
fix unclickable links under gitter button container

### LINKED ISSUE #2958: Unclickable anchors under gitter button container
Because of the way the gitter button container is positioned and built (spanning vertically over the whole viewport), it's making all the content under it inaccessible, including unclickable anchors bellow that region.
Screenshot_20190419_144136_marked

### PR DESCRIPTION
**Pull request by 2alin**
Fixes #2958

### CODE REVIEW

**Comment by 2alin** [comment]
There's also an alternative fix:
```diff
.gitter {
- right: 1.5em;
+ right: calc(1.5em + 3em);
+ width: 0;
}
```

**Comment by EugeneHlushko** [comment]
How about we go with position fixed and height 48 for the button?

**Comment by pranshuchittora** [comment]
What about this :point_down: 
```css
.gitter {
    position: fixed;
    right: 1.5em;
    bottom: 3em;
}
```
Screenshot from 2019-04-22 21-16-22

**Comment by EugeneHlushko** [comment]
Yeah, need to make sure it doesnt cover the footer when scrolled to the bottom ty @pranshuchittora 
Please try your updates on mobile, tablet and desktop resolutions before re-requesting a review @2alin

**Comment by 2alin** [comment]
@EugeneHlushko @pranshuchittora The problem of going with 'fixed' position is that you end up with the gitter button relative to the right side of the **document** and not the right side of the **site content** as it was implemented originally, i.e., gitter button ends up all the way to the right side in an empty space far from the content.

Screenshot_20190422_132843

**Comment by 2alin** [comment]
@EugeneHlushko My updates doesn't change the way gitter button is positioned previously so it shouldn't have any problem with any resolution. It only gives a 'transparency' click effect to the content under such div container that is not the button.

**Comment by pranshuchittora** [comment]
@2alin IMO the new position of Gitter btn looks good. As it doesn't interfere with the content & provides a better UX.
Let's see what others think about this.

And @2alin pls sign the CLA in order to successfully merge these changes.

**Comment by 2alin** [comment]
@pranshuchittora well, if having the position far from the content is okay, then 'fixed' would be the way to go. What do you think? @EugeneHlushko 

And I already signed up the CLA when I opened this PR.

**Comment by montogeek** [comment]
It should be aligned to the content.

**Comment by EugeneHlushko** [comment]
Looking at the website in different resolutions i cannot say it looks worse or better, why do you want it aligned when there is space to have it on the edge right @montogeek ?

**Comment by montogeek** [comment]
It was just added at that position, there was not discussion https://github.com/webpack/webpack.js.org/pull/816 about its position.

I would say that it is fine to moved it to the bottom right of the page :)

**Comment by EugeneHlushko** [comment]
ok in that case please apply the fixed position fix as suggested above @2alin

**Comment by 2alin** [comment]
Done, I went  with @pranshuchittora code.

**Comment by montogeek** [comment]
Nice bot, thanks @EugeneHlushko

**Comment by EugeneHlushko** [comment]
Well done

**Comment by EugeneHlushko** [comment]
Thanks!

**Comment by 2alin** [comment]
Thank you all for the review :)

**Comment by pranshuchittora** [comment]
Awesome 👏

**Pull request merged**
