### PR TITLE
fix(dev-server): delete lazy and filename options

### PR DESCRIPTION
**Pull request by hiroppy**
**Don't merge.**

Delete lazy and filename options because webpack-dev-middleware won't support them.

Related PR: https://github.com/webpack/webpack-dev-server/pull/2544

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].

### CODE REVIEW

**Review by EugeneHlushko — APPROVED** [review]

**Comment by EugeneHlushko** [comment]
@hiroppy its been in "do not merge" for a while now, any updates? :)

**Comment by evilebottnawi** [comment]
@EugeneHlushko We should merge it after `v4` release

**Review by sokra — APPROVED** [review]

**Comment by evilebottnawi** [comment]
On hold

**Comment by chenxsan** [comment]
Closed via https://github.com/webpack/webpack.js.org/pull/4950

**Pull request closed without merging**
