### PR TITLE
docs(configuration): sort other-options alphabetically

### PR DESCRIPTION
**Pull request by snitin315**
sort `other-options` alphabetically

### CODE REVIEW

**Comment by chenxsan** [comment]
It would be painful for the downstream repositories (Chinese translation and korean translation) to sync large changes. That's why I sorted just two or three options in one pull request. So if you are going to do it, I would suggest doing it with small changes maybe every other week because the downstream won't sync that quickly.

**Comment by snitin315** [comment]
I just moved `infrastructureLogging` and `name` up but it seems Github is showing like I moved other options down. 

>So if you are going to do it, I would suggest doing it with small changes maybe every other week because the downstream won't sync that quickly.

I get your point here I will keep this in mind in the future, do I need to update this PR with fewer changes?

**Comment by chenxsan** [comment]
I think we can move just one option in one commit, like this one https://github.com/webpack/webpack.js.org/pull/5187/commits. Also prefer to use semantic commit messages so the downstream can follow it easily.

**Comment by alexander-akait** [comment]
Sometimes I think moving `infrastructureLogging` on own page with example will be great idea, because logging is main for many developers

**Comment by snitin315** [comment]
> Sometimes I think moving `infrastructureLogging` on own page with example will be great idea, because logging is main for many developers

Makes sense to me 👍🏻

**Comment by chenxsan** [comment]
So maybe sort these three as well considering the whole changes are already a lot?

**Review by chenxsan — APPROVED** [review]

**Pull request merged**
