### PR TITLE
Add missing div tag with an id "div" in index.html

### PR DESCRIPTION
**Pull request by mubarak-basha**
Add missing div tag with an id value of "div" in index.html code.

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by montogeek** [comment]
Why it is missing?

**Comment by mubarak-basha** [comment]
@montogeek I am sorry I don't understand what you are trying to ask

**Comment by mubarak-basha** [comment]
It is missing because the JavaScript code reference an element with and id of value.
If you follow along the guide it will build successfully but, when you run the index.html page in browser you can see that it throws cannot set property of innerHTML of null error in browser console.

**Comment by montogeek** [comment]
The JS is creating it and append it to the body:
```js
function component() {
  const element = document.createElement('div');

  // Lodash, currently included via a script, is required for this line to work
  element.innerHTML = _.join(['Hello', 'webpack'], ' ');

  return element;
}

document.body.appendChild(component());
```

There is not need to add the HTML tag.

**Comment by mubarak-basha** [comment]
My bad. I misunderstood createElement as getElementById

**Pull request closed without merging**
