### PR TITLE
Update hmr-react.md

### PR DESCRIPTION
**Pull request by sararubin**
Add note about using es6 modules with webpack 2 tree-shaking

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Could you sign the CLA?

**Comment by bebraw** [comment]
Can you rebase against `master`? The development happens against it now (faster deployments).

**Comment by sararubin** [comment]
signed SLA and rebased against master @bebraw @SpaceK33z

**Comment by bebraw** [comment]
Thanks. 👍

**Pull request merged**
