### PR TITLE
chore(rebuild): re-incorporate header links

### PR DESCRIPTION
**Pull request by montogeek**
Src code patched until
https://github.com/ben-eb/remark-autolink-headings/pull/41 is merged, if
ever, we should probably use a fork.

### CODE REVIEW

**Comment by wooorm** [comment]
Ohh, seems Ben isn’t very active in remark anymore. Let me see and check in with him if he’s interested in moving it to @remarkjs

**Comment by skipjack** [comment]
@montogeek not seeing any links pop up in the `h*` elements... do I need to install the package from that fork in order for it to work?

**Comment by skipjack** [comment]
Nvm used @rigor789's fork, `@rigor789/remark-autolink-headings`, which works. Cleaning up the styling slightly and then pushing/merging and knocking another one down 🎉. Thanks for digging into this @montogeek.

**Comment by montogeek** [comment]
@skipjack Yep, I patched it locally applying same changes as that fork

**Pull request merged**
