### PR TITLE
add math.js highlight (+) in project tree

### PR DESCRIPTION
**Pull request by HamidTanhaei**
math.js highlighted (+) in project tree

### CODE REVIEW

**Comment by montogeek** [comment]
@HamidTanhaei Could you please sign CLA to merge your change?

**Comment by skipjack** [comment]
@HamidTanhaei ping! We wanna merge but can't __if you don't sign the CLA__.

**Comment by TheDutchCoder** [comment]
@HamidTanhaei Can you please sign the CLA so we can merge this in?

**Comment by montogeek** [comment]
Friendly ping @HamidTanhaei pong

**Comment by montogeek** [comment]
https://github.com/webpack/webpack.js.org/pull/1914 was merged in favour of this PR giving that a lot of time passed.

**Pull request closed without merging**
