### PR TITLE
docs: correct grammar

### PR DESCRIPTION
**Pull request by wizardofhogwarts**
Continues #2785

### CODE REVIEW

**Comment by wizardofhogwarts** [comment]
@EugeneHlushko  @montogeek

**Comment by montogeek** [comment]
I like to leave the previous commits, for respect to its authors.

**Comment by wizardofhogwarts** [comment]
How to add those commits then?

**Comment by montogeek** [comment]
By creating a branch from the authors branch

**Comment by EugeneHlushko** [comment]
Yup you can cheery pick from fork, here is a good ref: https://gist.github.com/bhumphrey/3764983

**Comment by montogeek** [comment]
@wizardofhogwarts Friendly ping

**Comment by jamesgeorge007** [comment]
Taking this up :raised_hands:

**Comment by EugeneHlushko** [comment]
Stalled, alternative was merged, closing

**Pull request closed without merging**
