### PR TITLE
Minor corrections

### PR DESCRIPTION
**Pull request by skipjack**
Minor grammar and formatting fixes.

Includes fixes for:

#800 
#649

### CODE REVIEW

**Comment by rouzbeh84** [comment]
@skipjack / @simon04 i effed this one up with a very untimely trackpad tap 😬. I have a local copy of this branch with [57ea4a5](https://github.com/webpack/webpack.js.org/pull/1172/commits/57ea4a54a72d0a0c74e2885052431f84aeb2b865) removed but daren't `git push branch -f` without approval if at all. My apologies but let me know what you'd like to do here and I'll take care of it.

**Comment by skipjack** [comment]
@rouzbeh84 no worries, I can clean that up before it gets merged (or we can leave it, a master merge shouldn't hurt anything)

**Comment by rouzbeh84** [comment]
Sounds good to let it ride I guess then. Wasn't sure how y'all like to handle this being a bit newer to the collab role. If there are guidelines outside of 'dont do this' and generally accepted git best practices I'd love to see them 👍

**Comment by skipjack** [comment]
@rouzbeh84 can you review and merge (if all is good) when you have a chance?

**Comment by skipjack** [comment]
Awesome, thanks @rouzbeh84!

**Pull request merged**
