### PR TITLE
fix(plugins): Fix SplitChunksPlugin cacheGroup priority option

### PR DESCRIPTION
**Pull request by butsalt**
`priority` option should belong to `cacheGroups.{cacheGroup}`, should not belong to `cacheGroups`

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
@butsalt please sign CLA

**Comment by butsalt** [comment]
@EugeneHlushko Weird, I have signed CLA yesterday.

**Comment by butsalt** [comment]
Or please try ['Recheck PRS'](https://github.com/cla-assistant/cla-assistant/issues/124).

**Comment by anshumanv** [comment]
IIRC there was one more issue earlier, can we try reopening this PR?

**Comment by butsalt** [comment]
So what else I can do? :)

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
