### PR TITLE
Info Architecture

### LINKED ISSUE #1519: Dev - Information Architecture
> Summing up the key points from #438...

As we continue our work on #1258, #1386, and the others mentioned in #1380, we can, and have already, started talking about better ways to group, consolidate, and improve the flow of pages within this site. This should be started by simply sorting the pages within each section, but, once we've done that, we could likely group sections within the sidebar (as suggested by @pastelsky in #438) or add another layer of navigation.

Here's the checklist of TODOs:

- [ ] Sort all existing pages in an intuitive way (already done for guides, see #1258)
- [ ] _Support_, _Development_, and maybe sponsors/backers => _Contribute_ (#1365)
- [ ] _CLI_ nav link should be removed (it will instead just be found under _API_)
- [ ] The articles should then be organized via nested directories or a `group` field.
- [ ] Top level pages should use a wider layout (e.g. #1367)

Certain infrastructure changes should make some of this much easier. Specifically the fact that in newer versions of Antwar as well as in Phenomic and Gatsby -- routing is automatically synchronized/based on the structure of the `/content` directory. This means far less configuration and a more intuitive repository. This has already been started in #980 with some antwar/webpack updates.

See the proposed nesting levels in [this comment](https://github.com/webpack/webpack.js.org/issues/438#issuecomment-282508376). As mentioned above, a `group` field in the YAML frontmatter would also help us achieve this but wouldn't be reflected in the routing structure.

### PR DESCRIPTION
**Pull request by skipjack**
Tighten up page organization and sorting as discussed in #1519. This PR should resolve the following items:

- [x] Sort all existing pages in an intuitive way (already done for guides, see #1258).
- [x] _Support_, _Development_, and maybe sponsors/backers => _Contribute_ (#1365).
- [x] _CLI_ nav link should be removed (it will instead just be found under _API_).
- [x] The articles should then be organized via nested directories or a `group` field.
- [ ] Top level pages should use a wider layout (e.g. #1367).

The last one I may leave out as the stranded pages are a bit more joined together after #980. Hopefully once this is done, the content will be more usable, the structure more intuitive, and new features like `group` available for contributors and package maintainers. One thing we need to remember prior to merging this is:

- [x] Add redirects for all broken routes.

This should put us in a good place to continue pushing some of the other dev cleanup discussed in #1525 forward, however it would be great if some folks could help with the remaining content related issues (most of which are related to improving or fixing issues in the _API_ section).

Resolves #1519

### CODE REVIEW

**Comment by skipjack** [comment]
@pierreneter @jeremenichelli working on the last couple things right now and then all that will be left is to add redirects. Was hoping to get #1582 in before this one but I'm not sure it'll happen. At the very least I'll use it to test locally before merging.

Anyway, let me know your thoughts on the updated design and consolidated sections. I can share some screenshots as well if that would be helpful.

**Comment by jeremenichelli** [comment]
Wow! Great work @skipjack, I will download the branch and give it a test locally to see the changes. At first glance I liked the gardening you've done in the code.

**Comment by skipjack** [comment]
@jeremenichelli thanks, yeah definitely let me know your thoughts once you've tested locally.

@sokra @TheLarkInn I'd like to get this merged this weekend if possible, here's a quick screencast to give you an idea of how the structure is changed:



I still have a little more work to do in the _API_ section (particularly on the index page) but aside from that I see this as ready to ship.

**Comment by jeremenichelli** [comment]
@skipjack just went through all the files changed and the content updates look great, though I couldn't test locally due to errors on fetching some files, when this didn't happen server just didn't show the url to access locally to the site.

I don't know if this might be a local issue or some problem around the build process of the site. We should start doing fresh install and test this in my opinion. Regarding the changes in this PR, I approve them.

**Comment by skipjack** [comment]
> Regarding the changes in this PR, I approve them.

Great, I'm going to ping some others to see if we can get some more eyes but I'm planning to merge by tomorrow or monday at the latest.

> ... I don't know if this might be a local issue or some problem around the build process of the site. We should start doing fresh install and test this in my opinion.

Could you share the error you're seeing? Maybe a there's an issue with the Node version or something. The CI build does do a fresh install, build, and runs the tests... are you referring to refactoring the npm `scripts` or something?

**Comment by TheLarkInn** [comment]
What I see I love. I'll try and review the code today also.

**Comment by skipjack** [comment]
@TheLarkInn great -- more curious about your view on the tightening up of the content structure but happy to get more feedback on the code changes as well.

**Comment by pierreneter** [comment]
The content is too close to the left bar.
capture

**Comment by rouzbeh84** [comment]
Here's a quick pull to try and resolve the content/edge issue reference by @pierreneter https://github.com/webpack/webpack.js.org/pull/1626.  I thought this would be a quick fix without having the content itself be reviewed again by adjusting padding for both sidebar/content as i mention in the PR itself

**Comment by skipjack** [comment]
@rouzbeh84 thanks for that fix, I was thinking something similar when I saw @pierreneter's comment. I could also just add that left padding back but this is only a problem if:

1. The sidebar is expanded enough to where it needs scrolling.
2. The user is on a browser which doesn't use semi-hidden overlay scrollbars by default.

@pierreneter what browser are you using and does @rouzbeh84's styling tweak help?

I've been busy the last few days but I'm going to try to wrap up this PR and #1582 tonight.

**Comment by skipjack** [comment]
Ok I finished the final content edits (cleaner `/api` index page) and adding redirects for broken routes. Unfortunately #1582 still has some issues but I did test with `hyperlink` locally and will continue to work on resolving that issue with @Munter. The only broken links are the `.../edit/...` ones which are to be expected since some of these files don't exist on master yet.

I'm going to wait until tomorrow night (EST) to merge so we can figure out the minor scrollbar issue. If anyone has any other feedback, please let me know before then.

**Comment by rouzbeh84** [comment]
@skipjack is there anywhere you'd like me to look re:

> The sidebar is expanded enough to where it needs scrolling.
> The user is on a browser which doesn't use semi-hidden overlay scrollbars by default.

here is a screen of chrome/ff (respectively):

screenshots posted on #1626 to not clutter this PR any further

**Pull request merged**
