### PR TITLE
/loaders: add index of important loaders

### PR DESCRIPTION
**Pull request by simon04**
* Move all loader documentation to /concepts/loaders
* List various loaders at /loaders, partially based on https://github.com/webpack/webpack/blob/2ed6448/README.md#loaders

### CODE REVIEW

**Comment by bebraw** [comment]
I wonder what to do with those license links. I guess we should resolve them to the packages somehow as now it's trying to look up against the site itself.

**Comment by simon04** [comment]
The idea of those [license links/checks](https://travis-ci.org/webpack/webpack.js.org/builds/198179476#L678-L716) is to make sure that the included content is under a compatible license?

**Comment by bebraw** [comment]
The links are broken in npm too due to the way they have been written. I guess the best fix would be to fix the links at each package for this reason rather than work around here.

**Comment by simon04** [comment]
Hopefully those PRs will be merged quickly :smile:

**Comment by bebraw** [comment]
@simon04 Merged.

**Comment by simon04** [comment]
Thank you! Now the Travis build succeeds.

**Pull request merged**
