### PR TITLE
fix(site): Improve loaders parsing of external link in headers

### PR DESCRIPTION
**Pull request by budmc29**
Improve the way external links (like licences) in headers are parsed and generated on the website.

Before:
image

After (the link will act as expected and point the user to the document etc):
image

This issue is encountered in multiple loaders pages (and possibly in other pages as well), but here's one example:
https://webpack.js.org/loaders/worker-loader/

### CODE REVIEW

**Comment by montogeek** [comment]
It is broken as well, but in a different way:
image

**Comment by montogeek** [comment]
@budmc29 We are in an effort to modernize this repo infrastructure, our work is in the `rebuild` branch, Could you please fix the issue on that branch? Thanks

**Comment by budmc29** [comment]
Yes, I can have a look at that, should we close this?

**Comment by montogeek** [comment]
It was fixed by: https://github.com/webpack/webpack.js.org/pull/2453, I didn't have latest `rebuild` changes when taking the screenshot.

Although I am not sure if it is good to link the RAW file, it should link to the rendered markdown:
`https://github.com/webpack-contrib/worker-loader/blob/master/.github/CONTRIBUTING.md`
instead of
`https://raw.githubusercontent.com/webpack-contrib/worker-loader/master/.github/CONTRIBUTING.md`

What do you think @Munter ?

**Comment by Munter** [comment]
@montogeek It does sound like a nicer experience to go the the Github UI for the markdown files. The problem is that the url we get in `options.source` is on `raw.githubusercontent.com`, and all relative links are resolved from the source URL. I don't know if there is a safe way to make that URL transformation. There's quite a few edge cases I had to cover to fix all the errors I found. And those links are mostly part of the external hyperlink check, so you'd have to manually inspect the output of that run to ensure everything still works

**Comment by montogeek** [comment]
@Munter I can take a look, or do you want to do it @budmc29 ?

**Comment by budmc29** [comment]
@montogeek I'd like to give it a try and see how it goes, and open another PR.

We can close this for now since it's not relevant anymore.

Thanks

**Pull request closed without merging**
