### PR TITLE
docs(config) remove serve option

### LINKED ISSUE #3565: Document webpack change: improve schema and validation
*A pull request by @sokra was merged and maintainers requested a documentation change.*

See pull request: https://github.com/webpack/webpack/pull/10406

---

* remove serve property from options
* Add "did you mean" to schema validation for common errors

**What kind of change does this PR introduce?**
feature, removal

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
yes

**What needs to be documented once your changes are merged?**
`serve` property do no longer exist in configuration

### PR DESCRIPTION
**Pull request by EugeneHlushko**
- remove `serve` option from configuration
- Closes #3565

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
@anikethsaha i thought you've added it to migration guide

**Comment by anikethsaha** [comment]
> @anikethsaha i thought you've added it to migration guide

No, actually I added them in the `configuration` section with a new page name `serve.md` and I think that was not a correct section to add upon. I think this is fine place to add. just a note would be good about the removal of the options

**Comment by EugeneHlushko** [comment]
I meant second PR, now i realize its changelog repo. Ill duplicate here

**Comment by anikethsaha** [comment]
> Ill duplicate here

yeah...that will work too 👍

**Comment by EugeneHlushko** [comment]
Thanks for spotting, was sure it was migration guide 👍

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
