### PR TITLE
Branding Page

### PR DESCRIPTION
**Pull request by skipjack**
Still a WIP

Adding a branding page for easy downloading of webpack [design assets](/webpack/media) and updating the Navigation component to better display the growing number of sections/pages. See #297 for the related discussion.

- [x] Update assets directory
- [x] Update dependent components
- [x] Add branding page
- [x] Add a branding link to the Navigation or Footer component

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Cool. Tested it, and on a "normal" screen (retina looks fine) the logo at the top left has some rough edges:

webpack

I don't know where these rough edges around the cube come from and if it's fixable?

The branding page looks good :).

Maybe run [`svgo`](https://github.com/svg/svgo) on the svgs to remove some unnecessary bytes?

**Comment by skipjack** [comment]
@SpaceK33z yea I see that as well, I'll play around with it. It seems odd that a vector would render that way.

**Comment by skipjack** [comment]
@SpaceK33z haven't found a solution to the rough edges yet although I did add a link to the branding page in the footer. 

I think once you review again we should just get this merged since you said it's somewhat time sensitive. I started working on the Navigation a bit but realized it's going to lead to some other more serious organizational changes which I think should be pushed to another PR. I can continue looking into what's going on with the svgs over there as well.

Funny thing for me is I only see those rough edges on my external monitor, on my macbook display it looks sharp.

**Comment by SpaceK33z** [comment]
Allright merging. I'm looking with @indri-indri if we can fix the logo.

**Pull request merged**
