### PR TITLE
Feature/watch built size

### PR DESCRIPTION
**Pull request by chenxsan**
`bundlesize` seems to be [unmaintained now](https://github.com/siddharthkp/bundlesize/graphs/contributors), thus we're going to replace it with [`size-limit`](https://github.com/ai/size-limit). There're many alternatives https://github.com/GoogleChrome/lighthouse/issues/10472 but I think `size-limit` fits our usage quite good as the [github action it provides](https://github.com/andresz1/size-limit-action) requires very few configurations.

### CODE REVIEW

**Comment by chenxsan** [comment]
`size-limit` needs to be run for twice to compare the results, one for pull request, one for master branch. Which means we might hit the API limit again.

**Comment by montogeek** [comment]
Where can we see how the bundle changed?

**Comment by chenxsan** [comment]
No, you can't. I've removed it because the action can't be applied on forked pull requests which render it useless.

**Comment by montogeek** [comment]
Yeah, saw it later :(

**Pull request merged**
