### PR TITLE
mention defaults in config example

### PR DESCRIPTION
**Pull request by pravdomil**
see diff

### CODE REVIEW

**Comment by pravdomil** [comment]
https://github.com/webpack/webpack/pull/6140/files#diff-7473dd12403a310ad8cf18d0ab9f10b9R20

**Comment by montogeek** [comment]
Yes, it is still going to fail if `index.js` doesn't exists

**Comment by pravdomil** [comment]
if you want to have it `src/index.js` change webpack code first

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
