### PR TITLE
Search Interface

### PR DESCRIPTION
**Pull request by skipjack**
cc @bebraw @dzello

Still a WIP, adding the interface bits for search:
- [x] Add a togglable search bar in the Navigation
- [x] Handle focus for usability
- [x] Trigger a search event on keying for other components to hook into
- [x] Add a SearchResults component to fetch and display results
- [x] Polyfill [CustomEvent](https://github.com/webmodules/custom-event) for crossbrowser-support
- [x] Handle other events for closing and hiding the search bar and results

Still need to add another search bar in SidebarMobile for searching on screens under 768px, but we should probably take it one step at a time and first merge this so someone else can start playing around with actually displaying search results (see #184).

I'll add some gifs tonight...

### CODE REVIEW

**Comment by skipjack** [comment]
Here's a preview that demos toggling, typing in, and tabbing into the search bar:

**Comment by SpaceK33z** [comment]
@skipjack, do you think it would be useful if I test this out on some devices / browsers, or is this too early?

**Comment by skipjack** [comment]
@SpaceK33z you'd be more than welcome to test it out, however I haven't added a mobile version yet so the only devices that you might test on would be tablets (anything >= 768px width).

Initially I was planning to use the the same search bar in the nav for mobile devices as well but after trying it out and seeing the lack of screen real estate, I'm thinking it would be better to add a separate search field at the top of SidebarMobile. 

What I'm hoping is that whoever has experience with Algolia (or whichever lib we choose) and has the indexed data will jump in here at SearchResults._handleSearch...

```js
  _handleSearch(e) {
    let { text = '' } = e.detail;

    if (text.length) {
      if (!this.state.visible) this.setState({ visible: true });
      // TODO: Get search results

    } else this.setState({ visible: false });
  }
```

to start fetching and displaying results.

**Comment by SpaceK33z** [comment]
Okay, I tested it:

- After a click on the search icon, it would be nice if the text input would be focused immediately. I'd expect to be able to type immediately after clicking.
- The search icon is a `<span>` now, but for accessibility reasons you should use `<button type="button">` here. This also fixes the small issue that if you click twice quickly, the browser "selects" the icon as a text.

**Comment by skipjack** [comment]
@SpaceK33z thanks for reviewing, I'll fix both those things. I'll let you know when this is ready for another pass.

**Comment by skipjack** [comment]
@SpaceK33z done, let me know if there's anything else.

**Comment by dzello** [comment]
Lookin' good! I've got the indexing built and the search results connected, here's a preview:

search results

I'm attaching our DocSearch event in the `componentDidMount` of `navigation.jsx` which seems to be working well for now. I didn't need to hook into the search results component because the DocSearch library already knows how to handle keystrokes and a results modal. But I left all the plumbing in so that we can chat about it and make sure the integration does exactly what we want.

My instinct is to put that in a different PR since we can deal with it separately, but let me know if you'd rather I add the commits here.

**Comment by skipjack** [comment]
@dzello awesome, the screenshot looks great! I had a few reasons for separate SearchResults component:

1. Modularizing any custom styling or layout so as to not complicate the Navigation component.
2. It allows us to re-use it in multiple places, for example in the SidebarMobile component when searching on smaller screens (for which I haven't added anything yet).

With that said, I'm not too familiar with Algolia so I think we should just get something up and running (as it looks like you already have) and then continue to play around with it. Based off what you said, it seems Algolia comes with some built-in styling of results? Or is that layout custom?

> My instinct is to put that in a different PR since we can deal with it separately, but let me know if you'd rather I add the commits here.

Agree completely, I was just giving this another day or two to simmer in case anyone else wanted to test/review. Merging now... feel free to continue the conversation here or on your PR 👍

**Comment by dzello** [comment]
The styling is the default for the [DocSearch project](https://community.algolia.com/) but we'll be able to [customize it](https://github.com/algolia/docsearch#customization) by adding CSS selectors and get a really nice, consistent look. PR coming soon.

**Comment by sokra** [comment]
👍 The search is pretty nice.

**Pull request merged**
