### PR TITLE
Fixed minor typo in modules.md

### PR DESCRIPTION
**Pull request by HippoDippo**
Fixed a small typo where the beginning of the sentence was missing a capital letter.

### CODE REVIEW

**Comment by skipjack** [comment]
As per the [branding guidelines](https://github.com/webpack/media#name), "webpack ..." is actually correct. I do understand that it takes some getting used to at the beginning of sentences though. Thanks anyway for your submission.

**Comment by HippoDippo** [comment]
Ohh sorry. Got too eager.

**Comment by skipjack** [comment]
No worries, if you're still interested in contributing I could point you to a issue or two that we would love some help on.

**Comment by HippoDippo** [comment]
Yeah that would be awesome!

**Comment by skipjack** [comment]
Take a look at #1801 or #1796. Comment there if you have any questions or want to discuss an approach to resolve the issue. I'm not sure what your skill level is with webpack but the other open ones are a little more advanced (and some of the dev-related ones we're already working on). If the two I suggested don't work for you, feel free to comment on another that you'd like to pick up.

Thanks for your help!

**Comment by HippoDippo** [comment]
I am still learning, but will help out where i can! And as i grow more and more familiar with webpack, the more i will help! And anytime!

**Comment by HippoDippo** [comment]
Exceptional job on the site and docs by the way!

**Pull request closed without merging**
