### PR TITLE
docs(guides): Make all demo context consistently

### PR DESCRIPTION
**Pull request by Ivocin**
I read the guides and find that some demos aren't consistent.
This pr contains three parts:
-  #2409 change var to let in `index.js` file
-  #2845 change CleanWebpackPlugin arguments usage in `webpack.config.js` file
-  delete extra part in `package.json` to avoid changing the dependency vesion （now the webpack in `package.json` version is `^3.0.0`)

### CODE REVIEW

**Comment by RedTn** [comment]
@Ivocin @EugeneHlushko What's status on this? Ran into bug with CleanWebpackPlugin on production guide and this PR resolves it. Need my help to take it over?

**Comment by EugeneHlushko** [comment]
@Ivocin can you resolve conflicts? an earlier pr to let const was merged

**Comment by Ivocin** [comment]
> @Ivocin can you resolve conflicts? an earlier pr to let const was merged

Close, another pr has been merged.

**Comment by EugeneHlushko** [comment]
@Ivocin can you quickly open a new PR where you do changes for CleanWebpackPlugin from this pr's diff ?

**Comment by RedTn** [comment]
I can take it if he's unavailable

**Comment by EugeneHlushko** [comment]
Hi and thank you @RedTn but i already have a branch with such changes, just wanted to get original contributor to respond first

**Comment by EugeneHlushko** [comment]
Updated the branch and pushed the changes.

**Pull request closed without merging**
