### PR TITLE
docs(format) single quotes in js spotted, minor grammar

### PR DESCRIPTION
**Pull request by EugeneHlushko**
While reviewing recent PR i spotted mis- formatting on api pages, just cleared the occurrences and found another grammar improvement

### CODE REVIEW

**Comment by anikethsaha** [comment]
can we add `.vscode` config to work with eslint and prettier and remove it from `.gitignore` ?

**Comment by anshumanv** [comment]
> can we add .vscode config to work with eslint and prettier and remove it from .gitignore ?

I don't think that's a good idea given not everyone uses the same lint/format config. Having a single config in the project should be sufficient.

**Comment by anikethsaha** [comment]
> I don't think that's a good idea given not everyone uses the same lint/format config. Having a single config in the project should be sufficient.

I think vscode wont look for global config if `.vscode` is present in the project. so in that way, we all will be using same vscode config and wont get formatting issues.
just that we need to configure prettier well with linters in the project config,

**Comment by EugeneHlushko** [comment]
Yes linter should've caught this but its tricky in .md and .mdx files in different snippets. Therefore possible inconsistencies. Keep eye out for them since all the PRs require review

**Comment by anikethsaha** [comment]
eslint + prettier works like a charm 🚀 

> its tricky in .md and .mdx files in different snippets.

Yea, this might be an issue, but there is an [`eslint plugin for mdx`](https://github.com/mdx-js/eslint-mdx) and for [`.md`](https://github.com/eslint/eslint-plugin-markdown)  but there is no rules and support for `.mdx` from `markdownlint`'s side. 

So if we are considering consistent formatting using prettier, then I think we may need to remove `markdownlint` and use` eslint-plugin-markdown` and `eslint-mdx` instead. 

Even removing `markdownlint` right now isnt a good idea either 


>  Keep eye out for them since all the PRs require review

Yes .

**Comment by EugeneHlushko** [comment]
Another thing is that there might be a need for double quotes in those files e.g. JSON and regular quotes in plain text, so yeah its tricky

**Pull request merged**
