### PR TITLE
Update mode.md

### PR DESCRIPTION
**Pull request by Legends**
Added possible values for mode at the beginning.
Replaced `provides` with `sets`, sounds better imo.

### CODE REVIEW

**Comment by montogeek** [comment]
@Legends Your fork is gone, we can't merge it :(

**Comment by montogeek** [comment]
@Legends Yes please

**Comment by Legends** [comment]
@montogeek Just wanted to commit my local changes to the forked repo, but I get:

image

**Comment by Legends** [comment]
Didn't know how to exclude the modified `package.json`...
Therefore I've edited the file in the repo directly.

--> New PR is [here](https://github.com/webpack/webpack.js.org/pull/2340)

**Pull request closed without merging**
