### PR TITLE
add multiple language selection

### PR DESCRIPTION
**Pull request by lcxfs1991**
Preview:

language-webpack

Fixes #1148

### CODE REVIEW

**Comment by lcxfs1991** [comment]
@bebraw Please take a look

**Comment by skipjack** [comment]
@bebraw @sokra @TheLarkInn @lcxfs1991 also, from a higher level, how does internationalization play out in terms of issue management, prs, etc?

I know right now there's a `translation` branch in this repo and there's been some talk of using locki, #295, but I'm not sure where we're at with that. It seems there's [a separate repo](https://github.com/webpack-china/webpack.js.org) for the chinese fork (which I think makes sense for management purposes) but then what's the local `translation` branch for?

**Comment by lcxfs1991** [comment]
Local translation branch is for a separate management just like webpack-china since we have to fetch plugin/loader readme and put them under `/content/` folder. However, the master branch generate directly. It is a bit hard for us to make a diff if we simply follow what master do.

I think we can try locki. But we need to ensure the performance and we'd better keep a local copy of data.

**Comment by skipjack** [comment]
@lcxfs1991 ah ok thanks for the clarification, I did see something about that in #722 I think. In terms of the getting this PR merged please see my comments.

@bebraw any reason we can't just keep that change in the master branch? I actually kind of like having all site content, including fetched content, in the `/content` directory. Is this to keep a visual distinction for contributors so they know not to edit it?

**Comment by lcxfs1991** [comment]
Let me fix this tonight.

**Comment by skipjack** [comment]
Ok great, no rush.

**Comment by lcxfs1991** [comment]
width: 768

width: 1024

hover: 
language

**Comment by skipjack** [comment]
@lcxfs1991 awesome work, I will review again (and hopefully merge) shortly!

**Pull request merged**
