### PR TITLE
docs(guides): Add minimum Node version

### PR DESCRIPTION
**Pull request by TheDutchCoder**
Adds a warning to use Node 6+ to run the site locally (`Running the Site`), as otherwise `npm start` will fail.

### CODE REVIEW

**Comment by simon04** [comment]
We have some duplication on how to run the project:
* https://github.com/webpack/webpack.js.org#contributing
* https://github.com/webpack/webpack.js.org/blob/master/.github/CONTRIBUTING.md#setup
* https://github.com/webpack/webpack.js.org/blob/master/content/writers-guide.md#running-the-site

Can we reduce the number of occurrences? To my understanding, writers-guide.md should focus on the content and the technical part on how to build/dev-start the page should be somewhere else.

**Comment by TheDutchCoder** [comment]
@simon04 I think that's a good idea, we could reference it from this doc anyway (just a link).

Do you want me to take this section out instead?

**Comment by simon04** [comment]
@TheDutchCoder I'd remove the "Running the Site" section from writers-guide.md, but I'm open to differing suggestions as well. 😄 

Can you mention the required Node version in https://github.com/webpack/webpack.js.org/blob/master/.github/CONTRIBUTING.md?

**Comment by TheDutchCoder** [comment]
@simon04 Alright I removed it :)

It seems the Node version is already mentioned in Contributing, so I think we're good there?

**Pull request merged**
