### PR TITLE
docs(api): update commands

### PR DESCRIPTION
**Pull request by snitin315**
To be merged after the new `webpack-cli` release.

Refers - https://github.com/webpack/webpack-cli/pull/2303 https://github.com/webpack/webpack-cli/pull/2357

### CODE REVIEW

**Comment by chenxsan** [comment]
Let's convert it into draft, and set it ready for review when a new version `webpack-cli` including this feature is released.

**Comment by snitin315** [comment]
The new `webpack-cli` version is released 🚀

**Comment by alexander-akait** [comment]
Also we have `watch` (alias `--watch`) and `build` commands (alias `bundle`, `b`, or without command)

**Comment by snitin315** [comment]
https://github.com/webpack/webpack.js.org/pull/4450

**Pull request closed without merging**
