### PR TITLE
Add debug info

### PR DESCRIPTION
**Pull request by montogeek**

### CODE REVIEW

**Comment by montogeek** [comment]
@chenxsan Any idea why running Cypress is removing everything from `/dist`?
Check these 2 deploys:
`/dist` folder contents doesn't exist: https://travis-ci.org/github/webpack/webpack.js.org/jobs/703700941
`/dist` folder contents exist: https://travis-ci.org/github/webpack/webpack.js.org/jobs/703704529

The only change was removing `yarn cypress:ci`.
This started failing after your PR got merged into master:
image

Please check it out, if you can't find anything we will need to remove cypress run until this gets fixed.

**Comment by chenxsan** [comment]
@montogeek Thanks for heads-up, I'm investigating it.

**Comment by chenxsan** [comment]
@montogeek I think I've figured out what's going on here. `cypress:ci` would start the server with `yarn start` which would clean the `dist` folder causing post stage to fail. I've moved the `cypress:ci` script before `yarn build` now. Could you please check this pull request https://github.com/webpack/webpack.js.org/pull/3813 to see if it fixed this issue?

**Comment by EugeneHlushko** [comment]
merged the fix, lets see if it fixes it

**Comment by EugeneHlushko** [comment]
Yup deploy fixed CC @montogeek @chenxsan

**Comment by montogeek** [comment]
@chenxsan Thanks!

**Pull request closed without merging**
