### PR TITLE
fix(nav): makes the nav to show always on the top

### PR DESCRIPTION
**Pull request by pranshuchittora**
Improved the UX by making the nav always to show on the top of the page

**Motivation**
In order to navigate to another page, a user has to scroll to the top of the page in order to access the navigation bar.
The solution to this is
1. Put a button at the bottom of the page, clicking on which scrolls the page to the top.
2. Make the nav bar fixed to the top of the page.

### CODE REVIEW

**Comment by pranshuchittora** [comment]
@wizardofhogwarts pls review the new changes.

**Comment by pranshuchittora** [comment]
Any suggestions regarding the page `margin-top` ?

**Comment by pranshuchittora** [comment]
Ready to merge 
cc @montogeek

**Comment by pranshuchittora** [comment]
@dhruvdutt pls review the updated changes.

**Comment by pranshuchittora** [comment]
Final call pls.
cc @montogeek

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
