### PR TITLE
upgrade html-loader

### PR DESCRIPTION
**Pull request by chenxsan**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I recommend to wait new version of `html-webpack-plugin`, there are other small bugs

**Comment by chenxsan** [comment]
@alexander-akait I'm checking if the new feature can fix the problem. Seems not.

**Comment by chenxsan** [comment]
Error detail:

```

20:31:51.240 | ERROR in ReferenceError: URL is not defined
-- | --
20:31:51.240 | at evalmachine.<anonymous>:76585:46
20:31:51.240 | at evalmachine.<anonymous>:76586:13
20:31:51.240 | at evalmachine.<anonymous>:76713:12
20:31:51.241 | at webpackUniversalModuleDefinition (evalmachine.<anonymous>:3:20)
20:31:51.241 | at evalmachine.<anonymous>:10:3
20:31:51.241 | at Script.runInContext (vm.js:143:18)
20:31:51.241 | at Script.runInNewContext (vm.js:148:17)
20:31:51.241 | at module.exports (/vercel/workpath0/node_modules/eval/eval.js:73:12)
20:31:51.241 | at /vercel/workpath0/node_modules/static-site-generator-webpack-plugin/index.js:42:22
20:31:51.241 | at fn (/vercel/workpath0/node_modules/webpack/lib/Compilation.js:401:9)
20:31:51.241 | ssg (webpack 5.23.0) compiled with 1 error in 55120 ms


```

**Comment by alexander-akait** [comment]
Bug in `static-site-generator-webpack-plugin` too

**Comment by alexander-akait** [comment]
Here example how to fix it https://github.com/webpack/webpack/pull/12695

**Comment by alexander-akait** [comment]
```
compiler.options.module.defaultRules.push({
  compiler: /mini-css /, // or whatever the name prefix for mini-css child compilers is
  parser: { url: "relative" }
})
```

**Comment by chenxsan** [comment]
> Here example how to fix it [webpack/webpack#12695](https://github.com/webpack/webpack/pull/12695)

I believe I've added it. See https://github.com/webpack/webpack.js.org/pull/4629/files#diff-0e2cd931e69e0a20bcaabcf809440adb57cefc39f36a161bad867d039de6dc9c.

**Comment by chenxsan** [comment]
> Bug in `static-site-generator-webpack-plugin` too

Seems to be a problem from the `eval` package:

image

And here's the code webpack generated:

image


Unfortunately both `eval` and `static-site-generator-webpack-plugin` are unmaintained now.

**Comment by chenxsan** [comment]
I might found the culprit https://github.com/nodejs/node/issues/28823.

**Comment by chenxsan** [comment]
So far it works. But in the end we might need to replace `static-site-generator-webpack-plugin` with something else because:

1. it's no longer maintained
2. it modifies `compilation.assets` which will be a problem because of:
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated
```

**Comment by alexander-akait** [comment]
> it's no longer maintained

We can move this plugin inside `webpack.js.org` repo and update old API

**Comment by chenxsan** [comment]
It surprised me, but `eval` author had merged the fix.

**Pull request merged**
