### PR TITLE
fix(Configuration.scss): fix config dialog pre element with block style

### PR DESCRIPTION
**Pull request by JunIce**
fix config dialog

image

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- **Remove these instructions from your PR as they are for your eyes only.**

[1]: https://github.com/openjs-foundation/EasyCLA#openjs-foundation-cla
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by chenxsan** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2) - login: @JunIce / name: JSparow . The commit ([0324ad9](https://github.com/webpack/webpack.js.org/commit/0324ad96c382dc7bc2ba6cfe994001062102ab0b)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

@JunIce Could you sign the CLA here?

**Comment by JunIce** [comment]
done! thanks!

**Comment by JunIce** [comment]
> > [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2)
> > 
> > * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2) - login: @JunIce / name: JSparow . The commit ([0324ad9](https://github.com/webpack/webpack.js.org/commit/0324ad96c382dc7bc2ba6cfe994001062102ab0b)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18915764/61886109/6344/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).
> 
> @JunIce Could you sign the CLA here?

Done! Thanks.

**Review by chenxsan — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
