### PR TITLE
changing source-maps to source-map

### PR DESCRIPTION
**Pull request by joaomelo**
according to https://webpack.js.org/configuration/devtool the "devtool" option should be source-map (it was source-maps in the file).

### CODE REVIEW

**Comment by chenxsan** [comment]
@joaomelo I think you need to sign the Contributor License Agreement.

**Comment by joaomelo** [comment]
> @joaomelo I think you need to sign the Contributor License Agreement.

hi :)

i've tried a few times but i think i am doing something wrong :(

in the site, it shows to me as signed but here in the pull resquest is still pending. didn't figure out why.

**Comment by snitin315** [comment]
@joaomelo try closing and reopening pull request.

**Comment by joaomelo** [comment]
> @joaomelo try closing and reopening pull request.

worked :) thank you  @snitin315

**Comment by EugeneHlushko** [comment]
Thanks!

**Comment by joaomelo** [comment]
thank you. webpack is awesome.

**Pull request merged**
