### PR TITLE
chore: update voting app link

### PR DESCRIPTION
**Pull request by anshumanv**
_describe your changes..._

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by anshumanv** [comment]
image

**Comment by anshumanv** [comment]
image

**Comment by anshumanv** [comment]
@EugeneHlushko updated.

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
