### PR TITLE
docs(license): simplify and harmonize licenses

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by bebraw** [comment]
You could check this with someone from @jsfoundation as they manage the legal side. Poke @kborchers.

**Comment by kborchers** [comment]
I believe this is ok but will have legal take a look and let you know ASAP to be on the safe side.

**Comment by skipjack** [comment]
@kborchers any update so far? No rush, just curious.

**Comment by kborchers** [comment]
Sorry, nothing from legal yet but it's in the queue. I'll ping them again Monday for an update.

**Comment by StevenAyr** [comment]
Apologies for the delay in this review. Everything looks good to go here.

**Comment by skipjack** [comment]
Great, thanks @StevenAyr!

**Pull request merged**
