### PR TITLE
Babel-loader example is misleading

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
I have used that example to configure babel-loader and it wasn't working as by default Babel won't transpile the code without a preset passed to it.

### CODE REVIEW

**Comment by simon04** [comment]
@Maxim-Filimonov, thanks for bringing this up. For fixing it, I'd like to take a different approach:

@webpack/documentation-team, maybe we should use a loader which works without any additional configuration? Such as `url-loader`? Or even more basic, the `raw-loader` for text files? The `concepts` page should focus on the concepts and not get lost in the configuration details of a specific loader.

**Comment by bebraw** [comment]
Yup. `url-loader` or `raw-loader` would be enough.

**Comment by simon04** [comment]
Let's go with `raw-loader` for `.txt` files.

@Maxim-Filimonov, would you be interested in PR this? The following lines would need to be changed:
* https://github.com/webpack/webpack.js.org/blame/623862481703ba35d14c6e3545e1615449c5bf9c/content/concepts/index.md#L88
* https://github.com/webpack/webpack.js.org/blame/623862481703ba35d14c6e3545e1615449c5bf9c/content/concepts/index.md#L88
* https://github.com/webpack/webpack.js.org/blame/623862481703ba35d14c6e3545e1615449c5bf9c/content/concepts/index.md#L127

**Comment by Maxim-Filimonov** [comment]
@simon04 Sure I'll make required changes to use raw-loader.

**Comment by Maxim-Filimonov** [comment]
See #1270

**Pull request closed without merging**
