### PR TITLE
CleanWebpackPlugin | Requires a config object

### PR DESCRIPTION
**Pull request by priyankO-0**
new CleanWebpackPlugin() | requires a config object than an array

_describe your changes..._

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by montogeek** [comment]
Please also update the dependency in the package.json

**Comment by EugeneHlushko** [comment]
@montogeek which package.json do you mean? i dont see us asking for specific version in the guides

**Comment by montogeek** [comment]
We don't ask about it, but it is there:
image

image
image

**Comment by EugeneHlushko** [comment]
Ah there it is, i couldn't find it with algolia :)

**Comment by EugeneHlushko** [comment]
@montogeek lets get this one in and i'll do a follow up ?

**Comment by montogeek** [comment]
Thanks!

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
