### PR TITLE
Update configuration-languages.md

### PR DESCRIPTION
**Pull request by lornally**
coffee-script has been move to coffeescript

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by chenxsan** [comment]
Buggy CLA bot.

**Comment by chenxsan** [comment]
@lornally Can you sign the CLA here https://cla.js.foundation/webpack/webpack.js.org?

**Comment by lornally** [comment]
i have sign cla. :)

**Review by chenxsan — APPROVED** [review]

**Comment by chenxsan** [comment]
@lornally Thank you for your contribution.

**Pull request merged**
