### PR TITLE
chore(organization): fixes the breaking layout of organization page

### PR DESCRIPTION
**Pull request by pranshuchittora**
fixed the breaking layout of the organization page.

**_Overflowing content (check maintainers in the below image)_**

Screenshot from 2019-06-27 14-56-11

_Describe your changes..._
- Fixes overflowing content
- Makes child in the centre

### CODE REVIEW

**Comment by montogeek** [comment]
Can you please post the before/after?

**Comment by pranshuchittora** [comment]
Before => https://webpack.js.org/organization/
After => https://deploy-preview-3147--webpackjsorg-netlify.netlify.com/organization/

**Comment by montogeek** [comment]
Please leave it aligned to the left.

**Comment by pranshuchittora** [comment]
> Please leave it aligned to the left.

Alright, Done.
@montogeek I think it's ready to merge.

**Comment by pranshuchittora** [comment]
> image
> 
> Doesn't work, latest firefox on windows 10


@EugeneHlushko pls elaborate the issue

**Comment by pranshuchittora** [comment]
As I can see from the screenshot you have attached, the entire image of the maintainer is visible. Hence it's working. 

The issue with the current version is, that the image of the maintainer is getting cropped as the height of the card(box) is fixed to `480px`

**Comment by pranshuchittora** [comment]
Working fine for me in Firefox@latest

Screenshot from 2019-06-28 20-06-41

**Comment by EugeneHlushko** [comment]
Right, so it wasn't just cut by button by name on a rect.

@montogeek do you know why it has 75 padding on the right? if there are multiple maintainers they dont really fit.

image

**Comment by montogeek** [comment]
Probably a flex issue

**Comment by pranshuchittora** [comment]
So how would I proceed with this PR

**Comment by pranshuchittora** [comment]
@montogeek anymore changes?

**Comment by EugeneHlushko** [comment]
@pranshuchittora remove the 75 padding on the right, and lets re-test

**Comment by EugeneHlushko** [comment]
@pranshuchittora i think it looks better now, doesn't break. Did you try different resolutions and browsers?

**Comment by pranshuchittora** [comment]
No issues 🤘

**Comment by pranshuchittora** [comment]
It's been more than a month, since the last update. Pls, clear this PR.
cc @montogeek

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
