### PR TITLE
Splash Page

### PR DESCRIPTION
**Pull request by skipjack**
Ok so this is still very much a work in progress but I think it's ready for some feedback.

- [x] Update the layout of the splash page
- [x] Show example (`index.md` currently, interactive one is still in discussion)
- [x] Update sponsors section
- [x] Update footer styling
- [x] Work on mobile viewport

For the visualization:

- [x] Display output files
- [x] Start rotating the cube (needs some tweaking)
- [x] Start work on modules/output visualization

Here's a quick demo of what it looks like now, I'll add more soon:

### CODE REVIEW

**Comment by NejcZdovc** [comment]
Created #261 so that we can easily control all html elements and we don't have a bit svg file as discussed in #259.

**Comment by skipjack** [comment]
@NejcZdovc #261 has been pulled into here.

@bebraw seeing some odd [build errors](https://travis-ci.org/webpack/webpack.js.org/builds/168461877) that I can't quite make sense of starting on line 1277. Looks like it has to do with the interactive package.

**Comment by bebraw** [comment]
@skipjack There's a file naming mismatch. `splash-viz.jsx` doesn't exist.

**Comment by skipjack** [comment]
Doh, fixed it (js => jsx)

**Comment by NejcZdovc** [comment]
One thing that was quite off for me is the bundle size for JS. Most of the webpack users use it for web sites / apps and loading 19 MB in one chunk is something that no one wants. Maybe changing this to some smaller value would be batter, so that users will not be leaded into thinking that using webpack will lead into big bundle.

**Comment by skipjack** [comment]
Haha yea you're definitely right, 19 megs is way too high. I'll make sure they all have realistic values before merging.

**Comment by skipjack** [comment]
Ok cleaned this up a bit more. Once I add the links between modules in the visualization I think we should merge. The top section will take a bit more work but I can open another PR for it. It's starting to look pretty good on most viewports now. Here's a few demos:

Desktop:



Mobile:



Feedback welcome! Just keep in mind this is only round one.

**Comment by SpaceK33z** [comment]
@skipjack: first impression: WOW! It looks really nice :). Some feedback:

- When hovering on one of the "dependencies" on the left of the page, maybe display lines between them so it is clear that the files dependent on each other and what their relation is? Just an idea though, feel free to ignore.
- If I leave the page open, go to another tab and then come back after about 30 seconds, the spinning cube spins *very* quickly for a while.
- The "donate" button for Open Collective is gone. The original button for OC was a bit out-of-place style-wise, but maybe we can build a custom "donate" button?

**Comment by skipjack** [comment]
@SpaceK33z thanks for the feedback!

- Working on adding the links now. I think showing the connections a module has on hover is a great idea, I'll try to work that in.
- Yea the cube is still using a CSS animation, but I'm planning on moving this to more of a javascript implementation which should fix that issue.
- Definitely doable, @NejcZdovc was suggesting not hiding the one from the navigation on mobile screens, meaning there'd always be one displayed on the top right. We could always do another more prominent one in the sponsors/support section as well.

**Comment by skipjack** [comment]
Ok added links between the modules and cleaned up a bit. The visualization (top) section is by no means done, I'll be opening another PR for that soon. As soon as CI passes, I'm going to merge... if anyone has more feedback or notices any problems on this page feel free to open an issue.

**Comment by montogeek** [comment]
Was this deployed? I am still see the old page

**Comment by bebraw** [comment]
Not yet.

**Pull request merged**
