### PR TITLE
refactor(starter-kit): improves UX of starter kit and fixes layout

### PR DESCRIPTION
**Pull request by pranshuchittora**
Improves starter kit layout -> https://webpack.js.org/starter-kits/

Visual Diff
https://github.com/webpack/webpack.js.org/pull/3146#issuecomment-506752218

### CODE REVIEW

**Comment by pranshuchittora** [comment]
Review Requested  @anshumanv @EugeneHlushko @montogeek

**Comment by EugeneHlushko** [comment]
For layout improvements, i suggest you create some context using screenshots to demonstrate before and after 👍

**Comment by pranshuchittora** [comment]
**Before** 

Screenshot from 2019-06-28 19-50-31


**After**
Screenshot from 2019-06-28 19-50-43

**Comment by EugeneHlushko** [comment]
Can you make it a table instead? It was supposed to be a table but i guess nobody finished that page. It would make it much more compact

**Comment by EugeneHlushko** [comment]
It can be flex layout but just one row per starter-kit

**Comment by pranshuchittora** [comment]
@EugeneHlushko one row per starter kit might become a bit congested.
IMO this looks better as compared to the previous one.
 
Let's discuss

**Comment by EugeneHlushko** [comment]
If you try to put it into a table layout as it was intended to be and screen that to compare would be super useful

**Comment by EugeneHlushko** [comment]
If you are having issues, please ping me and ill do it

**Comment by pranshuchittora** [comment]
Will do that.

Few questions
- 3 column table i.e. Project Name, Maintainer and Tags or  just rows

**Comment by EugeneHlushko** [comment]
Yup, from the code that was originally there:
```
           <div className="table-th">Project Name</div>
            <div className="table-th">Maintainer</div>
            <div className="table-th">Tags</div>
```

**Comment by pranshuchittora** [comment]
@EugeneHlushko have a look at the latest changes.

Some glimpses.

Screenshot from 2019-06-29 01-42-22

**Comment by EugeneHlushko** [comment]
Amazing!!! 🚀  do you agree it looks better @pranshuchittora ?

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
