### PR TITLE
docs(guides) code splitting grammar and fix local links

### PR DESCRIPTION
**Pull request by EugeneHlushko**
While looking at #2790 
I've noticed a few things to do:
- Grammar
- broken links while in dev

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Yeah we have this issue when dev server locally wont resolve url unless it has a trailing slash

**Comment by EugeneHlushko** [comment]
It works for prod i know

**Comment by wizardofhogwarts** [comment]
> Yeah we have this issue when dev server locally wont resolve url unless it has a trailing slash

fine then :+1:

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
