### PR TITLE
Fix Broken links

### PR DESCRIPTION
**Pull request by nveenjain**
These links were broken in Plugins Page. Fixed them, will try to find more.

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by montogeek** [comment]
There is a lot more :)

**Comment by nveenjain** [comment]
Yups, will change them, was in a hurry, and noticed this, so sent a PR..

**Comment by montogeek** [comment]
@nveenjain Do you find more?

**Comment by nveenjain** [comment]
No, fortunately, not any more, since the only two files that were deleted were compiler and compilation. reference to these two files might have caused trouble, fixed that.

**Comment by montogeek** [comment]
Thanks!

**Pull request merged**
